# Annotation analysis

This noteboook

* illustrates the steps of the analysis currently implemented
* is used to analyze and monitor workers batch by batch

In [3]:
from load_data import load_experiment_data
from analyze_workers import get_worker_analysis
from analyze_pairs import get_pair_analysis
from analyze_pairs import show_pairs_of_worker
from analyze_pairs import compare_runs
from calculate_iaa import get_agreement
from clean_annotations import clean_annotations
from analyze_relations_and_examples import agreement_relations_across_runs

# Analyze worker contradictions:

* Workers with highest contradiction to annotations ratio appear on top
* use the pandas dataframe sort method to sort on other values: 

`df.sort_values(by, axis=0, ascending=True, inplace=False, kind='quicksort', na_position='last')`

### Current batch

In [17]:
run = 3
batch = 39
n_q = 70
group = 'experiment1'

data_dict_list = load_experiment_data(run, group, n_q, batch, remove_not_val = True)
name = f'run{run}-group_{group}-batch{batch}'.replace('*', '-all-')
df, filepath = get_worker_analysis(data_dict_list, name)
df.drop(['annotations'], axis = 1, inplace=True)
df

creating file with uuid run3-group_experiment1/qu70-s_qu70-batch39.csv
added unique ids - file can be found at: ../data/prolific_output_uuid/run3-group_experiment1/qu70-s_qu70-batch39.csv
Discarded 0.0 annotations.

,workerid,n_annotations,n_contradictions,n_fails,contradiction_annotation_ratio,fail_annotation_ratio,average_time_question,"(implied_category, rare)","(afforded_unusual, rare)","(afforded_unusual, unusual)",...,"(typical_of_concept, unusual)","(implied_category, impossible)","(afforded_unusual, impossible)","(impossible, typical_of_concept)","(afforded_usual, impossible)","(impossible, typical_of_property)","(rare, typical_of_concept)","(rare, typical_of_property)","(affording_activity, impossible)","(affording_activity, rare)"
1,5c129f53c27527000196c925,78,36,0,0.461538,0.000000,9.412782,2.0,3.0,3.0,...,4.0,1.0,2.0,1.0,1.0,1.0,1.0,1.0,NaN,NaN
3,5c62ed99eed63200017d88c3,78,26,0,0.333333,0.000000,15.093103,3.0,1.0,NaN,...,1.0,3.0,NaN,3.0,1.0,1.0,3.0,3.0,2.0,3.0
6,5d3c95ae98afa00015f636cb,78,20,1,0.256410,0.012821,10.307128,3.0,3.0,4.0,...,NaN,NaN,1.0,NaN,1.0,NaN,NaN,NaN,NaN,1.0
4,5c7bb80b54c5d600175fd576,78,15,0,0.192308,0.000000,12.297564,2.0,2.0,2.0,...,NaN,NaN,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8,5dee8dc525332652f941f79b,78,11,0,0.141026,0.000000,14.602936,NaN,1.0,NaN,...,NaN,NaN,1.0,NaN,2.0,NaN,2.0,NaN,NaN,2.0
9,5e86c320939b3030601f7fcb,78,8,1,0.102564,0.012821,6.839692,1.0,2.0,2.0,...,NaN,NaN,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7,5da306a22e89480012ef4176,78,7,0,0.089744,0.000000,21.891295,1.0,1.0,1.0,...,NaN,1.0,1.0,NaN,1.0,NaN,NaN,NaN,NaN,NaN
5,5d28f52cf5de2a00177893bf,78,6,0,0.076923,0.000000,11.509808,NaN,NaN,NaN,...,NaN,1.0,1.0,1.0,NaN,NaN,NaN,1.0,NaN,NaN
2,5c1a60905b2ab700015af8a1,78,5,0,0.064103,0.000000,5.529051,NaN,NaN,NaN,...,NaN,2.0,NaN,1.0,NaN,1.0,NaN,NaN,1.0,NaN
0,5a3ad6ba2f3c2500018bc4e4,117,6,0,0.051282,0.000000,7.256162,2.0,3.0,1.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

### All annotations

* Workers with highest contradiction to annotations ratio appear on top
* use the pandas dataframe sort method to sort on other values: 
* Check how the behavior of a specific worker with many contradictions compares to other workers

`df.sort_values(by, axis=0, ascending=True, inplace=False, kind='quicksort', na_position='last')`

In [20]:
run = '*'
batch = '*'
n_q = '*'
group = 'experiment1'

data_dict_list = load_experiment_data(run, group, n_q, batch, remove_not_val = True)
name = f'run{run}-group_{group}-batch{batch}'.replace('*', '-all-')
df, filepath = get_worker_analysis(data_dict_list, name)
df.drop(['annotations'], axis = 1, inplace=True)
df[:10]

Discarded 655.0 annotations.

,workerid,n_annotations,n_contradictions,n_fails,contradiction_annotation_ratio,fail_annotation_ratio,average_time_question,"(afforded_unusual, unusual)","(typical_of_property, unusual)","(implied_category, unusual)",...,"(implied_category, impossible)","(affording_activity, impossible)","(afforded_unusual, impossible)","(afforded_usual, impossible)","(implied_category, rare)","(rare, typical_of_concept)","(rare, typical_of_property)","(afforded_unusual, rare)","(affording_activity, rare)","(afforded_usual, rare)"
383,5c042ba4bb85e60001c05c83,72,47,0,0.652778,0.000000,7.812292,1.0,3.0,5.0,...,3.0,1.0,1.0,2.0,6.0,4.0,3.0,2.0,3.0,2.0
631,5d76a2dc2a476a0001ce6843,72,45,1,0.625000,0.013889,16.482319,NaN,3.0,5.0,...,3.0,2.0,NaN,NaN,5.0,5.0,3.0,NaN,5.0,NaN
298,5e4e86b070e1ed2d6e4e3f62,72,42,1,0.583333,0.013889,4.293264,NaN,5.0,5.0,...,2.0,1.0,NaN,NaN,5.0,4.0,5.0,NaN,4.0,NaN
303,5e7cbbbcf0a5a004b60b48f7,72,41,1,0.569444,0.013889,11.482222,NaN,2.0,1.0,...,4.0,4.0,NaN,NaN,5.0,4.0,6.0,NaN,6.0,NaN
402,5c1f3a7c10677f0001da2157,72,39,0,0.541667,0.000000,9.921528,3.0,5.0,5.0,...,1.0,1.0,1.0,1.0,3.0,1.0,4.0,2.0,1.0,1.0
241,5c91321c0375460001034cb8,71,38,0,0.535211,0.000000,12.942127,2.0,6.0,6.0,...,4.0,1.0,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
347,5ddd128c961cb3c6780ff181,72,36,0,0.500000,0.000000,8.403056,2.0,2.0,5.0,...,3.0,2.0,1.0,NaN,4.0,3.0,1.0,2.0,1.0,NaN
625,5e76ab49dec4562243b421f9,72,35,2,0.486111,0.027778,18.781028,NaN,3.0,2.0,...,2.0,3.0,NaN,NaN,2.0,4.0,3.0,NaN,4.0,NaN
324,5ba4f45c4286a00001ea457f,72,34,1,0.472222,0.013889,9.803042,NaN,4.0,4.0,...,2.0,2.0,NaN,NaN,3.0,2.0,3.0,NaN,3.0,NaN
15,5dc0395f2a1dd64710661ccd,71,33,0,0.464789,0.000000,3.745113,4.0,5.0,5.0,...,3.0,1.0,1.0,1.0,NaN,NaN,NaN,NaN,NaN,NaN

In [30]:
# Good workers
#df[-50:]

### Get all contradictions and fails of a particular worker 

* Check if a specfic worker continuously contradicts themselves (and fails checks)

In [21]:
# copy from above - worker with many disagreements in target batch
worker = '5c62ed99eed63200017d88c3'


# df.loc[df['column_name'] == some_value]
df.loc[df['workerid'] == worker]

,workerid,n_annotations,n_contradictions,n_fails,contradiction_annotation_ratio,fail_annotation_ratio,average_time_question,"(afforded_unusual, unusual)","(typical_of_property, unusual)","(implied_category, unusual)",...,"(implied_category, impossible)","(affording_activity, impossible)","(afforded_unusual, impossible)","(afforded_usual, impossible)","(implied_category, rare)","(rare, typical_of_concept)","(rare, typical_of_property)","(afforded_unusual, rare)","(affording_activity, rare)","(afforded_usual, rare)"
610,5c62ed99eed63200017d88c3,78,26,0,0.333333,0.0,15.093103,NaN,NaN,1.0,...,3.0,2.0,NaN,1.0,3.0,3.0,3.0,1.0,3.0,NaN

# Analyze pairs

* compars number of annotator contradictions among pairs

### Current batch:

In [12]:
run = '3'
batch = '37'
n_q = '*'
group = 'experiment1'

data_dict_list = load_experiment_data(run, group, n_q, batch, remove_not_val = True)
name = f'run{run}-group_{group}-batch{batch}'.replace('*', '-all-')
df, filepath = get_pair_analysis(data_dict_list, name)
df.drop(['annotations_with_contradiction'], axis = 1, inplace=True)
df

Discarded 0.0 annotations.

,pair,n_annotations,n_workers,n_contradictions,n_workers_contradicting,ratio_workers_contradicting,contradiction_annotation_ratio,average_time_pair,workers_contradicting,workers_not_contradicting,...,"(afforded_unusual, impossible)","(afforded_usual, impossible)","(implied_category, impossible)","(affording_activity, unusual)","(affording_activity, rare)","(typical_of_property, unusual)","(rare, typical_of_property)","(affording_activity, impossible)","(impossible, typical_of_property)","(impossible, typical_of_concept)"
0,roll-shaft,90,9,30,7,0.777778,0.333333,60.381378,5ab78e575cd1050001619cdf 5d4b03ce99e63300153a4...,5bd056f9263e0a00016d20d3 5e1cf0eb65b6d3071f489de9,...,2.0,2.0,2.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,roll-cartridge,90,9,24,5,0.555556,0.266667,60.381378,5ab78e575cd1050001619cdf 5bd056f9263e0a00016d2...,5d4b03ce99e63300153a42d6 5d5357e0b45aff0001980...,...,2.0,1.0,2.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,round-bottle,90,9,21,8,0.888889,0.233333,60.381378,5ab78e575cd1050001619cdf 5d4b03ce99e63300153a4...,5bd056f9263e0a00016d20d3,...,NaN,NaN,3.0,3.0,3.0,NaN,NaN,2.0,NaN,1.0
2,round-almond,90,9,20,5,0.555556,0.222222,60.381378,5d4b03ce99e63300153a42d6 5ddd128c961cb3c6780ff...,5ab78e575cd1050001619cdf 5bd056f9263e0a00016d2...,...,NaN,NaN,2.0,3.0,2.0,2.0,NaN,3.0,1.0,1.0
6,red-ink,90,9,16,6,0.666667,0.177778,60.381378,5d4b03ce99e63300153a42d6 5d5357e0b45aff0001980...,5ab78e575cd1050001619cdf 5bd056f9263e0a00016d2...,...,NaN,NaN,1.0,4.0,5.0,NaN,NaN,1.0,NaN,2.0
1,red-fern,91,10,12,3,0.300000,0.131868,60.547040,5d4b03ce99e63300153a42d6 5ddd128c961cb3c6780ff...,5ab78e575cd1050001619cdf 5bd056f9263e0a00016d2...,...,NaN,NaN,NaN,2.0,2.0,1.0,1.0,NaN,NaN,NaN
5,red-pansy,90,9,10,4,0.444444,0.111111,60.381378,5d4b03ce99e63300153a42d6 5ddd128c961cb3c6780ff...,5ab78e575cd1050001619cdf 5bd056f9263e0a00016d2...,...,NaN,NaN,2.0,NaN,1.0,NaN,NaN,NaN,NaN,1.0
7,_check1-_check1,9,9,0,0,0.000000,0.000000,603.813778,,5ab78e575cd1050001619cdf 5bd056f9263e0a00016d2...,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8,_test3-_test,9,9,0,0,0.000000,0.000000,603.813778,,5ab78e575cd1050001619cdf 5bd056f9263e0a00016d2...,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

### Get rows with pairs annotated by specific workers:

* Check if a worker in the only one contradicting or if others also had issues with the pairs

In [13]:
worker = '5bd056f9263e0a00016d20d3'

show_pairs_of_worker(worker, df)

Worker 5bd056f9263e0a00016d20d3 contradicted themselves in the following pairs:

roll-cartridge 	 total workers contradicting themselves: 5

### Compare to entire annotation set

In [7]:
run = '*'
batch = '*'
n_q = '*'
group = 'experiment1'

data_dict_list = load_experiment_data(run, group, n_q, batch, remove_not_val = True)
name = f'run{run}-group_{group}-batch{batch}'.replace('*', '-all-')
df, filepath = get_pair_analysis(data_dict_list, name)
df.drop(['annotations_with_contradiction'], axis = 1, inplace=True)
df

Discarded 655.0 annotations.

,pair,n_annotations,n_workers,n_contradictions,n_workers_contradicting,ratio_workers_contradicting,contradiction_annotation_ratio,average_time_pair,workers_contradicting,workers_not_contradicting,...,"(affording_activity, rare)","(implied_category, rare)","(rare, typical_of_property)","(implied_category, impossible)","(rare, typical_of_concept)","(affording_activity, impossible)","(afforded_unusual, impossible)","(afforded_usual, rare)","(afforded_unusual, rare)","(afforded_usual, impossible)"
26,roll-spindle,50,5,22,4,0.8,0.44,57.711660,5dc0395f2a1dd64710661ccd 5ddc56fbf290e7bbfa964...,5de6be6912bcf6041b3276ba,...,NaN,NaN,NaN,2.0,NaN,NaN,2.0,NaN,NaN,2.0
23,roll-mandrel,50,5,21,5,1.0,0.42,57.711660,5dc0395f2a1dd64710661ccd 5ddc56fbf290e7bbfa964...,,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25,roll-pipe,50,5,19,4,0.8,0.38,57.711660,5dc0395f2a1dd64710661ccd 5ddc56fbf290e7bbfa964...,5de6d199a23d79000bf9aef9,...,NaN,NaN,NaN,NaN,NaN,NaN,1.0,NaN,NaN,1.0
227,roll-lamp,50,5,17,4,0.8,0.34,85.335380,5acb5910e1546900019c413a 5d3f14f66a8a4e0018c17...,5c5758e9efe1550001dc31b6,...,NaN,NaN,NaN,1.0,NaN,NaN,2.0,NaN,NaN,1.0
39,roll-nut,50,5,16,5,1.0,0.32,53.847560,5a4bf85dac413f0001e6076a 5bfa79fdb8a4c50001b8a...,,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
228,round-cabbage,95,15,0,0,0.0,0.00,111.480262,,5acb5910e1546900019c413a 5c5758e9efe1550001dc3...,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
232,round-cheeseburger,50,5,0,0,0.0,0.00,91.594320,,5bb3e96383d96f0001184ef4 5c8f9cfea4b1bd0017fb6...,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
379,round-bracelet,35,5,0,0,0.0,0.00,150.287029,,5d38b5bc463d580015a05bcc 5dd4189ef30aa640b4e9c...,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
79,red-paint,95,15,0,0,0.0,0.00,126.641871,,5ab84333f69e940001d8f0af 5c9be64e7eead40016aeb...,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
315,red-rhino,50,5,0,0,0.0,0.00,202.773340,,5d362118bd3f570016067a6b 5d40128e2b6eaf00155f2...,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

### Compare contradictions between runs:

In [8]:
run = '1'
batch = '*'
n_q = '*'
group = 'experiment1'

data_dict_list = load_experiment_data(run, group, n_q, batch, remove_not_val = True)
name = f'run{run}-group_{group}-batch{batch}'.replace('*', '-all-')
df1, filepath = get_pair_analysis(data_dict_list, name)
print(f'analysis can be found at: {filepath}')

run = '3'
batch = '*'
n_q = '*'
group = 'experiment1'

data_dict_list = load_experiment_data(run, group, n_q, batch, remove_not_val = True)
name = f'run{run}-group_{group}-batch{batch}'.replace('*', '-all-')
df2, filepath = get_pair_analysis(data_dict_list, name)
print(f'analysis can be found at: {filepath}')

name1 = '1'
name2 = '3'
compare_runs(name1, name2, df1, df2, comp = 'all')
print()
compare_runs(name1, name2, df1, df2, comp = 'pairs')

Discarded 0.0 annotations.
analysis can be found at: ../analyses/pairs/run1-group_experiment1-batch-all-.csv
Discarded 655.0 annotations.
analysis can be found at: ../analyses/pairs/run3-group_experiment1-batch-all-.csv
Set 1 as a contradiction ratio of 0.26912294753704447
Set 3 as a contradiction ratio of 0.19720597790773228
The ratio is based on the number of workers annotating a pair.
A worker always annotates a full set.

Set 1 as a contradiction ratio of 0.22396856581532418
Set 3 as a contradiction ratio of 0.21801470588235294
The ratio is based on the number of workers annotating a pair.
A worker always annotates a full set.
This analysis only includes pairs annotated in run 1 and run 3.

(0.22396856581532418, 0.21801470588235294)

# Inter-annotator agreement

* Total agreement
* Agreement by relations
* agreement after removing annotators with many contradictions/annotators who fail checks/contradictory annotations

## Total iaa:

In [12]:
run = '3'
batch = '*'
n_q = '*'
group = 'experiment1'
print(f"Run {run}:")
data_dict_list = load_experiment_data(run, group, n_q, batch, remove_not_val = True)
get_agreement(data_dict_list)

run = '1'
batch = '*'
n_q = '*'
group = 'experiment1'
print(f"Run {run}:")
data_dict_list = load_experiment_data(run, group, n_q, batch, remove_not_val = True)

get_agreement(data_dict_list)

Run 3:
Discarded 655.0 annotations.
Krippendorff's alpha: 0.24831683716387543
Proportional agreement (pairwise): 0.6398473738324435

Run 1:
Discarded 0.0 annotations.
Krippendorff's alpha: 0.2413329996998821
Proportional agreement (pairwise): 0.6204625909422005

{'Krippendorff': 0.2413329996998821, 'Proportional': 0.6204625909422005}

## IAA by relation

In [11]:
runs = ['3', '1']
experiment_name = 'experiment1'
path, df = agreement_relations_across_runs(runs, experiment_name)
print(f'Results written to: {path}')
df

Discarded 655.0 annotations.
Discarded 0.0 annotations.
Results written to: ../analyses/iaa/relations_runs3-1.csv

,relation,3_Krippendorff,3_Proportional,1_Krippendorff,1_Proportional
0,test_false,0.084517,0.754927,NaN,NaN
1,afforded_usual,0.213991,0.687440,0.336767,0.698580
2,afforded_unusual,0.011321,0.519324,0.108460,0.557623
3,variability_subcategories,NaN,NaN,0.157270,0.579637
4,creative,0.061815,0.553464,0.040020,0.524894
5,variability_open,0.220998,0.608822,0.143751,0.580081
6,impossible,0.145979,0.675786,0.183925,0.679565
7,implied_category,0.277551,0.662064,0.260459,0.629956
8,affording_activity,0.195439,0.653329,0.149149,0.672259
9,rare,0.167334,0.600040,NaN,NaN
10,unusual,0.174283,0.584762,0.120147,0.561644
11,typical_of_concept,0.350274,0.720416,0.367910,0.689440
12,variability_limited,0.116538,0.558878,0.197795,0.599990
13,_check,0.636824,0.886903,0.904637,0.964443
14,test_true,0.072844,0.806485,NaN,NaN
15,typical_of_property,0.272381,0.770111,0.326482,0.682547

## Agreement after removing workers or annotations:

In [13]:
run = '3'
batch = '*'
n_q = '*'
group = 'experiment1'

print('Total Agreement')
data_dict_list = load_experiment_data(run, group, n_q, batch, remove_not_val = True)
get_agreement(data_dict_list)
print('-------')
print()

print('Removing pairs with many contradictions:')
category = 'pairs_contradictions'
print(f'analyze {category}')
annotations_clean, annotations_removed = clean_annotations(run, group, n_q, batch, category)
print('agreement clean')
get_agreement(annotations_clean)
#print('agreement rest')
#get_agreement(annotations_removed)


category = 'worker_contradictions'
print(f'analyze {category}')
annotations_clean, annotations_removed = clean_annotations(run, group, n_q, batch, category)
print('agreement clean')
get_agreement(annotations_clean)
#print('agreement rest')
#get_agreement(annotations_removed)
print()

category = 'worker_checks'
print(f'analyze {category}')
annotations_clean, annotations_removed = clean_annotations(run, group, n_q, batch, category)
print('agreement clean')
get_agreement(annotations_clean)
#print('agreement rest')
#get_agreement(annotations_removed)

Total Agreement
Discarded 655.0 annotations.
Krippendorff's alpha: 0.24831683716387543
Proportional agreement (pairwise): 0.6398473738324435

-------

Removing pairs with many contradictions:
analyze pairs_contradictions
Discarded 655.0 annotations.
Found 18646 clean annotations.
Round 6165 to remove.

agreement clean
Krippendorff's alpha: 0.33987128844423387
Proportional agreement (pairwise): 0.6913370807338856

analyze worker_contradictions
Discarded 655.0 annotations.
Found 14661 clean annotations.
Round 10100 to remove.

agreement clean
Krippendorff's alpha: 0.2849099868357793
Proportional agreement (pairwise): 0.6675007701958354


analyze worker_checks
Discarded 655.0 annotations.
Found 22232 clean annotations.
Round 2529 to remove.

agreement clean
Krippendorff's alpha: 0.2751705306283466
Proportional agreement (pairwise): 0.6533859282261935

{'Krippendorff': 0.2751705306283466, 'Proportional': 0.6533859282261935}