# Annotation analysis

This noteboook

* illustrates the steps of the analysis currently implemented
* is used to analyze and monitor workers batch by batch

In [1]:
from load_data import load_experiment_data
from analyze_workers import get_worker_analysis
from analyze_pairs import get_pair_analysis
from analyze_pairs import show_pairs_of_worker
from analyze_pairs import compare_runs
from calculate_iaa import get_agreement
from clean_annotations import clean_annotations

# Analyze worker contradictions:

* Workers with highest contradiction to annotations ratio appear on top
* use the pandas dataframe sort method to sort on other values: 

`df.sort_values(by, axis=0, ascending=True, inplace=False, kind='quicksort', na_position='last')`

### Current batch

In [16]:
run = 3
batch = 21
n_q = 70
group = 'experiment1'

data_dict_list = load_experiment_data(run, group, n_q, batch, remove_not_val = True)
name = f'run{run}-group_{group}-batch{batch}'.replace('*', '-all-')
df, filepath = get_worker_analysis(data_dict_list, name)
df.drop(['annotations'], axis = 1, inplace=True)
df

Discarded 10.0 annotations.

,workerid,n_annotations,n_contradictions,n_fails,contradiction_annotation_ratio,fail_annotation_ratio,average_time_question,"(implied_category, unusual)","(affording_activity, impossible)","(impossible, typical_of_concept)","(affording_activity, rare)","(rare, typical_of_concept)","(implied_category, impossible)","(implied_category, rare)","(impossible, typical_of_property)","(typical_of_property, unusual)","(rare, typical_of_property)","(typical_of_concept, unusual)","(affording_activity, unusual)"
4,5e4e86b070e1ed2d6e4e3f62,72,42,1,0.583333,0.013889,4.293264,5.0,1.0,1.0,4.0,4.0,2.0,5.0,2.0,5.0,5.0,4.0,4.0
9,5e7cbbbcf0a5a004b60b48f7,72,41,1,0.569444,0.013889,11.482222,1.0,4.0,2.0,6.0,4.0,4.0,5.0,4.0,2.0,6.0,1.0,2.0
5,5e6A4950b3ef740224c41,72,4,0,0.055556,0.000000,0.000000,1.0,NaN,NaN,NaN,1.0,NaN,1.0,NaN,NaN,NaN,1.0,NaN
2,5d5047590ea65a001adcec9f,72,3,0,0.041667,0.000000,24.535694,1.0,1.0,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,5e2310c9e37cd95baf4003a3,72,2,0,0.027778,0.000000,17.731333,NaN,NaN,NaN,1.0,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8,5e7ca153a60b642ec708809f,72,2,0,0.027778,0.000000,7.957028,NaN,NaN,NaN,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0
0,589e989ce6afe00001d349a8,72,0,0,0.000000,0.000000,7.749069,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,5b222aff59f9620001c109cb,72,0,0,0.000000,0.000000,17.075972,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,5e6a65e0f2e93f016351c9fb,72,0,1,0.000000,0.013889,10.233708,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7,5e7104944bccf2000a81dab3,72,0,0,0.000000,0.000000,9.144292,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
10,Redhoolo,3,0,0,0.000000,0.000000,0.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

### All annotations

* Workers with highest contradiction to annotations ratio appear on top
* use the pandas dataframe sort method to sort on other values: 
* Check how the behavior of a specific worker with many contradictions compares to other workers

`df.sort_values(by, axis=0, ascending=True, inplace=False, kind='quicksort', na_position='last')`

In [11]:
run = '*'
batch = '*'
n_q = '*'
group = 'experiment1'

data_dict_list = load_experiment_data(run, group, n_q, batch, remove_not_val = True)
name = f'run{run}-group_{group}-batch{batch}'.replace('*', '-all-')
df, filepath = get_worker_analysis(data_dict_list, name)
df.drop(['annotations'], axis = 1, inplace=True)
df[:10]

Discarded 655.0 annotations.

,workerid,n_annotations,n_contradictions,n_fails,contradiction_annotation_ratio,fail_annotation_ratio,average_time_question,"(afforded_unusual, unusual)","(typical_of_property, unusual)","(implied_category, unusual)",...,"(impossible, typical_of_concept)","(impossible, typical_of_property)","(implied_category, impossible)","(affording_activity, impossible)","(afforded_unusual, impossible)","(afforded_usual, impossible)","(implied_category, rare)","(rare, typical_of_concept)","(rare, typical_of_property)","(affording_activity, rare)"
474,5d76a2dc2a476a0001ce6843,72,45,1,0.625000,0.013889,16.482319,NaN,3.0,5.0,...,3.0,2.0,3.0,2.0,NaN,NaN,5.0,5.0,3.0,5.0
289,5e4e86b070e1ed2d6e4e3f62,72,42,1,0.583333,0.013889,4.293264,NaN,5.0,5.0,...,1.0,2.0,2.0,1.0,NaN,NaN,5.0,4.0,5.0,4.0
294,5e7cbbbcf0a5a004b60b48f7,72,41,1,0.569444,0.013889,11.482222,NaN,2.0,1.0,...,2.0,4.0,4.0,4.0,NaN,NaN,5.0,4.0,6.0,6.0
241,5c91321c0375460001034cb8,71,38,0,0.535211,0.000000,12.942127,2.0,6.0,6.0,...,5.0,5.0,4.0,1.0,1.0,NaN,NaN,NaN,NaN,NaN
468,5e76ab49dec4562243b421f9,72,35,2,0.486111,0.027778,18.781028,NaN,3.0,2.0,...,3.0,1.0,2.0,3.0,NaN,NaN,2.0,4.0,3.0,4.0
15,5dc0395f2a1dd64710661ccd,71,33,0,0.464789,0.000000,3.745113,4.0,5.0,5.0,...,3.0,2.0,3.0,1.0,1.0,1.0,NaN,NaN,NaN,NaN
192,5d4434c68225f9001642fcd3,71,30,0,0.422535,0.000000,5.209535,1.0,4.0,4.0,...,3.0,3.0,3.0,3.0,1.0,NaN,NaN,NaN,NaN,NaN
187,5de8dc07f42a16000a301cd6,78,31,0,0.397436,0.000000,4.965808,2.0,5.0,5.0,...,3.0,3.0,3.0,1.0,1.0,1.0,NaN,NaN,NaN,NaN
71,599aca876b939900012da2cd,71,27,0,0.380282,0.000000,19.589310,1.0,6.0,7.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
16,5ddc56fbf290e7bbfa96481d,71,27,0,0.380282,0.000000,11.515127,5.0,3.0,6.0,...,NaN,NaN,2.0,NaN,2.0,1.0,NaN,NaN,NaN,NaN

### Get all disagreements and fails of a particular worker 

* Check if a specfic worker continuously contradicts themselves (and fails checks)

In [18]:
# copy from above - worker with many disagreements in target batch
worker = '5e7cbbbcf0a5a004b60b48f7'

# df.loc[df['column_name'] == some_value]
df.loc[df['workerid'] == worker]

,workerid,n_annotations,n_contradictions,n_fails,contradiction_annotation_ratio,fail_annotation_ratio,average_time_question,"(implied_category, unusual)","(affording_activity, impossible)","(impossible, typical_of_concept)","(affording_activity, rare)","(rare, typical_of_concept)","(implied_category, impossible)","(implied_category, rare)","(impossible, typical_of_property)","(typical_of_property, unusual)","(rare, typical_of_property)","(typical_of_concept, unusual)","(affording_activity, unusual)"
9,5e7cbbbcf0a5a004b60b48f7,72,41,1,0.569444,0.013889,11.482222,1.0,4.0,2.0,6.0,4.0,4.0,5.0,4.0,2.0,6.0,1.0,2.0

# Analyze pairs

* compars number of annotator contradictions among pairs

### Current batch:

In [5]:
run = '3'
batch = '21'
n_q = '*'
group = 'experiment1'

data_dict_list = load_experiment_data(run, group, n_q, batch, remove_not_val = True)
name = f'run{run}-group_{group}-batch{batch}'.replace('*', '-all-')
df, filepath = get_pair_analysis(data_dict_list, name)
df.drop(['annotations_with_contradiction'], axis = 1, inplace=True)
df

Discarded 10.0 annotations.

,pair,n_annotations,n_workers,n_contradictions,n_workers_contradicting,ratio_workers_contradicting,contradiction_annotation_ratio,average_time_pair,workers_contradicting,workers_not_contradicting,...,"(implied_category, rare)","(impossible, typical_of_property)","(impossible, typical_of_concept)","(affording_activity, impossible)","(typical_of_property, unusual)","(rare, typical_of_property)","(typical_of_concept, unusual)","(rare, typical_of_concept)","(affording_activity, unusual)","(affording_activity, rare)"
0,red-chive,100,10,20,2,0.200000,0.200000,79.34586,5e4e86b070e1ed2d6e4e3f62 5e7cbbbcf0a5a004b60b48f7,589e989ce6afe00001d349a8 5b222aff59f9620001c10...,...,2.0,1.0,1.0,1.0,2.0,2.0,2.0,2.0,2.0,2.0
4,red-lingonberry,100,10,20,3,0.300000,0.200000,79.34586,5e4e86b070e1ed2d6e4e3f62 5e6A4950b3ef740224c41...,589e989ce6afe00001d349a8 5b222aff59f9620001c10...,...,3.0,1.0,1.0,1.0,1.0,2.0,2.0,3.0,1.0,2.0
5,red-geranium,100,10,16,4,0.400000,0.160000,79.34586,5d5047590ea65a001adcec9f 5e2310c9e37cd95baf400...,589e989ce6afe00001d349a8 5b222aff59f9620001c10...,...,2.0,1.0,2.0,2.0,NaN,1.0,NaN,2.0,1.0,3.0
2,round-pineapple,100,10,13,3,0.300000,0.130000,79.34586,5d5047590ea65a001adcec9f 5e4e86b070e1ed2d6e4e3...,589e989ce6afe00001d349a8 5b222aff59f9620001c10...,...,2.0,2.0,NaN,1.0,1.0,2.0,NaN,NaN,NaN,1.0
6,red-chicken,100,10,10,2,0.200000,0.100000,79.34586,5e4e86b070e1ed2d6e4e3f62 5e7cbbbcf0a5a004b60b48f7,589e989ce6afe00001d349a8 5b222aff59f9620001c10...,...,1.0,1.0,NaN,1.0,1.0,1.0,1.0,1.0,1.0,1.0
3,red-cream,101,11,8,3,0.272727,0.079208,72.13260,5e4e86b070e1ed2d6e4e3f62 5e7ca153a60b642ec7088...,589e989ce6afe00001d349a8 5b222aff59f9620001c10...,...,1.0,NaN,NaN,NaN,1.0,2.0,NaN,1.0,1.0,2.0
1,red-pot,102,11,7,2,0.181818,0.068627,72.13260,5e4e86b070e1ed2d6e4e3f62 5e7cbbbcf0a5a004b60b48f7,589e989ce6afe00001d349a8 5b222aff59f9620001c10...,...,NaN,NaN,NaN,NaN,1.0,1.0,1.0,1.0,1.0,1.0
7,_check1-_check1,10,10,0,0,0.000000,0.000000,793.45860,,589e989ce6afe00001d349a8 5b222aff59f9620001c10...,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8,_test1-_test1,10,10,0,0,0.000000,0.000000,793.45860,,589e989ce6afe00001d349a8 5b222aff59f9620001c10...,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

### Get rows with pairs annotated by specific workers:

* Check if a worker in the only one contradicting or if others also had issues with the pairs

In [6]:
worker = '5d206e075278fa001848134d'

show_pairs_of_worker(worker, df)

Worker 5d206e075278fa001848134d contradicted themselves in the following pairs:

red-hair 	 total workers contradicting themselves: 2
round-enchiladas 	 total workers contradicting themselves: 2

### Compare to entire annotation set

In [7]:
run = '*'
batch = '*'
n_q = '*'
group = 'experiment1'

data_dict_list = load_experiment_data(run, group, n_q, batch, remove_not_val = True)
name = f'run{run}-group_{group}-batch{batch}'.replace('*', '-all-')
df, filepath = get_pair_analysis(data_dict_list, name)
df.drop(['annotations_with_contradiction'], axis = 1, inplace=True)
df

,pair,n_annotations,n_workers,n_contradictions,n_workers_contradicting,ratio_workers_contradicting,contradiction_annotation_ratio,average_time_pair,workers_contradicting,workers_not_contradicting,...,"(impossible, typical_of_property)","(affording_activity, unusual)","(implied_category, impossible)","(implied_category, rare)","(rare, typical_of_concept)","(rare, typical_of_property)","(affording_activity, impossible)","(afforded_unusual, impossible)","(afforded_usual, impossible)","(affording_activity, rare)"
26,roll-spindle,50,5,22,4,0.8,0.44,57.711660,5dc0395f2a1dd64710661ccd 5ddc56fbf290e7bbfa964...,5de6be6912bcf6041b3276ba,...,2.0,NaN,2.0,NaN,NaN,NaN,NaN,2.0,2.0,NaN
231,roll-bolt,50,5,21,5,1.0,0.42,85.335380,5acb5910e1546900019c413a 5c5758e9efe1550001dc3...,,...,1.0,NaN,NaN,NaN,NaN,NaN,NaN,1.0,1.0,NaN
23,roll-mandrel,50,5,21,5,1.0,0.42,57.711660,5dc0395f2a1dd64710661ccd 5ddc56fbf290e7bbfa964...,,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25,roll-pipe,50,5,19,4,0.8,0.38,57.711660,5dc0395f2a1dd64710661ccd 5ddc56fbf290e7bbfa964...,5de6d199a23d79000bf9aef9,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,1.0,NaN
227,roll-lamp,50,5,17,4,0.8,0.34,85.335380,5acb5910e1546900019c413a 5d3f14f66a8a4e0018c17...,5c5758e9efe1550001dc31b6,...,2.0,NaN,1.0,NaN,NaN,NaN,NaN,2.0,1.0,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
266,red-ladybird,50,5,0,0,0.0,0.00,85.898220,,5ad90f90dec767000128a5f4 5aeded8f0ccc2e0001858...,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
265,round-football,50,5,0,0,0.0,0.00,85.898220,,5ad90f90dec767000128a5f4 5aeded8f0ccc2e0001858...,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
264,round-vinaigrette,50,5,0,0,0.0,0.00,85.898220,,5ad90f90dec767000128a5f4 5aeded8f0ccc2e0001858...,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
262,round-pilaf,55,6,0,0,0.0,0.00,170.509583,,56a5702281a8ca000d3e573e 5c409b3a5daced00018bf...,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
435,_test1-_test1,39,38,0,0,0.0,0.00,850.945855,,5b222aff59f9620001c109cb 5c62a91524035400014b6...,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

### Compare contradictions between runs:

In [8]:
run = '1'
batch = '*'
n_q = '*'
group = 'experiment1'

data_dict_list = load_experiment_data(run, group, n_q, batch, remove_not_val = True)
name = f'run{run}-group_{group}-batch{batch}'.replace('*', '-all-')
df1, filepath = get_pair_analysis(data_dict_list, name)
print(f'analysis can be found at: {filepath}')

run = '3'
batch = '*'
n_q = '*'
group = 'experiment1'

data_dict_list = load_experiment_data(run, group, n_q, batch, remove_not_val = True)
name = f'run{run}-group_{group}-batch{batch}'.replace('*', '-all-')
df2, filepath = get_pair_analysis(data_dict_list, name)
print(f'analysis can be found at: {filepath}')

name1 = '1'
name2 = '3'
compare_runs(name1, name2, df1, df2, comp = 'all')
print()
compare_runs(name1, name2, df1, df2, comp = 'pairs')

analysis can be found at: ../analyses/pairs/run1-group_experiment1-batch-all-.csv
analysis can be found at: ../analyses/pairs/run3-group_experiment1-batch-all-.csv
Set 1 as a contradiction ratio of 0.26912294753704447
Set 3 as a contradiction ratio of 0.14657079646017698
The ratio is based on the number of workers annotating a pair.
A worker always annotates a full set.

Set 1 as a contradiction ratio of 0.1786064769381747
Set 3 as a contradiction ratio of 0.1633416458852868
The ratio is based on the number of workers annotating a pair.
A worker always annotates a full set.
This analysis only includes pairs annotated in run 1 and run 3.

(0.1786064769381747, 0.1633416458852868)

# Inter-annotator agreement

Compare both runs in original version and version without annotations in which annotators contradict themselves:

In [25]:
run = '3'
batch = '18'
n_q = '*'
group = 'experiment1'
data_dict_list = load_experiment_data(run, group, n_q, batch, remove_not_val = True)

get_agreement(data_dict_list)

run = '3'
batch = '*'
n_q = '*'
group = 'experiment1'
data_dict_list = load_experiment_data(run, group, n_q, batch, remove_not_val = True)

get_agreement(data_dict_list)

Krippendorff's alpha: 0.28407019178507675
Proportional agreement (pairwise): 0.6794444444444443

Krippendorff's alpha: 0.2589417873074862
Proportional agreement (pairwise): 0.6464051771840055

In [9]:
run = '1'
batch = '*'
n_q = '*'
group = 'experiment1'
data_dict_list = load_experiment_data(run, group, n_q, batch, remove_not_val = True)

get_agreement(data_dict_list)

Krippendorff's alpha: 0.2413329996998821
Proportional agreement (pairwise): 0.6204625909422005

In [26]:
run = '3'
batch = '*'
n_q = '*'
group = 'experiment1'

category = 'pairs_contradictions'
print(f'analyze {category}')
annotations_clean, annotations_removed = clean_annotations(run, group, n_q, batch, category)
print('agreement clean')
get_agreement(annotations_clean)
print('agreement rest')
get_agreement(annotations_removed)


category = 'worker_contradictions'
print(f'analyze {category}')
annotations_clean, annotations_removed = clean_annotations(run, group, n_q, batch, category)
print('agreement clean')
get_agreement(annotations_clean)
print('agreement rest')
get_agreement(annotations_removed)


category = 'worker_checks'
print(f'analyze {category}')
annotations_clean, annotations_removed = clean_annotations(run, group, n_q, batch, category)
print('agreement clean')
get_agreement(annotations_clean)
print('agreement rest')
get_agreement(annotations_removed)

analyze pairs_contradictions
Found 12621 clean annotations.
Round 2803 to remove.

agreement clean
Krippendorff's alpha: 0.3364957083397154
Proportional agreement (pairwise): 0.6977050135958119

agreement rest
Krippendorff's alpha: 0.0886018669447709
Proportional agreement (pairwise): 0.390954945712575

analyze worker_contradictions
Found 5859 clean annotations.
Round 9471 to remove.

agreement clean
Krippendorff's alpha: 0.36180046848905834
Proportional agreement (pairwise): 0.6848353199259613

agreement rest
Krippendorff's alpha: 0.2235513526339752
Proportional agreement (pairwise): 0.616096839012484

analyze worker_checks
Found 13063 clean annotations.
Round 2267 to remove.

agreement clean
Krippendorff's alpha: 0.30160533360370045
Proportional agreement (pairwise): 0.666028083040578

agreement rest
Krippendorff's alpha: 0.13162011955912623
Proportional agreement (pairwise): 0.46383219408477677