# Annotation analysis

This noteboook

* illustrates the steps of the analysis currently implemented
* is used to analyze and monitor workers batch by batch

In [1]:
from load_data import load_experiment_data
from analyze_workers import get_worker_analysis
from analyze_pairs import get_pair_analysis
from analyze_pairs import show_pairs_of_worker
from analyze_pairs import compare_runs
from calculate_iaa import get_agreement
from clean_annotations import clean_annotations
from analyze_relations_and_examples import agreement_relations_across_runs

# Analyze worker contradictions:

* Workers with highest contradiction to annotations ratio appear on top
* use the pandas dataframe sort method to sort on other values: 

`df.sort_values(by, axis=0, ascending=True, inplace=False, kind='quicksort', na_position='last')`

### Current batch

In [37]:
run = 4
batch = 6
n_q = '*'
group = 'experiment2'

data_dict_list = load_experiment_data(run, group, n_q, batch, remove_not_val = True)
name = f'run{run}-group_{group}-batch{batch}'.replace('*', '-all-')
df, filepath = get_worker_analysis(data_dict_list, name)
df.drop(['annotations'], axis = 1, inplace=True)
df

creating file with uuid run4-group_experiment2/qu70-s_qu70-batch6.csv
added unique ids - file can be found at: ../data/prolific_output_uuid/run4-group_experiment2/qu70-s_qu70-batch6.csv
Discarded 0.0 annotations.

,workerid,n_annotations,n_contradictions,n_fails,contradiction_annotation_ratio,n_possible_contradictions,contradiction_poss_contradiction_ratio,fail_annotation_ratio,contradictory_pairs_ratio,average_time_question,...,"(afforded_unusual, impossible)","(afforded_unusual, unusual)","(implied_category, rare)","(rare, typical_of_concept)","(rare, typical_of_property)","(affording_activity, impossible)","(impossible, typical_of_concept)","(afforded_usual, impossible)","(implied_category, impossible)","(impossible, typical_of_property)"
9,5ea0cab850c77d0d40fa0768,72,21,2,0.291667,87,0.241379,0.027778,0.777778,5.428792,...,1.0,NaN,1.0,1.0,NaN,3.0,4.0,1.0,3.0,1.0
3,5be0b3d439bd3f000110d652,72,14,1,0.194444,87,0.160920,0.013889,0.333333,5.673389,...,1.0,1.0,2.0,1.0,1.0,NaN,NaN,NaN,NaN,NaN
4,5c3f73995353e90001e40d16,72,5,0,0.069444,87,0.057471,0.000000,0.222222,8.688653,...,NaN,NaN,NaN,NaN,NaN,1.0,NaN,NaN,NaN,NaN
1,59d71813e2762800015eb5d8,72,4,0,0.055556,87,0.045977,0.000000,0.111111,11.588833,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7,5ea07ee6ddea230581c2e93b,72,4,0,0.055556,87,0.045977,0.000000,0.111111,10.344486,...,NaN,NaN,NaN,1.0,NaN,NaN,NaN,NaN,NaN,NaN
8,5ea0b664c2b7320a4aef95af,72,4,0,0.055556,87,0.045977,0.000000,0.111111,6.671319,...,NaN,NaN,1.0,1.0,1.0,NaN,NaN,NaN,NaN,NaN
0,58bfb1f692a88e0001658253,72,2,0,0.027778,87,0.022989,0.000000,0.111111,13.211792,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,5bae3351a91ee200011a4220,72,0,0,0.000000,87,0.000000,0.000000,0.000000,9.695250,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,5d6aeb25a6a4220015010bd6,72,0,0,0.000000,87,0.000000,0.000000,0.000000,24.647153,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,5e1b28d4d370f435a62cfbe2,72,0,0,0.000000,87,0.000000,0.000000,0.000000,10.154597,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

### All annotations

* Workers with highest contradiction to annotations ratio appear on top
* use the pandas dataframe sort method to sort on other values: 
* Check how the behavior of a specific worker with many contradictions compares to other workers

`df.sort_values(by, axis=0, ascending=True, inplace=False, kind='quicksort', na_position='last')`

In [39]:
run = '*'
batch = '*'
n_q = '*'
group = 'experiment*'

data_dict_list = load_experiment_data(run, group, n_q, batch, remove_not_val = True)
name = f'run{run}-group_{group}-batch{batch}'.replace('*', '-all-')
df_total, filepath = get_worker_analysis(data_dict_list, name)
df_total.drop(['annotations'], axis = 1, inplace=True)
df_total[:20]

Discarded 655.0 annotations.

,workerid,n_annotations,n_contradictions,n_fails,contradiction_annotation_ratio,n_possible_contradictions,contradiction_poss_contradiction_ratio,fail_annotation_ratio,contradictory_pairs_ratio,average_time_question,...,"(rare, typical_of_concept)","(rare, typical_of_property)","(affording_activity, impossible)","(impossible, typical_of_concept)","(afforded_usual, impossible)","(implied_category, impossible)","(impossible, typical_of_property)","(afforded_unusual, rare)","(afforded_usual, rare)","(afforded_usual, unusual)"
356,5bfed16ca1f050000102693c,74,62,1,0.837838,87,0.712644,0.013514,0.600000,14.382986,...,4.0,4.0,NaN,5.0,5.0,4.0,5.0,3.0,4.0,4.0
604,5d6ef000391fb4001a97337d,138,69,1,0.500000,99,0.696970,0.007246,0.777778,4.301442,...,4.0,5.0,2.0,3.0,2.0,6.0,4.0,3.0,3.0,3.0
874,111,48,39,0,0.812500,60,0.650000,0.000000,0.571429,0.000000,...,1.0,2.0,NaN,3.0,3.0,2.0,4.0,2.0,1.0,3.0
299,5c91321c0375460001034cb8,71,38,0,0.535211,60,0.633333,0.000000,0.875000,12.942127,...,NaN,NaN,1.0,5.0,NaN,4.0,5.0,NaN,NaN,1.0
832,5d76a2dc2a476a0001ce6843,72,45,1,0.625000,72,0.625000,0.013889,0.600000,16.482319,...,5.0,3.0,2.0,3.0,NaN,3.0,2.0,NaN,NaN,NaN
362,5e2f554c4c58fa515ad361d0,17,3,0,0.176471,5,0.600000,0.000000,0.285714,24.201118,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
493,5e87276d17cdf1028850af59,72,54,1,0.750000,102,0.529412,0.013889,0.777778,2.828292,...,2.0,3.0,NaN,3.0,2.0,5.0,3.0,3.0,3.0,3.0
251,5d4434c68225f9001642fcd3,71,30,0,0.422535,58,0.517241,0.000000,0.875000,5.209535,...,NaN,NaN,3.0,3.0,NaN,3.0,3.0,NaN,NaN,NaN
572,5c042ba4bb85e60001c05c83,72,47,0,0.652778,93,0.505376,0.000000,0.777778,7.812292,...,4.0,3.0,1.0,1.0,2.0,3.0,2.0,2.0,2.0,1.0
74,5dc0395f2a1dd64710661ccd,71,33,0,0.464789,66,0.500000,0.000000,0.875000,3.745113,...,NaN,NaN,1.0,3.0,1.0,3.0,2.0,NaN,NaN,1.0
599,5dac6532ccaa330016e11e8f,51,15,1,0.294118,30,0.500000,0.019608,0.625000,0.000000,...,3.0,2.0,1.0,1.0,NaN,NaN,1.0,NaN,NaN,NaN
546,5ca0ab3d073bc1001209fd58,64,33,1,0.515625,66,0.500000,0.015625,0.555556,3.446672,...,2.0,1.0,2.0,3.0,1.0,3.0,3.0,1.0,1.0,1.0
246,5de8dc07f42a16000a301cd6,78,31,0,0.397436,62,0.500000,0.000000,0.555556,4.965808,...,NaN,NaN,1.0,3.0,1.0,3.0,3.0,NaN,NaN,1.0
460,5e4e86b070e1ed2d6e4e3f62,72,42,1,0.583333,84,0.500000,0.013889,0.777778,4.293264,...,4.0,5.0,1.0,1.0,NaN,2.0,2.0,NaN,NaN,NaN
465,5e7cbbbcf0a5a004b60b48f7,72,41,1,0.569444,84,0.488095,0.013889,0.777778,11.482222,...,4.0,6.0,4.0,2.0,NaN,4.0,4.0,NaN,NaN,NaN
209,banking,75,26,0,0.346667,54,0.481481,0.000000,0.555556,0.000000,...,NaN,NaN,NaN,4.0,3.0,2.0,4.0,NaN,NaN,1.0
130,599aca876b939900012da2cd,71,27,0,0.380282,58,0.465517,0.000000,0.875000,19.589310,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0
445,IT Manager,72,44,2,0.611111,96,0.458333,0.027778,0.777778,0.000000,...,1.0,3.0,1.0,1.0,2.0,3.0,1.0,4.0,3.0,3.0
169,5cd94cb10196990019dbcb09,78,25,0,0.320513,56,0.446429,0.000000,0.777778,5.271885,...,NaN,NaN,NaN,1.0,NaN,2.0,1.0,NaN,NaN,NaN
421,5e85d88e1d6de805083b051f,78,35,0,0.448718,81,0.432099,0.000000,0.545455,21.625103,...,1.0,1.0,NaN,NaN,1.0,1.0,NaN,3.0,2.0,2.0

In [41]:
# Good workers
df_total[-20:]

,workerid,n_annotations,n_contradictions,n_fails,contradiction_annotation_ratio,n_possible_contradictions,contradiction_poss_contradiction_ratio,fail_annotation_ratio,contradictory_pairs_ratio,average_time_question,...,"(rare, typical_of_concept)","(rare, typical_of_property)","(affording_activity, impossible)","(impossible, typical_of_concept)","(afforded_usual, impossible)","(implied_category, impossible)","(impossible, typical_of_property)","(afforded_unusual, rare)","(afforded_usual, rare)","(afforded_usual, unusual)"
71,5d430e89be616d0015f784e8,71,0,0,0.0,58,0.0,0.000000,0.0,8.678676,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
741,5dee62c0770a434f62147de2,76,0,0,0.0,84,0.0,0.000000,0.0,8.971500,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
147,5c036f34efea06000188cdba,8,0,0,0.0,0,0.0,0.000000,0.0,10.544000,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
743,5c62a91524035400014b69dc,78,0,0,0.0,84,0.0,0.000000,0.0,6.654244,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
148,5c3de869b3369c0001a9264a,8,0,0,0.0,0,0.0,0.000000,0.0,22.931875,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
745,5cb62e72ebe8a50001a9b7c8,78,0,1,0.0,84,0.0,0.012821,0.0,5.071128,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
149,5c8250c026a0940016b265da,8,0,0,0.0,0,0.0,0.000000,0.0,83.982125,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
747,5dd7abaaaf16d3746667182c,78,0,0,0.0,84,0.0,0.000000,0.0,9.759564,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
67,5ceac282ca3e100016373e3c,71,0,0,0.0,66,0.0,0.000000,0.0,10.510493,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
64,5a22e6aabf56cc00017701ef,71,0,0,0.0,66,0.0,0.000000,0.0,5.570915,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
150,5de93ba177443804fea65939,8,0,0,0.0,0,0.0,0.000000,0.0,10.269000,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
751,597fa2d8fc90e000011c586d,68,0,0,0.0,72,0.0,0.000000,0.0,8.560044,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
752,5b2838e8b1cd750001498ba9,68,0,0,0.0,72,0.0,0.000000,0.0,6.909279,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
153,5a0feb37df3fa800015c432a,78,0,0,0.0,56,0.0,0.000000,0.0,10.343346,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
754,5dd6ccc58cf2f966166c0399,68,0,0,0.0,72,0.0,0.000000,0.0,5.710118,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
65,5c41f300b96aae0001e75848,71,0,0,0.0,66,0.0,0.000000,0.0,16.126155,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
161,5dad7f29033d57001357a2b8,71,0,0,0.0,52,0.0,0.000000,0.0,11.930225,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
164,5c5b333a2b7de10001b78759,78,0,0,0.0,60,0.0,0.000000,0.0,11.800962,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
758,5e6c075b1689b01da3b62993,68,0,0,0.0,72,0.0,0.000000,0.0,9.027721,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
340,5cd574ebf1dc7600185cc0a4,71,0,0,0.0,60,0.0,0.000000,0.0,16.699577,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

### Get all contradictions and fails of a particular worker 

* Check if a specfic worker continuously contradicts themselves (and fails checks)

In [43]:
# copy from above - worker with many disagreements in target batch
worker = '5ea0cab850c77d0d40fa0768'


# df.loc[df['column_name'] == some_value]
df_total.loc[df_total['workerid'] == worker]

,workerid,n_annotations,n_contradictions,n_fails,contradiction_annotation_ratio,n_possible_contradictions,contradiction_poss_contradiction_ratio,fail_annotation_ratio,contradictory_pairs_ratio,average_time_question,...,"(rare, typical_of_concept)","(rare, typical_of_property)","(affording_activity, impossible)","(impossible, typical_of_concept)","(afforded_usual, impossible)","(implied_category, impossible)","(impossible, typical_of_property)","(afforded_unusual, rare)","(afforded_usual, rare)","(afforded_usual, unusual)"
9,5ea0cab850c77d0d40fa0768,72,21,2,0.291667,87,0.241379,0.027778,0.777778,5.428792,...,1.0,NaN,3.0,4.0,1.0,3.0,1.0,NaN,NaN,NaN

# Analyze pairs

* compars number of annotator contradictions among pairs

### Current batch:

In [45]:
run = '4'
batch = '6'
n_q = '*'
group = 'experiment2'

data_dict_list = load_experiment_data(run, group, n_q, batch, remove_not_val = True)
name = f'run{run}-group_{group}-batch{batch}'.replace('*', '-all-')
df, filepath = get_pair_analysis(data_dict_list, name)
df.drop(['annotations_with_contradiction'], axis = 1, inplace=True)
df

Discarded 0.0 annotations.

,pair,n_annotations,n_workers,n_contradictions,n_workers_contradicting,ratio_workers_contradicting,contradiction_annotation_ratio,n_possible_contradictions,contradiction_poss_contradiction_ratio,average_time_pair,...,"(afforded_unusual, unusual)","(typical_of_concept, unusual)","(implied_category, unusual)","(afforded_usual, impossible)","(typical_of_property, unusual)","(implied_category, rare)","(implied_category, impossible)","(rare, typical_of_concept)","(rare, typical_of_property)","(impossible, typical_of_property)"
5,sweet-sultana,100,10,16,4,0.4,0.16,120,0.133333,76.39507,...,NaN,1.0,2.0,NaN,1.0,2.0,NaN,2.0,2.0,NaN
2,fly-phalacrocorax,100,10,7,3,0.3,0.07,150,0.046667,76.39507,...,1.0,1.0,1.0,1.0,NaN,NaN,NaN,NaN,NaN,NaN
3,dangerous-reduviidae,100,10,10,3,0.3,0.10,120,0.083333,76.39507,...,NaN,1.0,2.0,NaN,1.0,1.0,1.0,NaN,NaN,NaN
0,made_of_wood-axe,100,10,5,2,0.2,0.05,120,0.041667,76.39507,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,hot-kerosene,100,10,7,2,0.2,0.07,120,0.058333,76.39507,...,NaN,1.0,NaN,NaN,NaN,NaN,1.0,1.0,NaN,1.0
1,black-mentzelia,100,10,3,1,0.1,0.03,120,0.025000,76.39507,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,square-cds,100,10,6,1,0.1,0.06,120,0.050000,76.39507,...,NaN,1.0,1.0,NaN,NaN,1.0,1.0,1.0,NaN,NaN
7,_check4-_check4,10,10,0,0,0.0,0.00,0,0.000000,763.95070,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8,_test1-_test1,10,10,0,0,0.0,0.00,0,0.000000,763.95070,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

### Get rows with pairs annotated by specific workers:

* Check if a worker in the only one contradicting or if others also had issues with the pairs

In [46]:
worker = '5ea0cab850c77d0d40fa0768'

show_pairs_of_worker(worker, df)

Worker 5ea0cab850c77d0d40fa0768 contradicted themselves in the following pairs:

sweet-sultana 	 total workers contradicting themselves: 4
fly-phalacrocorax 	 total workers contradicting themselves: 3
dangerous-reduviidae 	 total workers contradicting themselves: 3
made_of_wood-axe 	 total workers contradicting themselves: 2
hot-kerosene 	 total workers contradicting themselves: 2
black-mentzelia 	 total workers contradicting themselves: 1
square-cds 	 total workers contradicting themselves: 1

### Compare to entire annotation set

In [6]:
run = '4'
batch = '*'
n_q = '*'
group = 'experiment2'

data_dict_list = load_experiment_data(run, group, n_q, batch, remove_not_val = True)
name = f'run{run}-group_{group}-batch{batch}'.replace('*', '-all-')
df, filepath = get_pair_analysis(data_dict_list, name)
df.drop(['annotations_with_contradiction'], axis = 1, inplace=True)
df

Discarded 0.0 annotations.

,pair,n_annotations,n_workers,n_contradictions,n_workers_contradicting,ratio_workers_contradicting,contradiction_annotation_ratio,n_possible_contradictions,contradiction_poss_contradiction_ratio,average_time_pair,...,"(rare, typical_of_property)","(affording_activity, impossible)","(affording_activity, unusual)","(typical_of_property, unusual)","(impossible, typical_of_concept)","(impossible, typical_of_property)","(afforded_usual, unusual)","(typical_of_concept, unusual)","(afforded_usual, rare)","(afforded_usual, impossible)"
28,sweet-hazelnut,101,10,11,4,0.4,0.108911,120,0.091667,124.733665,...,NaN,1.0,1.0,NaN,1.0,NaN,NaN,1.0,NaN,NaN
6,lay_eggs-whiteface,100,10,9,4,0.4,0.090000,150,0.060000,91.739940,...,NaN,NaN,NaN,NaN,1.0,1.0,1.0,NaN,NaN,NaN
15,wheels-stage,100,10,15,4,0.4,0.150000,120,0.125000,83.539730,...,1.0,NaN,3.0,1.0,NaN,NaN,NaN,1.0,NaN,NaN
20,made_of_wood-ladder,100,10,13,4,0.4,0.130000,120,0.108333,109.697710,...,1.0,NaN,1.0,2.0,NaN,NaN,NaN,1.0,NaN,NaN
34,black-pipefish,102,10,14,4,0.4,0.137255,120,0.116667,123.943395,...,2.0,NaN,1.0,2.0,NaN,NaN,NaN,1.0,NaN,NaN
32,lay_eggs-eland,101,10,9,3,0.3,0.089109,150,0.060000,124.733665,...,2.0,NaN,NaN,1.0,NaN,NaN,NaN,NaN,1.0,NaN
30,made_of_wood-timber,101,10,10,3,0.3,0.099010,120,0.083333,124.733665,...,1.0,NaN,1.0,1.0,NaN,NaN,NaN,1.0,NaN,NaN
3,dangerous-doodlebug,100,10,8,3,0.3,0.080000,120,0.066667,91.739940,...,1.0,NaN,1.0,1.0,NaN,NaN,NaN,NaN,NaN,NaN
19,wheels-carrier,100,10,11,3,0.3,0.110000,120,0.091667,109.697710,...,1.0,NaN,1.0,1.0,NaN,NaN,NaN,2.0,NaN,NaN
22,lay_eggs-pointer,100,10,16,3,0.3,0.160000,150,0.106667,109.697710,...,NaN,NaN,NaN,NaN,NaN,NaN,2.0,1.0,1.0,1.0
21,hot-barbecue,100,10,15,3,0.3,0.150000,120,0.125000,109.697710,...,NaN,3.0,1.0,1.0,2.0,3.0,NaN,1.0,NaN,NaN
14,wheels-rig,100,10,5,3,0.3,0.050000,120,0.041667,83.539730,...,NaN,1.0,3.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
35,fly-nuthatch,100,10,12,3,0.3,0.120000,150,0.080000,125.681990,...,NaN,NaN,NaN,1.0,1.0,1.0,2.0,1.0,1.0,3.0
29,hot-candy,100,10,8,2,0.2,0.080000,120,0.066667,125.681990,...,NaN,1.0,2.0,NaN,1.0,NaN,NaN,1.0,NaN,NaN
25,dangerous-raper,100,10,7,2,0.2,0.070000,120,0.058333,109.697710,...,2.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
24,sweet-shiitake,100,10,8,2,0.2,0.080000,120,0.066667,109.697710,...,1.0,1.0,1.0,1.0,NaN,1.0,NaN,NaN,NaN,NaN
23,fly-haddock,100,10,9,2,0.2,0.090000,150,0.060000,109.697710,...,1.0,NaN,NaN,NaN,NaN,NaN,1.0,NaN,1.0,1.0
0,fly-wheeler,100,10,7,2,0.2,0.070000,150,0.046667,91.739940,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
13,dangerous-opener,100,10,5,2,0.2,0.050000,120,0.041667,83.539730,...,NaN,NaN,1.0,1.0,NaN,NaN,NaN,1.0,NaN,NaN
12,dangerous-plane,100,10,8,2,0.2,0.080000,120,0.066667,83.539730,...,NaN,1.0,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
11,wheels-railcar,100,10,7,2,0.2,0.070000,120,0.058333,83.539730,...,NaN,1.0,1.0,NaN,1.0,NaN,NaN,1.0,NaN,NaN
10,dangerous-unction,100,10,10,2,0.2,0.100000,120,0.083333,83.539730,...,NaN,1.0,NaN,NaN,2.0,NaN,NaN,1.0,NaN,NaN
2,wheels-snowmobile,100,10,5,2,0.2,0.050000,120,0.041667,91.739940,...,NaN,1.0,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,black-pelican,100,10,4,2,0.2,0.040000,120,0.033333,91.739940,...,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,sweet-jam,100,10,4,1,0.1,0.040000,120,0.033333,91.739940,...,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
16,dangerous-bar,100,10,2,1,0.1,0.020000,120,0.016667,83.539730,...,NaN,NaN,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7,made_of_wood-rod,100,10,3,1,0.1,0.030000,120,0.025000,91.739940,...,1.0,NaN,NaN,1.0,NaN,1.0,NaN,NaN,NaN,NaN
5,yellow-flame,40,10,0,0,0.0,0.000000,0,0.000000,229.349850,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
33,yellow-vanilla,40,10,0,0,0.0,0.000000,0,0.000000,314.204975,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
31,wheels-carriage,60,10,0,0,0.0,0.000000,0,0.000000,209.469983,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
27,_test4-_test,20,20,0,0,0.0,0.000000,0,0.000000,1176.898500,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8,_check1-_check1,10,10,0,0,0.0,0.000000,0,0.000000,917.399400,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
17,_check3-_check3,20,19,0,0,0.0,0.000000,0,0.000000,1066.441237,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
26,_check2-_check2,10,10,0,0,0.0,0.000000,0,0.000000,1096.977100,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9,_test2-_test2,10,10,0,0,0.0,0.000000,0,0.000000,917.399400,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
18,_test3-_test,10,10,0,0,0.0,0.000000,0,0.000000,835.397300,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [10]:
# check specific pair:

pair = 'red-lipstick'
df.loc[df['pair'] == pair]

,pair,n_annotations,n_workers,n_contradictions,n_workers_contradicting,ratio_workers_contradicting,contradiction_annotation_ratio,average_time_pair,workers_contradicting,workers_not_contradicting,...,"(affording_activity, unusual)","(rare, typical_of_concept)","(rare, typical_of_property)","(implied_category, rare)","(implied_category, impossible)","(affording_activity, impossible)","(afforded_unusual, impossible)","(afforded_usual, rare)","(afforded_unusual, rare)","(afforded_usual, impossible)"
305,red-lipstick,50,5,7,2,0.4,0.14,59.799,57617fdb1a5ecc0006fc3860 5ddc0d87d3ac2ad102aff2b9,59dc2e2016ecc200016fea95 5c544985be9cd80001156...,...,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

### Compare contradictions between runs:

In [47]:
run = '3'
batch = '*'
n_q = '*'
group = 'experiment1'

data_dict_list = load_experiment_data(run, group, n_q, batch, remove_not_val = True)
name = f'run{run}-group_{group}-batch{batch}'.replace('*', '-all-')
df1, filepath = get_pair_analysis(data_dict_list, name)
print(f'analysis can be found at: {filepath}')

run = '4'
batch = '*'
n_q = '*'
group = 'experiment2'

data_dict_list = load_experiment_data(run, group, n_q, batch, remove_not_val = True)
name = f'run{run}-group_{group}-batch{batch}'.replace('*', '-all-')
df2, filepath = get_pair_analysis(data_dict_list, name)
print(f'analysis can be found at: {filepath}')

name1 = '3'
name2 = '4'
compare_runs(name1, name2, df1, df2, comp = 'all')
#print()
#compare_runs(name1, name2, df1, df2, comp = 'pairs')

Discarded 655.0 annotations.
analysis can be found at: ../analyses/pairs/run3-group_experiment1-batch-all-.csv
Discarded 0.0 annotations.
analysis can be found at: ../analyses/pairs/run4-group_experiment2-batch-all-.csv
Set 3 as a contradiction ratio of 0.2528971962616822
Set 4 as a contradiction ratio of 0.17926186291739896
The ratio is based on the number of workers annotating a pair.
A worker always annotates a full set.

(0.2528971962616822, 0.17926186291739896)

# Inter-annotator agreement

* Total agreement
* Agreement by relations
* agreement after removing annotators with many contradictions/annotators who fail checks/contradictory annotations

## Total iaa:

In [48]:
run = '*'
batch = '*'
n_q = '*'
group = 'experiment1'
print(f"Run {run}:")
data_dict_list = load_experiment_data(run, group, n_q, batch, remove_not_val = True)
get_agreement(data_dict_list)

run = '4'
batch = '*'
n_q = '*'
group = 'experiment2'
print(f"Run {run}:")
data_dict_list = load_experiment_data(run, group, n_q, batch, remove_not_val = True)

get_agreement(data_dict_list)

Run *:
Discarded 655.0 annotations.
Krippendorff's alpha: 0.23567624334318582
Proportional agreement (pairwise): 0.6233819990832739

Run 4:
Discarded 0.0 annotations.
Krippendorff's alpha: 0.23892481653734177
Proportional agreement (pairwise): 0.6412293299870081

{'Krippendorff': 0.23892481653734177, 'Proportional': 0.6412293299870081}

## IAA of collapsed relations

In [9]:
run = '*'
batch = '*'
n_q = '*'
group = 'experiment1'
print(f"Run {run}:")
data_dict_list = load_experiment_data(run, group, n_q, batch, remove_not_val = True)
get_agreement(data_dict_list)

collapse_relations = 'pos_neg'
print(f'collapsing {collapse_relations}')
get_agreement(data_dict_list, collapse_relations = collapse_relations)

collapse_relations = 'levels'
print(f'collapsing {collapse_relations}')
get_agreement(data_dict_list, collapse_relations = collapse_relations)

collapse_relations = 'similar_relations'
print(f'collapsing {collapse_relations}')
get_agreement(data_dict_list, collapse_relations = collapse_relations)


run = '4'
batch = '*'
n_q = '*'
group = 'experiment2'
print(f"Run {run}:")
data_dict_list = load_experiment_data(run, group, n_q, batch, remove_not_val = True)
get_agreement(data_dict_list)

collapse_relations = 'pos_neg'
print(f'collapsing {collapse_relations}')
get_agreement(data_dict_list, collapse_relations = collapse_relations)

collapse_relations = 'levels'
print(f'collapsing {collapse_relations}')
get_agreement(data_dict_list, collapse_relations = collapse_relations)

collapse_relations = 'similar_relations'
print(f'collapsing {collapse_relations}')
get_agreement(data_dict_list, collapse_relations = collapse_relations)

Run *:
Discarded 655.0 annotations.
Krippendorff's alpha: 0.23567624334318582
Proportional agreement (pairwise): 0.6233819990832739

collapsing pos_neg
pos_neg
Krippendorff's alpha: 0.3348903198600117
Proportional agreement (pairwise): 0.7902502664705034

collapsing levels
levels
Krippendorff's alpha: 0.3555916355102202
Proportional agreement (pairwise): 0.7038679436637708

collapsing similar_relations
similar_relations
Krippendorff's alpha: 0.37526324080891615
Proportional agreement (pairwise): 0.6967938704580102

Run 4:
Discarded 0.0 annotations.
Krippendorff's alpha: 0.24217199868349115
Proportional agreement (pairwise): 0.6459022163559383

collapsing pos_neg
pos_neg
Krippendorff's alpha: 0.3443147721286992
Proportional agreement (pairwise): 0.7284790176338635

collapsing levels
levels
Krippendorff's alpha: 0.3749315715926481
Proportional agreement (pairwise): 0.6915466169308861

collapsing similar_relations
similar_relations
Krippendorff's alpha: 0.3732721346790516
Proportional agreement (pairwise): 0.7266231889199777

{'Krippendorff': 0.3732721346790516, 'Proportional': 0.7266231889199777}

## IAA by relation

In [12]:
runs = ['3', '1']
experiment_name = 'experiment1'
path, df = agreement_relations_across_runs(runs, experiment_name)
print(f'Results written to: {path}')
df

Discarded 655.0 annotations.
Discarded 0.0 annotations.
Results written to: ../analyses/iaa/relations_runs3-1.csv

,relation,3_Krippendorff,3_Proportional,1_Krippendorff,1_Proportional
0,implied_category,0.261604,0.648495,0.260459,0.629956
1,affording_activity,0.196837,0.654605,0.149149,0.672259
2,variability_subcategories,NaN,NaN,0.157270,0.579637
3,impossible,0.134907,0.658426,0.183925,0.679565
4,variability_limited,0.103003,0.551718,0.197795,0.599990
5,afforded_usual,0.172981,0.644417,0.336767,0.698580
6,typical_of_property,0.231757,0.755240,0.326482,0.682547
7,creative,0.059688,0.544502,0.040020,0.524894
8,rare,0.132488,0.576444,NaN,NaN
9,typical_of_concept,0.311785,0.712881,0.367910,0.689440
10,afforded_unusual,0.068180,0.544889,0.108460,0.557623
11,test_true,0.045786,0.794077,NaN,NaN
12,_check,0.606292,0.884235,0.904637,0.964443
13,test_false,0.258187,0.702768,NaN,NaN
14,unusual,0.159998,0.576699,0.120147,0.561644
15,variability_open,0.214621,0.606366,0.143751,0.580081

## Agreement after removing workers or annotations:

In [32]:
run = '3'
batch = '*'
n_q = '*'
group = 'experiment1'

print('Total Agreement')
data_dict_list = load_experiment_data(run, group, n_q, batch, remove_not_val = True)
get_agreement(data_dict_list)
print('-------')
print()

print('Removing pair annotations with many contradictions:')
category = 'pairs_contradictions'
print(f'analyze {category}')
annotations_clean, annotations_removed = clean_annotations(run, group, n_q, batch, category)
print('agreement clean')
get_agreement(annotations_clean)
#print('agreement rest')
#get_agreement(annotations_removed)


category = 'worker_contradictions'
print(f'analyze {category}')
annotations_clean, annotations_removed = clean_annotations(run, group, n_q, batch, category)
print('agreement clean')
get_agreement(annotations_clean)
#print('agreement rest')
#get_agreement(annotations_removed)
print()

category = 'worker_checks'
print(f'analyze {category}')
annotations_clean, annotations_removed = clean_annotations(run, group, n_q, batch, category)
print('agreement clean')
get_agreement(annotations_clean)
#print('agreement rest')
#get_agreement(annotations_removed)

Total Agreement
Discarded 655.0 annotations.
Krippendorff's alpha: 0.23336207839907597
Proportional agreement (pairwise): 0.6304754199128316

-------

Removing pair annotations with many contradictions:
analyze pairs_contradictions
Discarded 655.0 annotations.
Found 24827 clean annotations.
Round 10212 to remove.

agreement clean
Krippendorff's alpha: 0.33405102479157067
Proportional agreement (pairwise): 0.68651450192071

analyze worker_contradictions
Discarded 655.0 annotations.
Found 24877 clean annotations.
Round 10100 to remove.

agreement clean
Krippendorff's alpha: 0.24953378047207264
Proportional agreement (pairwise): 0.6498735089301452


analyze worker_checks
Discarded 655.0 annotations.
Found 32448 clean annotations.
Round 2529 to remove.

agreement clean
Krippendorff's alpha: 0.25028983009201133
Proportional agreement (pairwise): 0.639896601266422

{'Krippendorff': 0.25028983009201133, 'Proportional': 0.639896601266422}