# Annotation analysis

This noteboook

* illustrates the steps of the analysis currently implemented
* is used to analyze and monitor workers batch by batch

In [1]:
from load_data import load_experiment_data
from analyze_workers import get_worker_analysis
from analyze_pairs import get_pair_analysis
from analyze_pairs import show_pairs_of_worker
from analyze_pairs import compare_runs
from calculate_iaa import get_agreement
from clean_annotations import clean_annotations
from analyze_relations_and_examples import agreement_relations_across_runs

# Analyze worker contradictions:

* Workers with highest contradiction to annotations ratio appear on top
* use the pandas dataframe sort method to sort on other values: 

`df.sort_values(by, axis=0, ascending=True, inplace=False, kind='quicksort', na_position='last')`

### Current batch

In [25]:
run = 4
batch = 2
n_q = '*'
group = 'experiment2'

data_dict_list = load_experiment_data(run, group, n_q, batch, remove_not_val = True)
name = f'run{run}-group_{group}-batch{batch}'.replace('*', '-all-')
df, filepath = get_worker_analysis(data_dict_list, name)
df.drop(['annotations'], axis = 1, inplace=True)
df

Discarded 0.0 annotations.

,workerid,n_annotations,n_contradictions,n_fails,contradiction_annotation_ratio,n_possible_contradictions,contradiction_poss_contradiction_ratio,fail_annotation_ratio,contradictory_pairs_ratio,average_time_question,...,"(afforded_usual, rare)","(afforded_usual, unusual)","(rare, typical_of_concept)","(typical_of_concept, unusual)","(typical_of_property, unusual)","(rare, typical_of_property)","(impossible, typical_of_concept)","(affording_activity, impossible)","(impossible, typical_of_property)","(implied_category, impossible)"
7,5e7d04851ae8680b7c88e7e4,72,24,1,0.333333,72,0.333333,0.013889,0.4,13.606750,...,1.0,1.0,3.0,3.0,2.0,2.0,1.0,NaN,1.0,1.0
2,5d977727646bb70012d6ea5b,72,14,1,0.194444,72,0.194444,0.013889,0.5,7.412889,...,NaN,NaN,1.0,1.0,2.0,1.0,NaN,NaN,NaN,NaN
5,5e66c749fd0e5b454700f10f,72,11,1,0.152778,72,0.152778,0.013889,0.3,10.719486,...,NaN,NaN,3.0,1.0,NaN,1.0,1.0,1.0,NaN,NaN
0,58ac3822890ea500014c665d,72,7,1,0.097222,72,0.097222,0.013889,0.2,24.351819,...,1.0,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,5e1aed4331d8d93320bc6d4e,77,3,1,0.038961,72,0.041667,0.012987,0.2,13.547494,...,NaN,NaN,NaN,NaN,NaN,NaN,1.0,1.0,NaN,NaN
3,5e196bcd49c6aa210ea6aaad,72,2,1,0.027778,72,0.027778,0.013889,0.1,12.213319,...,NaN,NaN,NaN,NaN,1.0,1.0,NaN,NaN,NaN,NaN
9,5e9cfd9cee0aed225ed1c501,72,2,1,0.027778,72,0.027778,0.013889,0.1,32.265972,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,59007be801efbd0001856baf,72,0,1,0.000000,72,0.000000,0.013889,0.0,10.793125,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,5e6e35cac8f7653d80726811,72,0,1,0.000000,72,0.000000,0.013889,0.0,9.578764,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8,5e9b4d1efab83b050f3bd741,72,0,0,0.000000,72,0.000000,0.000000,0.0,39.127903,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

### All annotations

* Workers with highest contradiction to annotations ratio appear on top
* use the pandas dataframe sort method to sort on other values: 
* Check how the behavior of a specific worker with many contradictions compares to other workers

`df.sort_values(by, axis=0, ascending=True, inplace=False, kind='quicksort', na_position='last')`

In [27]:
run = '*'
batch = '*'
n_q = '*'
group = 'experiment2'

data_dict_list = load_experiment_data(run, group, n_q, batch, remove_not_val = True)
name = f'run{run}-group_{group}-batch{batch}'.replace('*', '-all-')
df_total, filepath = get_worker_analysis(data_dict_list, name)
df_total.drop(['annotations'], axis = 1, inplace=True)
df_total[:10]

Discarded 0.0 annotations.

,workerid,n_annotations,n_contradictions,n_fails,contradiction_annotation_ratio,n_possible_contradictions,contradiction_poss_contradiction_ratio,fail_annotation_ratio,contradictory_pairs_ratio,average_time_question,...,"(impossible, typical_of_concept)","(typical_of_concept, unusual)","(affording_activity, unusual)","(implied_category, unusual)","(typical_of_property, unusual)","(rare, typical_of_property)","(afforded_usual, impossible)","(afforded_usual, rare)","(afforded_usual, unusual)","(impossible, typical_of_property)"
16,5e7d04851ae8680b7c88e7e4,72,24,1,0.333333,72,0.333333,0.013889,0.400000,13.606750,...,1.0,3.0,1.0,3.0,2.0,2.0,1.0,1.0,1.0,1.0
0,55b24072fdf99b2462d7d259,72,27,0,0.375000,84,0.321429,0.000000,0.666667,12.016708,...,2.0,3.0,5.0,3.0,2.0,1.0,NaN,NaN,NaN,NaN
11,5d977727646bb70012d6ea5b,72,14,1,0.194444,72,0.194444,0.013889,0.500000,7.412889,...,NaN,1.0,1.0,3.0,2.0,1.0,NaN,NaN,NaN,NaN
14,5e66c749fd0e5b454700f10f,72,11,1,0.152778,72,0.152778,0.013889,0.300000,10.719486,...,1.0,1.0,1.0,NaN,NaN,1.0,NaN,NaN,NaN,NaN
10,58ac3822890ea500014c665d,72,7,1,0.097222,72,0.097222,0.013889,0.200000,24.351819,...,NaN,NaN,1.0,1.0,NaN,NaN,1.0,1.0,1.0,NaN
4,59a42dd68d2b1600011b407d,72,8,0,0.111111,84,0.095238,0.000000,0.333333,15.128681,...,1.0,1.0,NaN,2.0,NaN,NaN,NaN,NaN,NaN,NaN
7,5b872639a89e62000113cbb6,72,6,0,0.083333,84,0.071429,0.000000,0.333333,7.642375,...,NaN,NaN,1.0,2.0,NaN,NaN,NaN,NaN,NaN,NaN
9,5e23cce1233c6c674df6fb07,72,4,0,0.055556,84,0.047619,0.000000,0.222222,18.718042,...,NaN,NaN,2.0,1.0,NaN,NaN,NaN,NaN,NaN,NaN
13,5e1aed4331d8d93320bc6d4e,77,3,1,0.038961,72,0.041667,0.012987,0.200000,13.547494,...,1.0,NaN,NaN,NaN,NaN,NaN,1.0,NaN,NaN,NaN
3,59007be801efbd0001856baf,144,6,1,0.041667,156,0.038462,0.006944,0.055556,9.163729,...,NaN,NaN,1.0,1.0,NaN,NaN,NaN,NaN,NaN,NaN

In [28]:
# Good workers
df_total[-20:]

,workerid,n_annotations,n_contradictions,n_fails,contradiction_annotation_ratio,n_possible_contradictions,contradiction_poss_contradiction_ratio,fail_annotation_ratio,contradictory_pairs_ratio,average_time_question,...,"(impossible, typical_of_concept)","(typical_of_concept, unusual)","(affording_activity, unusual)","(implied_category, unusual)","(typical_of_property, unusual)","(rare, typical_of_property)","(afforded_usual, impossible)","(afforded_usual, rare)","(afforded_usual, unusual)","(impossible, typical_of_property)"
16,5e7d04851ae8680b7c88e7e4,72,24,1,0.333333,72,0.333333,0.013889,0.400000,13.606750,...,1.0,3.0,1.0,3.0,2.0,2.0,1.0,1.0,1.0,1.0
0,55b24072fdf99b2462d7d259,72,27,0,0.375000,84,0.321429,0.000000,0.666667,12.016708,...,2.0,3.0,5.0,3.0,2.0,1.0,NaN,NaN,NaN,NaN
11,5d977727646bb70012d6ea5b,72,14,1,0.194444,72,0.194444,0.013889,0.500000,7.412889,...,NaN,1.0,1.0,3.0,2.0,1.0,NaN,NaN,NaN,NaN
14,5e66c749fd0e5b454700f10f,72,11,1,0.152778,72,0.152778,0.013889,0.300000,10.719486,...,1.0,1.0,1.0,NaN,NaN,1.0,NaN,NaN,NaN,NaN
10,58ac3822890ea500014c665d,72,7,1,0.097222,72,0.097222,0.013889,0.200000,24.351819,...,NaN,NaN,1.0,1.0,NaN,NaN,1.0,1.0,1.0,NaN
4,59a42dd68d2b1600011b407d,72,8,0,0.111111,84,0.095238,0.000000,0.333333,15.128681,...,1.0,1.0,NaN,2.0,NaN,NaN,NaN,NaN,NaN,NaN
7,5b872639a89e62000113cbb6,72,6,0,0.083333,84,0.071429,0.000000,0.333333,7.642375,...,NaN,NaN,1.0,2.0,NaN,NaN,NaN,NaN,NaN,NaN
9,5e23cce1233c6c674df6fb07,72,4,0,0.055556,84,0.047619,0.000000,0.222222,18.718042,...,NaN,NaN,2.0,1.0,NaN,NaN,NaN,NaN,NaN,NaN
13,5e1aed4331d8d93320bc6d4e,77,3,1,0.038961,72,0.041667,0.012987,0.200000,13.547494,...,1.0,NaN,NaN,NaN,NaN,NaN,1.0,NaN,NaN,NaN
3,59007be801efbd0001856baf,144,6,1,0.041667,156,0.038462,0.006944,0.055556,9.163729,...,NaN,NaN,1.0,1.0,NaN,NaN,NaN,NaN,NaN,NaN
12,5e196bcd49c6aa210ea6aaad,72,2,1,0.027778,72,0.027778,0.013889,0.100000,12.213319,...,NaN,NaN,NaN,NaN,1.0,1.0,NaN,NaN,NaN,NaN
18,5e9cfd9cee0aed225ed1c501,72,2,1,0.027778,72,0.027778,0.013889,0.100000,32.265972,...,NaN,NaN,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,55e7117841988f000d75ce09,72,1,1,0.013889,84,0.011905,0.013889,0.111111,4.525097,...,NaN,NaN,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8,5c3fb75eca00d30001c5187d,72,0,0,0.000000,84,0.000000,0.000000,0.000000,9.645694,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,5aae93f5fb22320001baaaac,72,0,0,0.000000,84,0.000000,0.000000,0.000000,11.753167,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,5aae762bc4e8f200014b3f88,72,0,0,0.000000,84,0.000000,0.000000,0.000000,9.914667,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
15,5e6e35cac8f7653d80726811,72,0,1,0.000000,72,0.000000,0.013889,0.000000,9.578764,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,56e99d054111eb000c77885b,72,0,0,0.000000,84,0.000000,0.000000,0.000000,19.148639,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
17,5e9b4d1efab83b050f3bd741,72,0,0,0.000000,72,0.000000,0.000000,0.000000,39.127903,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

### Get all contradictions and fails of a particular worker 

* Check if a specfic worker continuously contradicts themselves (and fails checks)

In [5]:
# copy from above - worker with many disagreements in target batch
worker = '5e7d04851ae8680b7c88e7e4'


# df.loc[df['column_name'] == some_value]
df_total.loc[df_total['workerid'] == worker]

,workerid,n_annotations,n_contradictions,n_fails,contradiction_annotation_ratio,n_possible_contradictions,contradiction_poss_contradiction_ratio,fail_annotation_ratio,contradictory_pairs_ratio,average_time_question,...,"(impossible, typical_of_concept)","(typical_of_concept, unusual)","(affording_activity, unusual)","(implied_category, unusual)","(typical_of_property, unusual)","(rare, typical_of_property)","(afforded_usual, impossible)","(afforded_usual, rare)","(afforded_usual, unusual)","(impossible, typical_of_property)"
16,5e7d04851ae8680b7c88e7e4,72,24,1,0.333333,72,0.333333,0.013889,0.4,13.60675,...,1.0,3.0,1.0,3.0,2.0,2.0,1.0,1.0,1.0,1.0

# Analyze pairs

* compars number of annotator contradictions among pairs

### Current batch:

In [13]:
run = '4'
batch = '*'
n_q = '*'
group = 'experiment2'

data_dict_list = load_experiment_data(run, group, n_q, batch, remove_not_val = True)
name = f'run{run}-group_{group}-batch{batch}'.replace('*', '-all-')
df, filepath = get_pair_analysis(data_dict_list, name)
df.drop(['annotations_with_contradiction'], axis = 1, inplace=True)
df

Discarded 0.0 annotations.

,pair,n_annotations,n_workers,n_contradictions,n_workers_contradicting,ratio_workers_contradicting,contradiction_annotation_ratio,n_possible_contradictions,contradiction_poss_contradiction_ratio,average_time_pair,...,"(impossible, typical_of_concept)","(implied_category, unusual)","(typical_of_concept, unusual)","(affording_activity, unusual)","(typical_of_property, unusual)","(rare, typical_of_property)","(afforded_usual, rare)","(afforded_usual, impossible)","(afforded_usual, unusual)","(impossible, typical_of_property)"
9,sweet-hazelnut,101,10,11,4,0.4,0.108911,120,0.091667,124.733665,...,1.0,1.0,1.0,1.0,NaN,NaN,NaN,NaN,NaN,NaN
15,black-pipefish,102,10,14,4,0.4,0.137255,120,0.116667,123.943395,...,NaN,2.0,1.0,1.0,2.0,2.0,NaN,NaN,NaN,NaN
5,wheels-stage,100,10,15,4,0.4,0.150000,120,0.125000,83.539730,...,NaN,2.0,1.0,3.0,1.0,1.0,NaN,NaN,NaN,NaN
16,fly-nuthatch,100,10,12,3,0.3,0.120000,120,0.100000,125.681990,...,1.0,1.0,1.0,NaN,1.0,NaN,1.0,3.0,2.0,1.0
4,wheels-rig,100,10,5,3,0.3,0.050000,120,0.041667,83.539730,...,NaN,1.0,NaN,3.0,NaN,NaN,NaN,NaN,NaN,NaN
11,made_of_wood-timber,101,10,10,3,0.3,0.099010,120,0.083333,124.733665,...,NaN,2.0,1.0,1.0,1.0,1.0,NaN,NaN,NaN,NaN
1,wheels-railcar,100,10,7,2,0.2,0.070000,120,0.058333,83.539730,...,1.0,1.0,1.0,1.0,NaN,NaN,NaN,NaN,NaN,NaN
13,lay_eggs-eland,101,10,8,2,0.2,0.079208,120,0.066667,124.733665,...,NaN,1.0,NaN,NaN,1.0,2.0,1.0,NaN,NaN,NaN
10,hot-candy,100,10,8,2,0.2,0.080000,120,0.066667,125.681990,...,1.0,NaN,1.0,2.0,NaN,NaN,NaN,NaN,NaN,NaN
0,dangerous-unction,100,10,10,2,0.2,0.100000,120,0.083333,83.539730,...,2.0,1.0,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,dangerous-opener,100,10,5,2,0.2,0.050000,120,0.041667,83.539730,...,NaN,1.0,1.0,1.0,1.0,NaN,NaN,NaN,NaN,NaN
2,dangerous-plane,100,10,8,2,0.2,0.080000,120,0.066667,83.539730,...,NaN,2.0,NaN,1.0,NaN,NaN,NaN,NaN,NaN,NaN
6,dangerous-bar,100,10,2,1,0.1,0.020000,120,0.016667,83.539730,...,NaN,1.0,NaN,1.0,NaN,NaN,NaN,NaN,NaN,NaN
8,_test3-_test,10,10,0,0,0.0,0.000000,0,0.000000,835.397300,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7,_check3-_check3,20,19,0,0,0.0,0.000000,0,0.000000,1066.441237,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
12,wheels-carriage,60,10,0,0,0.0,0.000000,0,0.000000,209.469983,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
14,yellow-vanilla,40,10,0,0,0.0,0.000000,0,0.000000,314.204975,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
17,_test4-_test,10,10,0,0,0.0,0.000000,0,0.000000,1256.819900,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

### Get rows with pairs annotated by specific workers:

* Check if a worker in the only one contradicting or if others also had issues with the pairs

In [7]:
worker = '5e7d04851ae8680b7c88e7e4'

show_pairs_of_worker(worker, df)

Worker 5e7d04851ae8680b7c88e7e4 contradicted themselves in the following pairs:

sweet-hazelnut 	 total workers contradicting themselves: 4
black-pipefish 	 total workers contradicting themselves: 4
fly-nuthatch 	 total workers contradicting themselves: 3
lay_eggs-eland 	 total workers contradicting themselves: 2

### Compare to entire annotation set

In [16]:
run = '4'
batch = '*'
n_q = '*'
group = 'experiment2'

data_dict_list = load_experiment_data(run, group, n_q, batch, remove_not_val = True)
name = f'run{run}-group_{group}-batch{batch}'.replace('*', '-all-')
df, filepath = get_pair_analysis(data_dict_list, name)
df.drop(['annotations_with_contradiction'], axis = 1, inplace=True)
df

Discarded 0.0 annotations.

,pair,n_annotations,n_workers,n_contradictions,n_workers_contradicting,ratio_workers_contradicting,contradiction_annotation_ratio,n_possible_contradictions,contradiction_poss_contradiction_ratio,average_time_pair,...,"(impossible, typical_of_concept)","(implied_category, unusual)","(typical_of_concept, unusual)","(affording_activity, unusual)","(typical_of_property, unusual)","(rare, typical_of_property)","(afforded_usual, rare)","(afforded_usual, impossible)","(afforded_usual, unusual)","(impossible, typical_of_property)"
9,sweet-hazelnut,101,10,11,4,0.4,0.108911,120,0.091667,124.733665,...,1.0,1.0,1.0,1.0,NaN,NaN,NaN,NaN,NaN,NaN
15,black-pipefish,102,10,14,4,0.4,0.137255,120,0.116667,123.943395,...,NaN,2.0,1.0,1.0,2.0,2.0,NaN,NaN,NaN,NaN
5,wheels-stage,100,10,15,4,0.4,0.150000,120,0.125000,83.539730,...,NaN,2.0,1.0,3.0,1.0,1.0,NaN,NaN,NaN,NaN
16,fly-nuthatch,100,10,12,3,0.3,0.120000,120,0.100000,125.681990,...,1.0,1.0,1.0,NaN,1.0,NaN,1.0,3.0,2.0,1.0
4,wheels-rig,100,10,5,3,0.3,0.050000,120,0.041667,83.539730,...,NaN,1.0,NaN,3.0,NaN,NaN,NaN,NaN,NaN,NaN
11,made_of_wood-timber,101,10,10,3,0.3,0.099010,120,0.083333,124.733665,...,NaN,2.0,1.0,1.0,1.0,1.0,NaN,NaN,NaN,NaN
1,wheels-railcar,100,10,7,2,0.2,0.070000,120,0.058333,83.539730,...,1.0,1.0,1.0,1.0,NaN,NaN,NaN,NaN,NaN,NaN
13,lay_eggs-eland,101,10,8,2,0.2,0.079208,120,0.066667,124.733665,...,NaN,1.0,NaN,NaN,1.0,2.0,1.0,NaN,NaN,NaN
10,hot-candy,100,10,8,2,0.2,0.080000,120,0.066667,125.681990,...,1.0,NaN,1.0,2.0,NaN,NaN,NaN,NaN,NaN,NaN
0,dangerous-unction,100,10,10,2,0.2,0.100000,120,0.083333,83.539730,...,2.0,1.0,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,dangerous-opener,100,10,5,2,0.2,0.050000,120,0.041667,83.539730,...,NaN,1.0,1.0,1.0,1.0,NaN,NaN,NaN,NaN,NaN
2,dangerous-plane,100,10,8,2,0.2,0.080000,120,0.066667,83.539730,...,NaN,2.0,NaN,1.0,NaN,NaN,NaN,NaN,NaN,NaN
6,dangerous-bar,100,10,2,1,0.1,0.020000,120,0.016667,83.539730,...,NaN,1.0,NaN,1.0,NaN,NaN,NaN,NaN,NaN,NaN
8,_test3-_test,10,10,0,0,0.0,0.000000,0,0.000000,835.397300,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7,_check3-_check3,20,19,0,0,0.0,0.000000,0,0.000000,1066.441237,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
12,wheels-carriage,60,10,0,0,0.0,0.000000,0,0.000000,209.469983,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
14,yellow-vanilla,40,10,0,0,0.0,0.000000,0,0.000000,314.204975,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
17,_test4-_test,10,10,0,0,0.0,0.000000,0,0.000000,1256.819900,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [10]:
# check specific pair:

pair = 'red-lipstick'
df.loc[df['pair'] == pair]

,pair,n_annotations,n_workers,n_contradictions,n_workers_contradicting,ratio_workers_contradicting,contradiction_annotation_ratio,average_time_pair,workers_contradicting,workers_not_contradicting,...,"(affording_activity, unusual)","(rare, typical_of_concept)","(rare, typical_of_property)","(implied_category, rare)","(implied_category, impossible)","(affording_activity, impossible)","(afforded_unusual, impossible)","(afforded_usual, rare)","(afforded_unusual, rare)","(afforded_usual, impossible)"
305,red-lipstick,50,5,7,2,0.4,0.14,59.799,57617fdb1a5ecc0006fc3860 5ddc0d87d3ac2ad102aff2b9,59dc2e2016ecc200016fea95 5c544985be9cd80001156...,...,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

### Compare contradictions between runs:

In [19]:
run = '3'
batch = '*'
n_q = '*'
group = 'experiment1'

data_dict_list = load_experiment_data(run, group, n_q, batch, remove_not_val = True)
name = f'run{run}-group_{group}-batch{batch}'.replace('*', '-all-')
df1, filepath = get_pair_analysis(data_dict_list, name)
print(f'analysis can be found at: {filepath}')

run = '4'
batch = '*'
n_q = '*'
group = 'experiment2'

data_dict_list = load_experiment_data(run, group, n_q, batch, remove_not_val = True)
name = f'run{run}-group_{group}-batch{batch}'.replace('*', '-all-')
df2, filepath = get_pair_analysis(data_dict_list, name)
print(f'analysis can be found at: {filepath}')

name1 = '3'
name2 = '4'
compare_runs(name1, name2, df1, df2, comp = 'all')
#print()
#compare_runs(name1, name2, df1, df2, comp = 'pairs')

Discarded 655.0 annotations.
analysis can be found at: ../analyses/pairs/run3-group_experiment1-batch-all-.csv
Discarded 0.0 annotations.
analysis can be found at: ../analyses/pairs/run4-group_experiment2-batch-all-.csv
Set 3 as a contradiction ratio of 0.20542056074766354
Set 4 as a contradiction ratio of 0.17989417989417988
The ratio is based on the number of workers annotating a pair.
A worker always annotates a full set.

(0.20542056074766354, 0.17989417989417988)

# Inter-annotator agreement

* Total agreement
* Agreement by relations
* agreement after removing annotators with many contradictions/annotators who fail checks/contradictory annotations

## Total iaa:

In [20]:
run = '*'
batch = '*'
n_q = '*'
group = 'experiment1'
print(f"Run {run}:")
data_dict_list = load_experiment_data(run, group, n_q, batch, remove_not_val = True)
get_agreement(data_dict_list)

run = '4'
batch = '*'
n_q = '*'
group = 'experiment2'
print(f"Run {run}:")
data_dict_list = load_experiment_data(run, group, n_q, batch, remove_not_val = True)

get_agreement(data_dict_list)

Run *:
Discarded 655.0 annotations.
Krippendorff's alpha: 0.23567624334318582
Proportional agreement (pairwise): 0.6233819990832739

Run 4:
Discarded 0.0 annotations.
Krippendorff's alpha: 0.2557092823160244
Proportional agreement (pairwise): 0.6446280991735535

{'Krippendorff': 0.2557092823160244, 'Proportional': 0.6446280991735535}

## IAA of collapsed relations

In [21]:
run = '*'
batch = '*'
n_q = '*'
group = 'experiment1'
print(f"Run {run}:")
data_dict_list = load_experiment_data(run, group, n_q, batch, remove_not_val = True)
get_agreement(data_dict_list)

collapse_relations = 'pos_neg'
print(f'collapsing {collapse_relations}')
get_agreement(data_dict_list, collapse_relations = collapse_relations)

collapse_relations = 'levels'
print(f'collapsing {collapse_relations}')
get_agreement(data_dict_list, collapse_relations = collapse_relations)

collapse_relations = 'similar_relations'
print(f'collapsing {collapse_relations}')
get_agreement(data_dict_list, collapse_relations = collapse_relations)


run = '4'
batch = '*'
n_q = '*'
group = 'experiment2'
print(f"Run {run}:")
data_dict_list = load_experiment_data(run, group, n_q, batch, remove_not_val = True)
get_agreement(data_dict_list)

collapse_relations = 'pos_neg'
print(f'collapsing {collapse_relations}')
get_agreement(data_dict_list, collapse_relations = collapse_relations)

collapse_relations = 'levels'
print(f'collapsing {collapse_relations}')
get_agreement(data_dict_list, collapse_relations = collapse_relations)

collapse_relations = 'similar_relations'
print(f'collapsing {collapse_relations}')
get_agreement(data_dict_list, collapse_relations = collapse_relations)

Run *:
Discarded 655.0 annotations.
Krippendorff's alpha: 0.23567624334318582
Proportional agreement (pairwise): 0.6233819990832739

collapsing pos_neg
pos_neg
Krippendorff's alpha: 0.3348903198600117
Proportional agreement (pairwise): 0.7902502664705034

collapsing levels
levels
Krippendorff's alpha: 0.3555916355102202
Proportional agreement (pairwise): 0.7038679436637708

collapsing similar_relations
similar_relations
Krippendorff's alpha: 0.37526324080891615
Proportional agreement (pairwise): 0.6967938704580102

Run 4:
Discarded 0.0 annotations.
Krippendorff's alpha: 0.2557092823160244
Proportional agreement (pairwise): 0.6446280991735535

collapsing pos_neg
pos_neg
Krippendorff's alpha: 0.34615384615384615
Proportional agreement (pairwise): 0.7154610622352557

collapsing levels
levels
Krippendorff's alpha: 0.4013903547010509
Proportional agreement (pairwise): 0.7050020579307507

collapsing similar_relations
similar_relations
Krippendorff's alpha: 0.3774123398935175
Proportional agreement (pairwise): 0.741418442380525

{'Krippendorff': 0.3774123398935175, 'Proportional': 0.741418442380525}

## IAA by relation

In [12]:
runs = ['3', '1']
experiment_name = 'experiment1'
path, df = agreement_relations_across_runs(runs, experiment_name)
print(f'Results written to: {path}')
df

Discarded 655.0 annotations.
Discarded 0.0 annotations.
Results written to: ../analyses/iaa/relations_runs3-1.csv

,relation,3_Krippendorff,3_Proportional,1_Krippendorff,1_Proportional
0,implied_category,0.261604,0.648495,0.260459,0.629956
1,affording_activity,0.196837,0.654605,0.149149,0.672259
2,variability_subcategories,NaN,NaN,0.157270,0.579637
3,impossible,0.134907,0.658426,0.183925,0.679565
4,variability_limited,0.103003,0.551718,0.197795,0.599990
5,afforded_usual,0.172981,0.644417,0.336767,0.698580
6,typical_of_property,0.231757,0.755240,0.326482,0.682547
7,creative,0.059688,0.544502,0.040020,0.524894
8,rare,0.132488,0.576444,NaN,NaN
9,typical_of_concept,0.311785,0.712881,0.367910,0.689440
10,afforded_unusual,0.068180,0.544889,0.108460,0.557623
11,test_true,0.045786,0.794077,NaN,NaN
12,_check,0.606292,0.884235,0.904637,0.964443
13,test_false,0.258187,0.702768,NaN,NaN
14,unusual,0.159998,0.576699,0.120147,0.561644
15,variability_open,0.214621,0.606366,0.143751,0.580081

## Agreement after removing workers or annotations:

In [32]:
run = '3'
batch = '*'
n_q = '*'
group = 'experiment1'

print('Total Agreement')
data_dict_list = load_experiment_data(run, group, n_q, batch, remove_not_val = True)
get_agreement(data_dict_list)
print('-------')
print()

print('Removing pair annotations with many contradictions:')
category = 'pairs_contradictions'
print(f'analyze {category}')
annotations_clean, annotations_removed = clean_annotations(run, group, n_q, batch, category)
print('agreement clean')
get_agreement(annotations_clean)
#print('agreement rest')
#get_agreement(annotations_removed)


category = 'worker_contradictions'
print(f'analyze {category}')
annotations_clean, annotations_removed = clean_annotations(run, group, n_q, batch, category)
print('agreement clean')
get_agreement(annotations_clean)
#print('agreement rest')
#get_agreement(annotations_removed)
print()

category = 'worker_checks'
print(f'analyze {category}')
annotations_clean, annotations_removed = clean_annotations(run, group, n_q, batch, category)
print('agreement clean')
get_agreement(annotations_clean)
#print('agreement rest')
#get_agreement(annotations_removed)

Total Agreement
Discarded 655.0 annotations.
Krippendorff's alpha: 0.23336207839907597
Proportional agreement (pairwise): 0.6304754199128316

-------

Removing pair annotations with many contradictions:
analyze pairs_contradictions
Discarded 655.0 annotations.
Found 24827 clean annotations.
Round 10212 to remove.

agreement clean
Krippendorff's alpha: 0.33405102479157067
Proportional agreement (pairwise): 0.68651450192071

analyze worker_contradictions
Discarded 655.0 annotations.
Found 24877 clean annotations.
Round 10100 to remove.

agreement clean
Krippendorff's alpha: 0.24953378047207264
Proportional agreement (pairwise): 0.6498735089301452


analyze worker_checks
Discarded 655.0 annotations.
Found 32448 clean annotations.
Round 2529 to remove.

agreement clean
Krippendorff's alpha: 0.25028983009201133
Proportional agreement (pairwise): 0.639896601266422

{'Krippendorff': 0.25028983009201133, 'Proportional': 0.639896601266422}