# Annotation analysis

This noteboook

* illustrates the steps of the analysis currently implemented
* is used to analyze and monitor workers batch by batch

In [44]:
from load_data import load_experiment_data
from analyze_workers import get_worker_analysis
from analyze_pairs import get_pair_analysis
from analyze_pairs import show_pairs_of_worker
from analyze_pairs import compare_runs
from calculate_iaa import get_agreement
from clean_annotations import clean_annotations

# Analyze worker contradictions:

* Workers with highest contradiction to annotations ratio appear on top
* use the pandas dataframe sort method to sort on other values: 

`df.sort_values(by, axis=0, ascending=True, inplace=False, kind='quicksort', na_position='last')`

### Current batch

In [54]:
run = 3
batch = 18
n_q = 70
group = 'experiment1'

data_dict_list = load_experiment_data(run, group, n_q, batch, remove_not_val = True)
name = f'run{run}-group_{group}-batch{batch}'.replace('*', '-all-')
df, filepath = get_worker_analysis(data_dict_list, name)
df.drop(['annotations'], axis = 1, inplace=True)
df

creating file with uuid run3-group_experiment1/qu70-s_qu70-batch18.csv
added unique ids - file can be found at: ../data/prolific_output_uuid/run3-group_experiment1/qu70-s_qu70-batch18.csv

,workerid,n_annotations,n_contradictions,n_fails,contradiction_annotation_ratio,fail_annotation_ratio,average_time_question,"(impossible, typical_of_property)","(affording_activity, rare)","(implied_category, rare)","(affording_activity, unusual)","(impossible, typical_of_concept)"
3,5d206e075278fa001848134d,80,3,0,0.0375,0.0,7.669412,1.0,1.0,1.0,NaN,NaN
4,5d51bb808dace500197a54c7,80,2,0,0.0250,0.0,4.361112,NaN,1.0,NaN,1.0,NaN
9,5e73a3f9a53b483104353b5f,80,2,0,0.0250,0.0,13.846425,NaN,1.0,1.0,NaN,NaN
5,5e10c28282052679c88dcb9f,80,1,0,0.0125,0.0,7.560875,NaN,NaN,NaN,NaN,1.0
6,5e518641c702b0000d6da0b5,80,1,0,0.0125,0.0,10.352625,NaN,1.0,NaN,NaN,NaN
8,5e722d72a2b106155672f855,80,1,0,0.0125,0.0,11.333025,NaN,1.0,NaN,NaN,NaN
0,5a1d9acffe645f0001ea09e9,80,0,0,0.0000,0.0,6.670575,NaN,NaN,NaN,NaN,NaN
1,5c63291ef256940001ca71bd,80,0,0,0.0000,0.0,7.958988,NaN,NaN,NaN,NaN,NaN
2,5d034f7733bb360017370b87,80,0,0,0.0000,0.0,4.802213,NaN,NaN,NaN,NaN,NaN
7,5e5baf4674c9533805ebae09,80,0,0,0.0000,0.0,5.144662,NaN,NaN,NaN,NaN,NaN

### All annotations

* Workers with highest contradiction to annotations ratio appear on top
* use the pandas dataframe sort method to sort on other values: 
* Check how the behavior of a specific worker with many contradictions compares to other workers

`df.sort_values(by, axis=0, ascending=True, inplace=False, kind='quicksort', na_position='last')`

In [55]:
run = '3'
batch = '*'
n_q = '*'
group = 'experiment1'

data_dict_list = load_experiment_data(run, group, n_q, batch, remove_not_val = True)
name = f'run{run}-group_{group}-batch{batch}'.replace('*', '-all-')
df, filepath = get_worker_analysis(data_dict_list, name)
df.drop(['annotations'], axis = 1, inplace=True)
df[:10]

,workerid,n_annotations,n_contradictions,n_fails,contradiction_annotation_ratio,fail_annotation_ratio,average_time_question,"(affording_activity, rare)","(affording_activity, impossible)","(affording_activity, unusual)","(implied_category, impossible)","(impossible, typical_of_property)","(implied_category, unusual)","(rare, typical_of_concept)","(impossible, typical_of_concept)","(typical_of_concept, unusual)","(implied_category, rare)","(rare, typical_of_property)","(typical_of_property, unusual)"
162,5d76a2dc2a476a0001ce6843,75,45,1,0.600000,0.013333,15.823027,5.0,2.0,4.0,3.0,2.0,5.0,5.0,3.0,5.0,5.0,3.0,3.0
156,5e76ab49dec4562243b421f9,79,35,2,0.443038,0.025316,17.116886,4.0,3.0,4.0,2.0,1.0,2.0,4.0,3.0,4.0,2.0,3.0,3.0
78,5c2bd5f88c234c00018b91f8,78,28,0,0.358974,0.000000,2.837038,3.0,3.0,2.0,3.0,2.0,2.0,1.0,1.0,2.0,3.0,3.0,3.0
123,5c8d3f8bf756d40016683868,76,25,0,0.328947,0.000000,12.950526,NaN,1.0,1.0,2.0,1.0,6.0,2.0,NaN,4.0,3.0,2.0,3.0
98,5e71fc448ebe4211e668e71f,72,23,1,0.319444,0.013889,7.325736,NaN,2.0,2.0,2.0,2.0,3.0,2.0,2.0,3.0,2.0,1.0,2.0
111,5dc029217fa54e4545661559,72,21,1,0.291667,0.013889,6.118708,NaN,1.0,1.0,2.0,1.0,3.0,2.0,3.0,2.0,2.0,2.0,2.0
26,5c1d4d88508cfd000103dc47,151,43,2,0.284768,0.013245,21.793230,3.0,3.0,4.0,3.0,2.0,6.0,3.0,3.0,5.0,3.0,4.0,4.0
11,5dac6532ccaa330016e11e8f,53,15,1,0.283019,0.018868,0.000000,3.0,1.0,2.0,NaN,1.0,1.0,3.0,1.0,NaN,1.0,2.0,NaN
71,Programmer,80,19,0,0.237500,0.000000,0.000000,4.0,3.0,2.0,2.0,NaN,1.0,NaN,1.0,2.0,3.0,1.0,NaN
174,5e673f3fb47a554b79b02c5a,72,17,0,0.236111,0.000000,5.850250,3.0,1.0,2.0,1.0,NaN,2.0,1.0,NaN,1.0,3.0,1.0,2.0

### Get all disagreements and fails of a particular worker 

* Check if a specfic worker continuously contradicts themselves (and fails checks)

In [56]:
# copy from above - worker with many disagreements in target batch
worker = '5d206e075278fa001848134d'

# df.loc[df['column_name'] == some_value]
df.loc[df['workerid'] == worker]

,workerid,n_annotations,n_contradictions,n_fails,contradiction_annotation_ratio,fail_annotation_ratio,average_time_question,"(affording_activity, rare)","(affording_activity, impossible)","(affording_activity, unusual)","(implied_category, impossible)","(impossible, typical_of_property)","(implied_category, unusual)","(rare, typical_of_concept)","(impossible, typical_of_concept)","(typical_of_concept, unusual)","(implied_category, rare)","(rare, typical_of_property)","(typical_of_property, unusual)"
15,5d206e075278fa001848134d,80,3,0,0.0375,0.0,7.669412,1.0,NaN,NaN,NaN,1.0,NaN,NaN,NaN,NaN,1.0,NaN,NaN

# Analyze pairs

* compars number of annotator contradictions among pairs

### Current batch:

In [58]:
run = '3'
batch = '18'
n_q = '*'
group = 'experiment1'

data_dict_list = load_experiment_data(run, group, n_q, batch, remove_not_val = True)
name = f'run{run}-group_{group}-batch{batch}'.replace('*', '-all-')
df, filepath = get_pair_analysis(data_dict_list, name)
df.drop(['annotations_with_contradiction'], axis = 1, inplace=True)
df

,pair,n_annotations,n_workers,n_contradictions,n_workers_contradicting,ratio_workers_contradicting,contradiction_annotation_ratio,average_time_pair,workers_contradicting,workers_not_contradicting,"(affording_activity, rare)","(affording_activity, unusual)","(implied_category, rare)","(impossible, typical_of_property)","(impossible, typical_of_concept)"
1,round-sapodilla,100,10,4,2,0.2,0.04,63.75993,5d51bb808dace500197a54c7 5e73a3f9a53b483104353b5f,5a1d9acffe645f0001ea09e9 5c63291ef256940001ca7...,2.0,1.0,1.0,NaN,NaN
9,red-hair,100,10,3,2,0.2,0.03,63.75993,5d206e075278fa001848134d 5e722d72a2b106155672f855,5a1d9acffe645f0001ea09e9 5c63291ef256940001ca7...,2.0,NaN,1.0,NaN,NaN
5,round-enchiladas,100,10,2,2,0.2,0.02,63.75993,5d206e075278fa001848134d 5e518641c702b0000d6da0b5,5a1d9acffe645f0001ea09e9 5c63291ef256940001ca7...,1.0,NaN,NaN,1.0,NaN
8,red-ruby,100,10,1,1,0.1,0.01,63.75993,5e10c28282052679c88dcb9f,5a1d9acffe645f0001ea09e9 5c63291ef256940001ca7...,NaN,NaN,NaN,NaN,1.0
0,round-syrup,100,10,0,0,0.0,0.00,63.75993,,5a1d9acffe645f0001ea09e9 5c63291ef256940001ca7...,NaN,NaN,NaN,NaN,NaN
2,roll-shovel,10,10,0,0,0.0,0.00,637.59930,,5a1d9acffe645f0001ea09e9 5c63291ef256940001ca7...,NaN,NaN,NaN,NaN,NaN
3,red-tiger,100,10,0,0,0.0,0.00,63.75993,,5a1d9acffe645f0001ea09e9 5c63291ef256940001ca7...,NaN,NaN,NaN,NaN,NaN
4,roll-wagon,10,10,0,0,0.0,0.00,637.59930,,5a1d9acffe645f0001ea09e9 5c63291ef256940001ca7...,NaN,NaN,NaN,NaN,NaN
6,red-hazelnut,100,10,0,0,0.0,0.00,63.75993,,5a1d9acffe645f0001ea09e9 5c63291ef256940001ca7...,NaN,NaN,NaN,NaN,NaN
7,round-cabbage,60,10,0,0,0.0,0.00,106.26655,,5a1d9acffe645f0001ea09e9 5c63291ef256940001ca7...,NaN,NaN,NaN,NaN,NaN
10,_check1-_check1,10,10,0,0,0.0,0.00,637.59930,,5a1d9acffe645f0001ea09e9 5c63291ef256940001ca7...,NaN,NaN,NaN,NaN,NaN
11,_test3-_test3,10,10,0,0,0.0,0.00,637.59930,,5a1d9acffe645f0001ea09e9 5c63291ef256940001ca7...,NaN,NaN,NaN,NaN,NaN

### Get rows with pairs annotated by specific workers:

* Check if a worker in the only one contradicting or if others also had issues with the pairs

In [59]:
worker = '5d206e075278fa001848134d'

show_pairs_of_worker(worker, df)

Worker 5d206e075278fa001848134d contradicted themselves in the following pairs:

red-hair 	 total workers contradicting themselves: 2
round-enchiladas 	 total workers contradicting themselves: 2

### Compare to entire annotation set

In [60]:
run = '*'
batch = '*'
n_q = '*'
group = 'experiment1'

data_dict_list = load_experiment_data(run, group, n_q, batch, remove_not_val = True)
name = f'run{run}-group_{group}-batch{batch}'.replace('*', '-all-')
df, filepath = get_pair_analysis(data_dict_list, name)
df.drop(['annotations_with_contradiction'], axis = 1, inplace=True)
df

,pair,n_annotations,n_workers,n_contradictions,n_workers_contradicting,ratio_workers_contradicting,contradiction_annotation_ratio,average_time_pair,workers_contradicting,workers_not_contradicting,...,"(impossible, typical_of_property)","(affording_activity, unusual)","(implied_category, impossible)","(implied_category, rare)","(rare, typical_of_concept)","(rare, typical_of_property)","(affording_activity, impossible)","(afforded_unusual, impossible)","(afforded_usual, impossible)","(affording_activity, rare)"
26,roll-spindle,50,5,22,4,0.8,0.44,57.711660,5dc0395f2a1dd64710661ccd 5ddc56fbf290e7bbfa964...,5de6be6912bcf6041b3276ba,...,2.0,NaN,2.0,NaN,NaN,NaN,NaN,2.0,2.0,NaN
231,roll-bolt,50,5,21,5,1.0,0.42,85.335380,5acb5910e1546900019c413a 5c5758e9efe1550001dc3...,,...,1.0,NaN,NaN,NaN,NaN,NaN,NaN,1.0,1.0,NaN
23,roll-mandrel,50,5,21,5,1.0,0.42,57.711660,5dc0395f2a1dd64710661ccd 5ddc56fbf290e7bbfa964...,,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
227,roll-lamp,50,5,17,4,0.8,0.34,85.335380,5acb5910e1546900019c413a 5d3f14f66a8a4e0018c17...,5c5758e9efe1550001dc31b6,...,2.0,NaN,1.0,NaN,NaN,NaN,NaN,2.0,1.0,NaN
376,roll-barrel,50,5,16,4,0.8,0.32,78.149540,591d7a33e4b20e00016c2798 5a473bda7aebf70001153...,5d4aa7d50b5bf80015ad014d,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
265,round-football,50,5,0,0,0.0,0.00,85.898220,,5ad90f90dec767000128a5f4 5aeded8f0ccc2e0001858...,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
266,red-ladybird,50,5,0,0,0.0,0.00,85.898220,,5ad90f90dec767000128a5f4 5aeded8f0ccc2e0001858...,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
267,red-gorilla,140,14,0,0,0.0,0.00,75.016829,,5ad90f90dec767000128a5f4 5aeded8f0ccc2e0001858...,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
271,red-banana,15,5,0,0,0.0,0.00,286.327400,,5ad90f90dec767000128a5f4 5aeded8f0ccc2e0001858...,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
436,_test1-_test1,39,38,0,0,0.0,0.00,850.945855,,5b222aff59f9620001c109cb 5c62a91524035400014b6...,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

### Compare contradictions between runs:

In [61]:
run = '1'
batch = '*'
n_q = '*'
group = 'experiment1'

data_dict_list = load_experiment_data(run, group, n_q, batch, remove_not_val = True)
name = f'run{run}-group_{group}-batch{batch}'.replace('*', '-all-')
df1, filepath = get_pair_analysis(data_dict_list, name)
print(f'analysis can be found at: {filepath}')

run = '3'
batch = '*'
n_q = '*'
group = 'experiment1'

data_dict_list = load_experiment_data(run, group, n_q, batch, remove_not_val = True)
name = f'run{run}-group_{group}-batch{batch}'.replace('*', '-all-')
df2, filepath = get_pair_analysis(data_dict_list, name)
print(f'analysis can be found at: {filepath}')

name1 = '1'
name2 = '3'
compare_runs(name1, name2, df1, df2, comp = 'all')
print()
compare_runs(name1, name2, df1, df2, comp = 'pairs')

analysis can be found at: ../analyses/pairs/run1-group_experiment1-batch-all-.csv
analysis can be found at: ../analyses/pairs/run3-group_experiment1-batch-all-.csv
Set 1 as a contradiction ratio of 0.26912294753704447
Set 3 as a contradiction ratio of 0.11668928086838534
The ratio is based on the number of workers annotating a pair.
A worker always annotates a full set.

Set 1 as a contradiction ratio of 0.22771474878444084
Set 3 as a contradiction ratio of 0.1271186440677966
The ratio is based on the number of workers annotating a pair.
A worker always annotates a full set.
This analysis only includes pairs annotated in run 1 and run 3.

(0.22771474878444084, 0.1271186440677966)

# Inter-annotator agreement

Compare both runs in original version and version without annotations in which annotators contradict themselves:

In [62]:
run = '3'
batch = '18'
n_q = '*'
group = 'experiment1'
data_dict_list = load_experiment_data(run, group, n_q, batch, remove_not_val = True)

get_agreement(data_dict_list)

run = '3'
batch = '*'
n_q = '*'
group = 'experiment1'
data_dict_list = load_experiment_data(run, group, n_q, batch, remove_not_val = True)

get_agreement(data_dict_list)

Krippendorff's alpha: 0.28407019178507675
Proportional agreement (pairwise): 0.6794444444444443

Krippendorff's alpha: 0.25464404781023575
Proportional agreement (pairwise): 0.6447450510035114

In [38]:
run = '1'
batch = '*'
n_q = '*'
group = 'experiment1'
data_dict_list = load_experiment_data(run, group, n_q, batch, remove_not_val = True)

get_agreement(data_dict_list)

Krippendorff's alpha: 0.2413329996998821
Proportional agreement (pairwise): 0.6204625909422006

In [39]:
run = '3'
batch = '*'
n_q = '*'
group = 'experiment1'

category = 'pairs_contradictions'
print(f'analyze {category}')
annotations_clean, annotations_removed = clean_annotations(run, group, n_q, batch, category)
print('agreement clean')
get_agreement(annotations_clean)
print('agreement rest')
get_agreement(annotations_removed)


category = 'worker_contradictions'
print(f'analyze {category}')
annotations_clean, annotations_removed = clean_annotations(run, group, n_q, batch, category)
print('agreement clean')
get_agreement(annotations_clean)
print('agreement rest')
get_agreement(annotations_removed)


category = 'worker_checks'
print(f'analyze {category}')
annotations_clean, annotations_removed = clean_annotations(run, group, n_q, batch, category)
print('agreement clean')
get_agreement(annotations_clean)
print('agreement rest')
get_agreement(annotations_removed)

analyze pairs_contradictions
Found 10619 clean annotations.
Round 2492 to remove.

agreement clean
Krippendorff's alpha: 0.33854979704773625
Proportional agreement (pairwise): 0.6979987395738319

agreement rest
Krippendorff's alpha: 0.09140486997357211
Proportional agreement (pairwise): 0.3931782256471053

analyze worker_contradictions
Found 4930 clean annotations.
Round 8103 to remove.

agreement clean
Krippendorff's alpha: 0.36158485353969416
Proportional agreement (pairwise): 0.6772690623872616

agreement rest
Krippendorff's alpha: 0.224756133781151
Proportional agreement (pairwise): 0.6143752906637412

analyze worker_checks
Found 10766 clean annotations.
Round 2267 to remove.

agreement clean
Krippendorff's alpha: 0.30735431434397065
Proportional agreement (pairwise): 0.6670677960568823

agreement rest
Krippendorff's alpha: 0.13162011955912623
Proportional agreement (pairwise): 0.46383219408477677