# Annotation analysis

This noteboook

* illustrates the steps of the analysis currently implemented
* is used to analyze and monitor workers batch by batch

In [18]:
from load_data import load_experiment_data
from analyze_workers import get_worker_analysis
from analyze_pairs import get_pair_analysis
from analyze_pairs import show_pairs_of_worker
from analyze_pairs import compare_runs
from calculate_iaa import get_agreement
from clean_annotations import clean_annotations

# Analyze worker contradictions:

* Workers with highest contradiction to annotations ratio appear on top
* use the pandas dataframe sort method to sort on other values: 

`df.sort_values(by, axis=0, ascending=True, inplace=False, kind='quicksort', na_position='last')`

### Current batch

In [19]:
run = 3
batch = 24
n_q = 70
group = 'experiment1'

data_dict_list = load_experiment_data(run, group, n_q, batch, remove_not_val = True)
name = f'run{run}-group_{group}-batch{batch}'.replace('*', '-all-')
df, filepath = get_worker_analysis(data_dict_list, name)
df.drop(['annotations'], axis = 1, inplace=True)
df

creating file with uuid run3-group_experiment1/qu70-s_qu70-batch24.csv
added unique ids - file can be found at: ../data/prolific_output_uuid/run3-group_experiment1/qu70-s_qu70-batch24.csv
Discarded 0.0 annotations.

,workerid,n_annotations,n_contradictions,n_fails,contradiction_annotation_ratio,fail_annotation_ratio,average_time_question,"(typical_of_concept, unusual)","(implied_category, unusual)","(affording_activity, unusual)","(implied_category, rare)","(rare, typical_of_concept)","(typical_of_property, unusual)","(affording_activity, rare)","(affording_activity, impossible)","(implied_category, impossible)","(impossible, typical_of_concept)","(rare, typical_of_property)"
6,5d87ca81c3cecc0001747172,72,24,0,0.333333,0.0,1.691972,2.0,4.0,3.0,3.0,1.0,2.0,2.0,2.0,2.0,2.0,1.0
2,5c4e2d07c401980001ab62d9,72,11,0,0.152778,0.0,9.104278,3.0,3.0,1.0,2.0,2.0,NaN,NaN,NaN,NaN,NaN,NaN
7,5dab291188b2f30017d270c0,72,9,0,0.125000,0.0,4.349556,4.0,1.0,NaN,1.0,1.0,1.0,NaN,NaN,1.0,NaN,NaN
8,5e10836d783225755f7e673f,72,3,0,0.041667,0.0,11.076319,1.0,NaN,1.0,NaN,NaN,1.0,NaN,NaN,NaN,NaN,NaN
5,5d6932258b1f860019e2a7e1,72,2,0,0.027778,0.0,8.445222,NaN,1.0,NaN,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,5d593e9e44609300192e33d1,72,1,0,0.013889,0.0,13.106069,NaN,NaN,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
0,59d686325606100001c25ef0,72,0,0,0.000000,0.0,14.485125,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,5b02fe323bc9af0001909bc5,72,0,0,0.000000,0.0,11.831708,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,5ca92e4aa110d9001971fd0a,72,0,0,0.000000,0.0,7.468167,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9,5e5987efb5420118cfd1cf6e,72,0,0,0.000000,0.0,25.311833,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

### All annotations

* Workers with highest contradiction to annotations ratio appear on top
* use the pandas dataframe sort method to sort on other values: 
* Check how the behavior of a specific worker with many contradictions compares to other workers

`df.sort_values(by, axis=0, ascending=True, inplace=False, kind='quicksort', na_position='last')`

In [25]:
run = '*'
batch = '*'
n_q = '*'
group = 'experiment1'

data_dict_list = load_experiment_data(run, group, n_q, batch, remove_not_val = True)
name = f'run{run}-group_{group}-batch{batch}'.replace('*', '-all-')
df, filepath = get_worker_analysis(data_dict_list, name)
df.drop(['annotations'], axis = 1, inplace=True)
df[:10]

Discarded 655.0 annotations.

,workerid,n_annotations,n_contradictions,n_fails,contradiction_annotation_ratio,fail_annotation_ratio,average_time_question,"(afforded_unusual, unusual)","(typical_of_property, unusual)","(implied_category, unusual)",...,"(impossible, typical_of_concept)","(impossible, typical_of_property)","(implied_category, impossible)","(affording_activity, impossible)","(afforded_unusual, impossible)","(afforded_usual, impossible)","(implied_category, rare)","(rare, typical_of_concept)","(rare, typical_of_property)","(affording_activity, rare)"
502,5d76a2dc2a476a0001ce6843,72,45,1,0.625000,0.013889,16.482319,NaN,3.0,5.0,...,3.0,2.0,3.0,2.0,NaN,NaN,5.0,5.0,3.0,5.0
289,5e4e86b070e1ed2d6e4e3f62,72,42,1,0.583333,0.013889,4.293264,NaN,5.0,5.0,...,1.0,2.0,2.0,1.0,NaN,NaN,5.0,4.0,5.0,4.0
294,5e7cbbbcf0a5a004b60b48f7,72,41,1,0.569444,0.013889,11.482222,NaN,2.0,1.0,...,2.0,4.0,4.0,4.0,NaN,NaN,5.0,4.0,6.0,6.0
241,5c91321c0375460001034cb8,71,38,0,0.535211,0.000000,12.942127,2.0,6.0,6.0,...,5.0,5.0,4.0,1.0,1.0,NaN,NaN,NaN,NaN,NaN
496,5e76ab49dec4562243b421f9,72,35,2,0.486111,0.027778,18.781028,NaN,3.0,2.0,...,3.0,1.0,2.0,3.0,NaN,NaN,2.0,4.0,3.0,4.0
305,5ba4f45c4286a00001ea457f,72,34,1,0.472222,0.013889,9.803042,NaN,4.0,4.0,...,2.0,2.0,2.0,2.0,NaN,NaN,3.0,2.0,3.0,3.0
15,5dc0395f2a1dd64710661ccd,71,33,0,0.464789,0.000000,3.745113,4.0,5.0,5.0,...,3.0,2.0,3.0,1.0,1.0,1.0,NaN,NaN,NaN,NaN
192,5d4434c68225f9001642fcd3,71,30,0,0.422535,0.000000,5.209535,1.0,4.0,4.0,...,3.0,3.0,3.0,3.0,1.0,NaN,NaN,NaN,NaN,NaN
187,5de8dc07f42a16000a301cd6,78,31,0,0.397436,0.000000,4.965808,2.0,5.0,5.0,...,3.0,3.0,3.0,1.0,1.0,1.0,NaN,NaN,NaN,NaN
71,599aca876b939900012da2cd,71,27,0,0.380282,0.000000,19.589310,1.0,6.0,7.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

### Get all disagreements and fails of a particular worker 

* Check if a specfic worker continuously contradicts themselves (and fails checks)

In [26]:
# copy from above - worker with many disagreements in target batch
worker = '5c4e2d07c401980001ab62d9'

# df.loc[df['column_name'] == some_value]
df.loc[df['workerid'] == worker]

,workerid,n_annotations,n_contradictions,n_fails,contradiction_annotation_ratio,fail_annotation_ratio,average_time_question,"(afforded_unusual, unusual)","(typical_of_property, unusual)","(implied_category, unusual)",...,"(impossible, typical_of_concept)","(impossible, typical_of_property)","(implied_category, impossible)","(affording_activity, impossible)","(afforded_unusual, impossible)","(afforded_usual, impossible)","(implied_category, rare)","(rare, typical_of_concept)","(rare, typical_of_property)","(affording_activity, rare)"
345,5c4e2d07c401980001ab62d9,72,11,0,0.152778,0.0,9.104278,NaN,NaN,3.0,...,NaN,NaN,NaN,NaN,NaN,NaN,2.0,2.0,NaN,NaN

# Analyze pairs

* compars number of annotator contradictions among pairs

### Current batch:

In [22]:
run = '3'
batch = '23'
n_q = '*'
group = 'experiment1'

data_dict_list = load_experiment_data(run, group, n_q, batch, remove_not_val = True)
name = f'run{run}-group_{group}-batch{batch}'.replace('*', '-all-')
df, filepath = get_pair_analysis(data_dict_list, name)
df.drop(['annotations_with_contradiction'], axis = 1, inplace=True)
df

Discarded 0.0 annotations.

,pair,n_annotations,n_workers,n_contradictions,n_workers_contradicting,ratio_workers_contradicting,contradiction_annotation_ratio,average_time_pair,workers_contradicting,workers_not_contradicting,...,"(rare, typical_of_concept)","(implied_category, rare)","(affording_activity, rare)","(implied_category, unusual)","(typical_of_concept, unusual)","(affording_activity, impossible)","(impossible, typical_of_concept)","(typical_of_property, unusual)","(rare, typical_of_property)","(impossible, typical_of_property)"
1,round-soursop,100,10,13,3,0.3,0.13,60.055330,5d87ca81c3cecc0001747172 5d9943563cc9670014523...,59bfa457d9e6ba0001b5f2bf 5b222aff59f9620001c10...,...,2.0,1.0,2.0,2.0,3.0,NaN,NaN,NaN,NaN,NaN
3,red-chocolate,100,10,9,1,0.1,0.09,60.055330,5d87ca81c3cecc0001747172,59bfa457d9e6ba0001b5f2bf 5b222aff59f9620001c10...,...,1.0,NaN,1.0,NaN,1.0,1.0,1.0,1.0,1.0,1.0
2,red-mango,100,10,8,3,0.3,0.08,60.055330,5d2a471d608cc7000106fe48 5d87ca81c3cecc0001747...,59bfa457d9e6ba0001b5f2bf 5b222aff59f9620001c10...,...,1.0,NaN,2.0,NaN,NaN,2.0,1.0,NaN,NaN,NaN
4,red-mamey,100,10,8,4,0.4,0.08,60.055330,59bfa457d9e6ba0001b5f2bf 5d87ca81c3cecc0001747...,5b222aff59f9620001c109cb 5c6b0f0dec453a00014d6...,...,1.0,2.0,1.0,2.0,NaN,NaN,NaN,NaN,1.0,NaN
6,red-eye,100,10,4,1,0.1,0.04,60.055330,5d87ca81c3cecc0001747172,59bfa457d9e6ba0001b5f2bf 5b222aff59f9620001c10...,...,1.0,NaN,NaN,NaN,1.0,NaN,NaN,1.0,1.0,NaN
0,round-sausage,100,10,3,2,0.2,0.03,60.055330,5c6b0f0dec453a00014d6a5c 5d87ca81c3cecc0001747172,59bfa457d9e6ba0001b5f2bf 5b222aff59f9620001c10...,...,1.0,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,round-banana,60,10,0,0,0.0,0.00,100.092217,,59bfa457d9e6ba0001b5f2bf 5b222aff59f9620001c10...,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7,_check1-_check1,10,10,0,0,0.0,0.00,600.553300,,59bfa457d9e6ba0001b5f2bf 5b222aff59f9620001c10...,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8,_test2-_test2,10,10,0,0,0.0,0.00,600.553300,,59bfa457d9e6ba0001b5f2bf 5b222aff59f9620001c10...,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

### Get rows with pairs annotated by specific workers:

* Check if a worker in the only one contradicting or if others also had issues with the pairs

In [23]:
worker = '5d87ca81c3cecc0001747172'

show_pairs_of_worker(worker, df)

Worker 5d87ca81c3cecc0001747172 contradicted themselves in the following pairs:

round-soursop 	 total workers contradicting themselves: 3
red-chocolate 	 total workers contradicting themselves: 1
red-mango 	 total workers contradicting themselves: 3
red-mamey 	 total workers contradicting themselves: 4
red-eye 	 total workers contradicting themselves: 1
round-sausage 	 total workers contradicting themselves: 2

### Compare to entire annotation set

In [7]:
run = '*'
batch = '*'
n_q = '*'
group = 'experiment1'

data_dict_list = load_experiment_data(run, group, n_q, batch, remove_not_val = True)
name = f'run{run}-group_{group}-batch{batch}'.replace('*', '-all-')
df, filepath = get_pair_analysis(data_dict_list, name)
df.drop(['annotations_with_contradiction'], axis = 1, inplace=True)
df

Discarded 655.0 annotations.

,pair,n_annotations,n_workers,n_contradictions,n_workers_contradicting,ratio_workers_contradicting,contradiction_annotation_ratio,average_time_pair,workers_contradicting,workers_not_contradicting,...,"(impossible, typical_of_property)","(implied_category, rare)","(rare, typical_of_property)","(affording_activity, unusual)","(implied_category, impossible)","(rare, typical_of_concept)","(affording_activity, impossible)","(afforded_unusual, impossible)","(afforded_usual, impossible)","(affording_activity, rare)"
26,roll-spindle,50,5,22,4,0.8,0.44,57.711660,5dc0395f2a1dd64710661ccd 5ddc56fbf290e7bbfa964...,5de6be6912bcf6041b3276ba,...,2.0,NaN,NaN,NaN,2.0,NaN,NaN,2.0,2.0,NaN
231,roll-bolt,50,5,21,5,1.0,0.42,85.335380,5acb5910e1546900019c413a 5c5758e9efe1550001dc3...,,...,1.0,NaN,NaN,NaN,NaN,NaN,NaN,1.0,1.0,NaN
23,roll-mandrel,50,5,21,5,1.0,0.42,57.711660,5dc0395f2a1dd64710661ccd 5ddc56fbf290e7bbfa964...,,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25,roll-pipe,50,5,19,4,0.8,0.38,57.711660,5dc0395f2a1dd64710661ccd 5ddc56fbf290e7bbfa964...,5de6d199a23d79000bf9aef9,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,1.0,NaN
227,roll-lamp,50,5,17,4,0.8,0.34,85.335380,5acb5910e1546900019c413a 5d3f14f66a8a4e0018c17...,5c5758e9efe1550001dc31b6,...,2.0,NaN,NaN,NaN,1.0,NaN,NaN,2.0,1.0,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
324,round-breadcrumb,50,5,0,0,0.0,0.00,53.131520,,5aed0f3823e2ca0001976444 5c590c02e66e510001ef0...,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
323,red-cat,142,15,0,0,0.0,0.00,70.430573,,5aed0f3823e2ca0001976444 5c590c02e66e510001ef0...,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
176,round-cream,50,5,0,0,0.0,0.00,23.563020,,59d3764946447f00011f0407 5a828ebeeea3d300016e5...,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
320,red-guava,50,5,0,0,0.0,0.00,53.131520,,5aed0f3823e2ca0001976444 5c590c02e66e510001ef0...,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
245,red-beet,35,5,0,0,0.0,0.00,93.395600,,5c8abb61e1b6910001b30615 5d8b0fb691f3e600016e6...,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

### Compare contradictions between runs:

In [17]:
run = '1'
batch = '*'
n_q = '*'
group = 'experiment1'

data_dict_list = load_experiment_data(run, group, n_q, batch, remove_not_val = True)
name = f'run{run}-group_{group}-batch{batch}'.replace('*', '-all-')
df1, filepath = get_pair_analysis(data_dict_list, name)
print(f'analysis can be found at: {filepath}')

run = '3'
batch = '*'
n_q = '*'
group = 'experiment1'

data_dict_list = load_experiment_data(run, group, n_q, batch, remove_not_val = True)
name = f'run{run}-group_{group}-batch{batch}'.replace('*', '-all-')
df2, filepath = get_pair_analysis(data_dict_list, name)
print(f'analysis can be found at: {filepath}')

name1 = '1'
name2 = '3'
compare_runs(name1, name2, df1, df2, comp = 'all')
print()
compare_runs(name1, name2, df1, df2, comp = 'pairs')

Discarded 0.0 annotations.
analysis can be found at: ../analyses/pairs/run1-group_experiment1-batch-all-.csv
Discarded 655.0 annotations.
analysis can be found at: ../analyses/pairs/run3-group_experiment1-batch-all-.csv
Set 1 as a contradiction ratio of 0.26912294753704447
Set 3 as a contradiction ratio of 0.1533487297921478
The ratio is based on the number of workers annotating a pair.
A worker always annotates a full set.

Set 1 as a contradiction ratio of 0.19137931034482758
Set 3 as a contradiction ratio of 0.170997920997921
The ratio is based on the number of workers annotating a pair.
A worker always annotates a full set.
This analysis only includes pairs annotated in run 1 and run 3.

(0.19137931034482758, 0.170997920997921)

# Inter-annotator agreement

Compare both runs in original version and version without annotations in which annotators contradict themselves:

In [9]:
run = '3'
batch = '18'
n_q = '*'
group = 'experiment1'
data_dict_list = load_experiment_data(run, group, n_q, batch, remove_not_val = True)

get_agreement(data_dict_list)

run = '1'
batch = '*'
n_q = '*'
group = 'experiment1'
data_dict_list = load_experiment_data(run, group, n_q, batch, remove_not_val = True)

get_agreement(data_dict_list)

Discarded 20.0 annotations.
Krippendorff's alpha: 0.2933511483129806
Proportional agreement (pairwise): 0.684330484330484

Discarded 0.0 annotations.
Krippendorff's alpha: 0.2413329996998821
Proportional agreement (pairwise): 0.6204625909422005

In [10]:
run = '1'
batch = '*'
n_q = '*'
group = 'experiment1'
data_dict_list = load_experiment_data(run, group, n_q, batch, remove_not_val = True)

get_agreement(data_dict_list)

Discarded 0.0 annotations.
Krippendorff's alpha: 0.2413329996998821
Proportional agreement (pairwise): 0.6204625909422005

In [11]:
run = '3'
batch = '*'
n_q = '*'
group = 'experiment1'

category = 'pairs_contradictions'
print(f'analyze {category}')
annotations_clean, annotations_removed = clean_annotations(run, group, n_q, batch, category)
print('agreement clean')
get_agreement(annotations_clean)
print('agreement rest')
get_agreement(annotations_removed)


category = 'worker_contradictions'
print(f'analyze {category}')
annotations_clean, annotations_removed = clean_annotations(run, group, n_q, batch, category)
print('agreement clean')
get_agreement(annotations_clean)
print('agreement rest')
get_agreement(annotations_removed)


category = 'worker_checks'
print(f'analyze {category}')
annotations_clean, annotations_removed = clean_annotations(run, group, n_q, batch, category)
print('agreement clean')
get_agreement(annotations_clean)
print('agreement rest')
get_agreement(annotations_removed)

analyze pairs_contradictions
Discarded 655.0 annotations.
Found 13633 clean annotations.
Round 3283 to remove.

agreement clean
Krippendorff's alpha: 0.34099930456831007
Proportional agreement (pairwise): 0.7022918102658329

agreement rest
Krippendorff's alpha: 0.08464996553294202
Proportional agreement (pairwise): 0.40217438573602804

analyze worker_contradictions
Discarded 655.0 annotations.
Found 6774 clean annotations.
Round 10100 to remove.

agreement clean
Krippendorff's alpha: 0.34138322343219396
Proportional agreement (pairwise): 0.6879524284198786

agreement rest
Krippendorff's alpha: 0.22305174148170004
Proportional agreement (pairwise): 0.6155764495684004

analyze worker_checks
Discarded 655.0 annotations.
Found 14345 clean annotations.
Round 2529 to remove.

agreement clean
Krippendorff's alpha: 0.3004942691037146
Proportional agreement (pairwise): 0.6671261731478569

agreement rest
Krippendorff's alpha: 0.11758340511071363
Proportional agreement (pairwise): 0.47452206698530147