# Annotation analysis

This noteboook

* illustrates the steps of the analysis currently implemented
* is used to analyze and monitor workers batch by batch

In [1]:
from load_data import load_experiment_data
from analyze_workers import get_worker_analysis
from analyze_pairs import get_pair_analysis
from analyze_pairs import show_pairs_of_worker
from analyze_pairs import compare_runs
from calculate_iaa import get_agreement
from clean_annotations import clean_annotations
from analyze_relations_and_examples import agreement_relations_across_runs

# Analyze worker contradictions:

* Workers with highest contradiction to annotations ratio appear on top
* use the pandas dataframe sort method to sort on other values: 

`df.sort_values(by, axis=0, ascending=True, inplace=False, kind='quicksort', na_position='last')`

### Current batch

In [32]:
run = 3
batch = 55
n_q = '*'
group = 'experiment1'

data_dict_list = load_experiment_data(run, group, n_q, batch, remove_not_val = True)
name = f'run{run}-group_{group}-batch{batch}'.replace('*', '-all-')
df, filepath = get_worker_analysis(data_dict_list, name)
df.drop(['annotations'], axis = 1, inplace=True)
df

Discarded 0.0 annotations.

,workerid,n_annotations,n_contradictions,n_fails,contradiction_annotation_ratio,fail_annotation_ratio,average_time_question,"(afforded_unusual, unusual)","(afforded_unusual, rare)","(implied_category, rare)",...,"(afforded_usual, unusual)","(typical_of_property, unusual)","(afforded_unusual, impossible)","(rare, typical_of_property)","(afforded_usual, rare)","(impossible, typical_of_property)","(afforded_usual, impossible)","(affording_activity, unusual)","(affording_activity, impossible)","(affording_activity, rare)"
4,5ca0ab3d073bc1001209fd58,64,33,1,0.515625,0.015625,3.446672,1.0,1.0,1.0,...,1.0,3.0,1.0,1.0,1.0,3.0,1.0,2.0,2.0,1.0
2,5c93cb4bdcad2e00188b365f,64,12,1,0.187500,0.015625,3.946109,NaN,NaN,NaN,...,1.0,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9,5e5e623737be5e1762ad4418,64,10,1,0.156250,0.015625,12.582500,2.0,2.0,2.0,...,NaN,NaN,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,5bffa07fa1f05000010293b8,64,8,1,0.125000,0.015625,6.981719,2.0,2.0,2.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
0,5ad8affa4efee10001f537fd,64,6,1,0.093750,0.015625,11.608844,2.0,2.0,1.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,5c9b5a2635a4f1001514e5c8,64,4,1,0.062500,0.015625,8.862422,2.0,NaN,NaN,...,NaN,NaN,2.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,5ca48daf8572ee001230b11c,64,2,1,0.031250,0.015625,10.378687,NaN,1.0,1.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8,5e8a398a0b33b46e98edd73b,64,2,1,0.031250,0.015625,8.000250,NaN,1.0,1.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,5dc5c8cfb1dabb44812d5f1d,64,0,1,0.000000,0.015625,12.332625,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7,5e33190a5a41122e93c40989,64,0,1,0.000000,0.015625,7.259625,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

### All annotations

* Workers with highest contradiction to annotations ratio appear on top
* use the pandas dataframe sort method to sort on other values: 
* Check how the behavior of a specific worker with many contradictions compares to other workers

`df.sort_values(by, axis=0, ascending=True, inplace=False, kind='quicksort', na_position='last')`

In [14]:
run = '*'
batch = '*'
n_q = '*'
group = 'experiment1'

data_dict_list = load_experiment_data(run, group, n_q, batch, remove_not_val = True)
name = f'run{run}-group_{group}-batch{batch}'.replace('*', '-all-')
df_total, filepath = get_worker_analysis(data_dict_list, name)
df_total.drop(['annotations'], axis = 1, inplace=True)
df_total[:10]

Discarded 655.0 annotations.

,workerid,n_annotations,n_contradictions,n_fails,contradiction_annotation_ratio,fail_annotation_ratio,average_time_question,"(afforded_unusual, unusual)","(typical_of_property, unusual)","(implied_category, unusual)",...,"(implied_category, impossible)","(affording_activity, impossible)","(afforded_unusual, impossible)","(afforded_usual, impossible)","(implied_category, rare)","(rare, typical_of_concept)","(rare, typical_of_property)","(afforded_unusual, rare)","(afforded_usual, rare)","(affording_activity, rare)"
298,5bfed16ca1f050000102693c,74,62,1,0.837838,0.013514,14.382986,3.0,4.0,4.0,...,4.0,NaN,4.0,5.0,3.0,4.0,4.0,3.0,4.0,NaN
425,5e87276d17cdf1028850af59,72,54,1,0.750000,0.013889,2.828292,4.0,4.0,6.0,...,5.0,NaN,4.0,2.0,5.0,2.0,3.0,3.0,3.0,NaN
504,5c042ba4bb85e60001c05c83,72,47,0,0.652778,0.000000,7.812292,1.0,3.0,5.0,...,3.0,1.0,1.0,2.0,6.0,4.0,3.0,2.0,2.0,3.0
764,5d76a2dc2a476a0001ce6843,72,45,1,0.625000,0.013889,16.482319,NaN,3.0,5.0,...,3.0,2.0,NaN,NaN,5.0,5.0,3.0,NaN,NaN,5.0
377,IT Manager,72,44,2,0.611111,0.027778,0.000000,4.0,3.0,3.0,...,3.0,1.0,3.0,2.0,2.0,1.0,3.0,4.0,3.0,2.0
421,5d4c5e4baf102c001a385bf0,72,43,0,0.597222,0.000000,10.631083,2.0,3.0,4.0,...,4.0,NaN,3.0,4.0,2.0,1.0,3.0,2.0,3.0,NaN
392,5e4e86b070e1ed2d6e4e3f62,72,42,1,0.583333,0.013889,4.293264,NaN,5.0,5.0,...,2.0,1.0,NaN,NaN,5.0,4.0,5.0,NaN,NaN,4.0
397,5e7cbbbcf0a5a004b60b48f7,72,41,1,0.569444,0.013889,11.482222,NaN,2.0,1.0,...,4.0,4.0,NaN,NaN,5.0,4.0,6.0,NaN,NaN,6.0
599,5d7a5163c1f9be0001e4f891,72,40,2,0.555556,0.027778,11.160347,2.0,3.0,3.0,...,1.0,1.0,1.0,2.0,3.0,4.0,3.0,1.0,3.0,2.0
290,5d323affa754dc00018b15cc,150,82,3,0.546667,0.020000,17.685089,6.0,6.0,5.0,...,5.0,1.0,5.0,5.0,4.0,5.0,5.0,5.0,5.0,NaN

In [4]:
# Good workers
#df[-20:]

### Get all contradictions and fails of a particular worker 

* Check if a specfic worker continuously contradicts themselves (and fails checks)

In [35]:
# copy from above - worker with many disagreements in target batch
worker = '5e33190a5a41122e93c40989'


# df.loc[df['column_name'] == some_value]
df_total.loc[df_total['workerid'] == worker]

,workerid,n_annotations,n_contradictions,n_fails,contradiction_annotation_ratio,fail_annotation_ratio,average_time_question,"(afforded_unusual, unusual)","(typical_of_property, unusual)","(implied_category, unusual)",...,"(implied_category, impossible)","(affording_activity, impossible)","(afforded_unusual, impossible)","(afforded_usual, impossible)","(implied_category, rare)","(rare, typical_of_concept)","(rare, typical_of_property)","(afforded_unusual, rare)","(afforded_usual, rare)","(affording_activity, rare)"
480,5e33190a5a41122e93c40989,64,0,1,0.0,0.015625,7.259625,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

# Analyze pairs

* compars number of annotator contradictions among pairs

### Current batch:

In [24]:
run = '3'
batch = '56'
n_q = '*'
group = 'experiment1'

data_dict_list = load_experiment_data(run, group, n_q, batch, remove_not_val = True)
name = f'run{run}-group_{group}-batch{batch}'.replace('*', '-all-')
df, filepath = get_pair_analysis(data_dict_list, name)
df.drop(['annotations_with_contradiction'], axis = 1, inplace=True)
df

Discarded 0.0 annotations.

,pair,n_annotations,n_workers,n_contradictions,n_workers_contradicting,ratio_workers_contradicting,contradiction_annotation_ratio,average_time_pair,workers_contradicting,workers_not_contradicting,...,"(implied_category, rare)","(afforded_usual, rare)","(afforded_usual, unusual)","(afforded_unusual, rare)","(rare, typical_of_property)","(afforded_unusual, unusual)","(typical_of_property, unusual)","(afforded_usual, impossible)","(afforded_unusual, impossible)","(rare, typical_of_concept)"
6,roll-leather,90,9,40,7,0.777778,0.444444,63.183289,5a280bb2e2d20d000132093e 5b943acc6adb260001906...,5c93cb4bdcad2e00188b365f 5dc5c8cfb1dabb44812d5f1d,...,1.0,1.0,3.0,4.0,2.0,6.0,4.0,3.0,3.0,1.0
4,roll-horseshoe,90,9,38,8,0.888889,0.422222,63.183289,5a280bb2e2d20d000132093e 5b943acc6adb260001906...,5c93cb4bdcad2e00188b365f,...,3.0,NaN,NaN,6.0,2.0,5.0,3.0,1.0,4.0,2.0
1,roll-shovel,90,9,36,8,0.888889,0.400000,63.183289,5a280bb2e2d20d000132093e 5b943acc6adb260001906...,5c93cb4bdcad2e00188b365f,...,3.0,3.0,3.0,4.0,1.0,5.0,2.0,3.0,3.0,NaN
2,roll-gearshift,90,9,34,8,0.888889,0.377778,63.183289,5a280bb2e2d20d000132093e 5b943acc6adb260001906...,5dc5c8cfb1dabb44812d5f1d,...,3.0,4.0,2.0,4.0,1.0,3.0,2.0,3.0,3.0,NaN
5,roll-projectile,90,9,24,6,0.666667,0.266667,63.183289,5a280bb2e2d20d000132093e 5b943acc6adb260001906...,5c93cb4bdcad2e00188b365f 5d7d0cc0e32539001a174...,...,1.0,1.0,1.0,2.0,1.0,3.0,2.0,1.0,2.0,1.0
3,roll-donkey,90,9,22,6,0.666667,0.244444,63.183289,5a280bb2e2d20d000132093e 5cdbda89561ebb0019d97...,5b943acc6adb26000190694d 5c93cb4bdcad2e00188b3...,...,NaN,1.0,NaN,3.0,1.0,3.0,NaN,1.0,4.0,NaN
0,red-watermelon,90,9,10,4,0.444444,0.111111,63.183289,5a280bb2e2d20d000132093e 5c93cb4bdcad2e00188b3...,5b943acc6adb26000190694d 5cdbda89561ebb0019d97...,...,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7,_check3-_check3,9,9,0,0,0.000000,0.000000,631.832889,,5a280bb2e2d20d000132093e 5b943acc6adb260001906...,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8,_test3-_test,9,9,0,0,0.000000,0.000000,631.832889,,5a280bb2e2d20d000132093e 5b943acc6adb260001906...,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

### Get rows with pairs annotated by specific workers:

* Check if a worker in the only one contradicting or if others also had issues with the pairs

In [25]:
worker = '5d7d0cc0e32539001a174642'

show_pairs_of_worker(worker, df)

Worker 5d7d0cc0e32539001a174642 contradicted themselves in the following pairs:

roll-leather 	 total workers contradicting themselves: 7
roll-horseshoe 	 total workers contradicting themselves: 8
roll-shovel 	 total workers contradicting themselves: 8
roll-gearshift 	 total workers contradicting themselves: 8
roll-donkey 	 total workers contradicting themselves: 6

### Compare to entire annotation set

In [7]:
run = '*'
batch = '*'
n_q = '*'
group = 'experiment1'

data_dict_list = load_experiment_data(run, group, n_q, batch, remove_not_val = True)
name = f'run{run}-group_{group}-batch{batch}'.replace('*', '-all-')
df, filepath = get_pair_analysis(data_dict_list, name)
df.drop(['annotations_with_contradiction'], axis = 1, inplace=True)
df

Discarded 655.0 annotations.

,pair,n_annotations,n_workers,n_contradictions,n_workers_contradicting,ratio_workers_contradicting,contradiction_annotation_ratio,average_time_pair,workers_contradicting,workers_not_contradicting,...,"(afforded_unusual, impossible)","(typical_of_property, unusual)","(rare, typical_of_property)","(afforded_usual, rare)","(impossible, typical_of_property)","(afforded_usual, impossible)","(affording_activity, rare)","(affording_activity, unusual)","(rare, typical_of_concept)","(affording_activity, impossible)"
95,roll-horseshoe,140,14,50,11,0.785714,0.357143,66.567100,5b994a6d700b020001c572e2 5de4e06be4f42a477cdbb...,5bce0e9e48473300014cafca 5d134f52f1341200164f9...,...,6.0,4.0,2.0,NaN,4.0,2.0,NaN,NaN,2.0,NaN
312,roll-leather,141,14,48,10,0.714286,0.340426,111.016862,5d362118bd3f570016067a6b 5de5157820c5aa09b7a53...,5d40128e2b6eaf00155f222c 5de67b36610fba5ef7b86...,...,6.0,4.0,2.0,1.0,4.0,3.0,NaN,NaN,1.0,NaN
26,roll-spindle,150,15,48,10,0.666667,0.320000,75.754453,5dc0395f2a1dd64710661ccd 5ddc56fbf290e7bbfa964...,5de6be6912bcf6041b3276ba 589cc7bd8bf22a00015b7...,...,3.0,4.0,3.0,2.0,3.0,3.0,NaN,NaN,1.0,NaN
208,roll-washer,150,15,46,11,0.733333,0.306667,72.499607,5bbbc0f56322c500015a53a1 5bf077d95fc1db0001305...,5aad5d5a917b3b00010d42a1 5b83c47e67b3b70001915...,...,2.0,5.0,1.0,2.0,1.0,2.0,NaN,NaN,1.0,NaN
87,roll-dowel,149,15,45,11,0.733333,0.302013,56.773827,5b281303007d870001c7f24a 5c097af754deae0001ac6...,5cfa90ccd128950001311ed0 5d598dff48766d0001949...,...,NaN,2.0,2.0,4.0,1.0,3.0,NaN,NaN,3.0,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
216,round-pen,95,15,0,0,0.000000,0.000000,128.238483,,5b8d575aafe6be000115695b 5d667b2ac25c160001b0a...,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
265,round-football,50,5,0,0,0.000000,0.000000,85.898220,,5ad90f90dec767000128a5f4 5aeded8f0ccc2e0001858...,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
215,red-blueberry,55,15,0,0,0.000000,0.000000,216.265611,,5aad5d5a917b3b00010d42a1 5b83c47e67b3b70001915...,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
404,red-ant,102,16,0,0,0.000000,0.000000,114.361622,,5ba797ad7c0ebe000127092a 5bb202b18aba5700017f3...,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
140,round-bowl,95,15,0,0,0.000000,0.000000,116.375259,,592bdd896489ca00013b3fcf 5a0feb37df3fa800015c4...,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [10]:
# check specific pair:

pair = 'red-lipstick'
df.loc[df['pair'] == pair]

,pair,n_annotations,n_workers,n_contradictions,n_workers_contradicting,ratio_workers_contradicting,contradiction_annotation_ratio,average_time_pair,workers_contradicting,workers_not_contradicting,...,"(affording_activity, unusual)","(rare, typical_of_concept)","(rare, typical_of_property)","(implied_category, rare)","(implied_category, impossible)","(affording_activity, impossible)","(afforded_unusual, impossible)","(afforded_usual, rare)","(afforded_unusual, rare)","(afforded_usual, impossible)"
305,red-lipstick,50,5,7,2,0.4,0.14,59.799,57617fdb1a5ecc0006fc3860 5ddc0d87d3ac2ad102aff2b9,59dc2e2016ecc200016fea95 5c544985be9cd80001156...,...,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

### Compare contradictions between runs:

In [8]:
run = '1'
batch = '*'
n_q = '*'
group = 'experiment1'

data_dict_list = load_experiment_data(run, group, n_q, batch, remove_not_val = True)
name = f'run{run}-group_{group}-batch{batch}'.replace('*', '-all-')
df1, filepath = get_pair_analysis(data_dict_list, name)
print(f'analysis can be found at: {filepath}')

run = '3'
batch = '*'
n_q = '*'
group = 'experiment1'

data_dict_list = load_experiment_data(run, group, n_q, batch, remove_not_val = True)
name = f'run{run}-group_{group}-batch{batch}'.replace('*', '-all-')
df2, filepath = get_pair_analysis(data_dict_list, name)
print(f'analysis can be found at: {filepath}')

name1 = '1'
name2 = '3'
compare_runs(name1, name2, df1, df2, comp = 'all')
print()
compare_runs(name1, name2, df1, df2, comp = 'pairs')

Discarded 0.0 annotations.
analysis can be found at: ../analyses/pairs/run1-group_experiment1-batch-all-.csv
Discarded 655.0 annotations.
analysis can be found at: ../analyses/pairs/run3-group_experiment1-batch-all-.csv
Set 1 as a contradiction ratio of 0.26912294753704447
Set 3 as a contradiction ratio of 0.2489402697495183
The ratio is based on the number of workers annotating a pair.
A worker always annotates a full set.

Set 1 as a contradiction ratio of 0.26755852842809363
Set 3 as a contradiction ratio of 0.2754320717567272
The ratio is based on the number of workers annotating a pair.
A worker always annotates a full set.
This analysis only includes pairs annotated in run 1 and run 3.

(0.26755852842809363, 0.2754320717567272)

# Inter-annotator agreement

* Total agreement
* Agreement by relations
* agreement after removing annotators with many contradictions/annotators who fail checks/contradictory annotations

## Total iaa:

In [9]:
run = '3'
batch = '*'
n_q = '*'
group = 'experiment1'
print(f"Run {run}:")
data_dict_list = load_experiment_data(run, group, n_q, batch, remove_not_val = True)
get_agreement(data_dict_list)

run = '1'
batch = '*'
n_q = '*'
group = 'experiment1'
print(f"Run {run}:")
data_dict_list = load_experiment_data(run, group, n_q, batch, remove_not_val = True)

get_agreement(data_dict_list)

Run 3:
Discarded 655.0 annotations.
Krippendorff's alpha: 0.23025005912852226
Proportional agreement (pairwise): 0.6278668020788083

Run 1:
Discarded 0.0 annotations.
Krippendorff's alpha: 0.2413329996998821
Proportional agreement (pairwise): 0.6204625909422005

{'Krippendorff': 0.2413329996998821, 'Proportional': 0.6204625909422005}

## IAA of collapsed relations

In [11]:
run = '3'
batch = '*'
n_q = '*'
group = 'experiment1'
print(f"Run {run}:")
data_dict_list = load_experiment_data(run, group, n_q, batch, remove_not_val = True)
get_agreement(data_dict_list)

collapse_relations = 'pos_neg'
print(f'collapsing {collapse_relations}')
get_agreement(data_dict_list, collapse_relations = collapse_relations)

collapse_relations = 'levels'
print(f'collapsing {collapse_relations}')
get_agreement(data_dict_list, collapse_relations = collapse_relations)

collapse_relations = 'similar_relations'
print(f'collapsing {collapse_relations}')
get_agreement(data_dict_list, collapse_relations = collapse_relations)


run = '1'
batch = '*'
n_q = '*'
group = 'experiment1'
print(f"Run {run}:")
data_dict_list = load_experiment_data(run, group, n_q, batch, remove_not_val = True)
get_agreement(data_dict_list)

collapse_relations = 'pos_neg'
print(f'collapsing {collapse_relations}')
get_agreement(data_dict_list, collapse_relations = collapse_relations)

collapse_relations = 'levels'
print(f'collapsing {collapse_relations}')
get_agreement(data_dict_list, collapse_relations = collapse_relations)

collapse_relations = 'similar_relations'
print(f'collapsing {collapse_relations}')
get_agreement(data_dict_list, collapse_relations = collapse_relations)

Run 3:
Discarded 655.0 annotations.
Krippendorff's alpha: 0.23025005912852226
Proportional agreement (pairwise): 0.6278668020788083

collapsing pos_neg
pos_neg
Krippendorff's alpha: 0.27756552643968013
Proportional agreement (pairwise): 0.7741680282541057

collapsing levels
levels
Krippendorff's alpha: 0.3350593790692973
Proportional agreement (pairwise): 0.684251616474486

collapsing similar_relations
similar_relations
Krippendorff's alpha: 0.3618095029088817
Proportional agreement (pairwise): 0.6833857466264721

Run 1:
Discarded 0.0 annotations.
Krippendorff's alpha: 0.2413329996998821
Proportional agreement (pairwise): 0.6204625909422005

collapsing pos_neg
pos_neg
Krippendorff's alpha: 0.42075917589059175
Proportional agreement (pairwise): 0.7928260904709381

collapsing levels
levels
Krippendorff's alpha: 0.4043412769447291
Proportional agreement (pairwise): 0.7139476347066023

collapsing similar_relations
similar_relations
Krippendorff's alpha: 0.41176179025339876
Proportional agreement (pairwise): 0.7027721648280387

{'Krippendorff': 0.41176179025339876, 'Proportional': 0.7027721648280387}

## IAA by relation

In [12]:
runs = ['3', '1']
experiment_name = 'experiment1'
path, df = agreement_relations_across_runs(runs, experiment_name)
print(f'Results written to: {path}')
df

Discarded 655.0 annotations.
Discarded 0.0 annotations.
Results written to: ../analyses/iaa/relations_runs3-1.csv

,relation,3_Krippendorff,3_Proportional,1_Krippendorff,1_Proportional
0,implied_category,0.261604,0.648495,0.260459,0.629956
1,affording_activity,0.196837,0.654605,0.149149,0.672259
2,variability_subcategories,NaN,NaN,0.157270,0.579637
3,impossible,0.134907,0.658426,0.183925,0.679565
4,variability_limited,0.103003,0.551718,0.197795,0.599990
5,afforded_usual,0.172981,0.644417,0.336767,0.698580
6,typical_of_property,0.231757,0.755240,0.326482,0.682547
7,creative,0.059688,0.544502,0.040020,0.524894
8,rare,0.132488,0.576444,NaN,NaN
9,typical_of_concept,0.311785,0.712881,0.367910,0.689440
10,afforded_unusual,0.068180,0.544889,0.108460,0.557623
11,test_true,0.045786,0.794077,NaN,NaN
12,_check,0.606292,0.884235,0.904637,0.964443
13,test_false,0.258187,0.702768,NaN,NaN
14,unusual,0.159998,0.576699,0.120147,0.561644
15,variability_open,0.214621,0.606366,0.143751,0.580081

## Agreement after removing workers or annotations:

In [32]:
run = '3'
batch = '*'
n_q = '*'
group = 'experiment1'

print('Total Agreement')
data_dict_list = load_experiment_data(run, group, n_q, batch, remove_not_val = True)
get_agreement(data_dict_list)
print('-------')
print()

print('Removing pair annotations with many contradictions:')
category = 'pairs_contradictions'
print(f'analyze {category}')
annotations_clean, annotations_removed = clean_annotations(run, group, n_q, batch, category)
print('agreement clean')
get_agreement(annotations_clean)
#print('agreement rest')
#get_agreement(annotations_removed)


category = 'worker_contradictions'
print(f'analyze {category}')
annotations_clean, annotations_removed = clean_annotations(run, group, n_q, batch, category)
print('agreement clean')
get_agreement(annotations_clean)
#print('agreement rest')
#get_agreement(annotations_removed)
print()

category = 'worker_checks'
print(f'analyze {category}')
annotations_clean, annotations_removed = clean_annotations(run, group, n_q, batch, category)
print('agreement clean')
get_agreement(annotations_clean)
#print('agreement rest')
#get_agreement(annotations_removed)

Total Agreement
Discarded 655.0 annotations.
Krippendorff's alpha: 0.23336207839907597
Proportional agreement (pairwise): 0.6304754199128316

-------

Removing pair annotations with many contradictions:
analyze pairs_contradictions
Discarded 655.0 annotations.
Found 24827 clean annotations.
Round 10212 to remove.

agreement clean
Krippendorff's alpha: 0.33405102479157067
Proportional agreement (pairwise): 0.68651450192071

analyze worker_contradictions
Discarded 655.0 annotations.
Found 24877 clean annotations.
Round 10100 to remove.

agreement clean
Krippendorff's alpha: 0.24953378047207264
Proportional agreement (pairwise): 0.6498735089301452


analyze worker_checks
Discarded 655.0 annotations.
Found 32448 clean annotations.
Round 2529 to remove.

agreement clean
Krippendorff's alpha: 0.25028983009201133
Proportional agreement (pairwise): 0.639896601266422

{'Krippendorff': 0.25028983009201133, 'Proportional': 0.639896601266422}