# Annotation analysis

This noteboook

* illustrates the steps of the analysis currently implemented
* is used to analyze and monitor workers batch by batch

In [4]:
from load_data import load_experiment_data
from analyze_workers import get_worker_analysis
from analyze_pairs import get_pair_analysis
from analyze_pairs import show_pairs_of_worker
from analyze_pairs import compare_runs
from calculate_iaa import get_agreement
from clean_annotations import clean_annotations

# Analyze worker contradictions:

* Workers with highest contradiction to annotations ratio appear on top
* use the pandas dataframe sort method to sort on other values: 

`df.sort_values(by, axis=0, ascending=True, inplace=False, kind='quicksort', na_position='last')`

### Current batch

In [6]:
run = 3
batch = 25
n_q = 70
group = 'experiment1'

data_dict_list = load_experiment_data(run, group, n_q, batch, remove_not_val = True)
name = f'run{run}-group_{group}-batch{batch}'.replace('*', '-all-')
df, filepath = get_worker_analysis(data_dict_list, name)
df.drop(['annotations'], axis = 1, inplace=True)
df

creating file with uuid run3-group_experiment1/qu70-s_qu70-batch25.csv
added unique ids - file can be found at: ../data/prolific_output_uuid/run3-group_experiment1/qu70-s_qu70-batch25.csv
Discarded 0.0 annotations.

,workerid,n_annotations,n_contradictions,n_fails,contradiction_annotation_ratio,fail_annotation_ratio,average_time_question,"(implied_category, unusual)","(affording_activity, rare)","(affording_activity, unusual)",...,"(typical_of_concept, unusual)","(implied_category, impossible)","(impossible, typical_of_concept)","(afforded_usual, unusual)","(rare, typical_of_property)","(typical_of_property, unusual)","(afforded_usual, rare)","(impossible, typical_of_property)","(afforded_usual, impossible)","(affording_activity, impossible)"
1,5beca582fcb5fe0001259b1e,72,24,1,0.333333,0.013889,8.454736,6.0,1.0,2.0,...,3.0,2.0,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,5d494d958e0dc5001a99a392,72,15,0,0.208333,0.000000,13.496722,2.0,NaN,NaN,...,1.0,NaN,NaN,1.0,1.0,2.0,1.0,2.0,NaN,NaN
4,5d87958fa509900001580d88,72,9,1,0.125000,0.013889,10.251208,NaN,NaN,NaN,...,NaN,1.0,1.0,NaN,NaN,NaN,NaN,1.0,1.0,1.0
0,59edc6eceae741000111afb8,72,8,1,0.111111,0.013889,8.050917,1.0,2.0,2.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,5cb883db4e440300010f602c,72,8,1,0.111111,0.013889,8.626083,2.0,NaN,NaN,...,1.0,NaN,NaN,1.0,NaN,NaN,NaN,NaN,NaN,NaN
5,5e79e4e83d839d0009c76b09,72,6,1,0.083333,0.013889,10.688514,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7,5e7cd4f79bebe5330d0234d6,72,4,1,0.055556,0.013889,10.204917,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,5e7bb30e3f9fe31d223a0f04,72,3,1,0.041667,0.013889,11.110153,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9,5e8423ef51b53b187eee0c69,72,3,1,0.041667,0.013889,10.905625,1.0,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8,5e80ee7f1de315011aa4592d,74,3,1,0.040541,0.013514,23.820432,NaN,NaN,NaN,...,NaN,NaN,NaN,1.0,NaN,NaN,1.0,NaN,1.0,NaN

### All annotations

* Workers with highest contradiction to annotations ratio appear on top
* use the pandas dataframe sort method to sort on other values: 
* Check how the behavior of a specific worker with many contradictions compares to other workers

`df.sort_values(by, axis=0, ascending=True, inplace=False, kind='quicksort', na_position='last')`

In [12]:
run = '*'
batch = '*'
n_q = '*'
group = 'experiment1'

data_dict_list = load_experiment_data(run, group, n_q, batch, remove_not_val = True)
name = f'run{run}-group_{group}-batch{batch}'.replace('*', '-all-')
df, filepath = get_worker_analysis(data_dict_list, name)
df.drop(['annotations'], axis = 1, inplace=True)
df[:10]

Discarded 655.0 annotations.

,workerid,n_annotations,n_contradictions,n_fails,contradiction_annotation_ratio,fail_annotation_ratio,average_time_question,"(afforded_unusual, unusual)","(typical_of_property, unusual)","(implied_category, unusual)",...,"(implied_category, impossible)","(affording_activity, impossible)","(afforded_unusual, impossible)","(afforded_usual, impossible)","(implied_category, rare)","(rare, typical_of_concept)","(rare, typical_of_property)","(affording_activity, rare)","(afforded_unusual, rare)","(afforded_usual, rare)"
512,5d76a2dc2a476a0001ce6843,72,45,1,0.625000,0.013889,16.482319,NaN,3.0,5.0,...,3.0,2.0,NaN,NaN,5.0,5.0,3.0,5.0,NaN,NaN
289,5e4e86b070e1ed2d6e4e3f62,72,42,1,0.583333,0.013889,4.293264,NaN,5.0,5.0,...,2.0,1.0,NaN,NaN,5.0,4.0,5.0,4.0,NaN,NaN
294,5e7cbbbcf0a5a004b60b48f7,72,41,1,0.569444,0.013889,11.482222,NaN,2.0,1.0,...,4.0,4.0,NaN,NaN,5.0,4.0,6.0,6.0,NaN,NaN
241,5c91321c0375460001034cb8,71,38,0,0.535211,0.000000,12.942127,2.0,6.0,6.0,...,4.0,1.0,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
506,5e76ab49dec4562243b421f9,72,35,2,0.486111,0.027778,18.781028,NaN,3.0,2.0,...,2.0,3.0,NaN,NaN,2.0,4.0,3.0,4.0,NaN,NaN
305,5ba4f45c4286a00001ea457f,72,34,1,0.472222,0.013889,9.803042,NaN,4.0,4.0,...,2.0,2.0,NaN,NaN,3.0,2.0,3.0,3.0,NaN,NaN
15,5dc0395f2a1dd64710661ccd,71,33,0,0.464789,0.000000,3.745113,4.0,5.0,5.0,...,3.0,1.0,1.0,1.0,NaN,NaN,NaN,NaN,NaN,NaN
192,5d4434c68225f9001642fcd3,71,30,0,0.422535,0.000000,5.209535,1.0,4.0,4.0,...,3.0,3.0,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
187,5de8dc07f42a16000a301cd6,78,31,0,0.397436,0.000000,4.965808,2.0,5.0,5.0,...,3.0,1.0,1.0,1.0,NaN,NaN,NaN,NaN,NaN,NaN
71,599aca876b939900012da2cd,71,27,0,0.380282,0.000000,19.589310,1.0,6.0,7.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

### Get all disagreements and fails of a particular worker 

* Check if a specfic worker continuously contradicts themselves (and fails checks)

In [13]:
# copy from above - worker with many disagreements in target batch
worker = '5d494d958e0dc5001a99a392'

# df.loc[df['column_name'] == some_value]
df.loc[df['workerid'] == worker]

,workerid,n_annotations,n_contradictions,n_fails,contradiction_annotation_ratio,fail_annotation_ratio,average_time_question,"(afforded_unusual, unusual)","(typical_of_property, unusual)","(implied_category, unusual)",...,"(implied_category, impossible)","(affording_activity, impossible)","(afforded_unusual, impossible)","(afforded_usual, impossible)","(implied_category, rare)","(rare, typical_of_concept)","(rare, typical_of_property)","(affording_activity, rare)","(afforded_unusual, rare)","(afforded_usual, rare)"
355,5d494d958e0dc5001a99a392,72,15,0,0.208333,0.0,13.496722,1.0,2.0,2.0,...,NaN,NaN,NaN,NaN,2.0,1.0,1.0,NaN,1.0,1.0

# Analyze pairs

* compars number of annotator contradictions among pairs

### Current batch:

In [9]:
run = '3'
batch = '25'
n_q = '*'
group = 'experiment1'

data_dict_list = load_experiment_data(run, group, n_q, batch, remove_not_val = True)
name = f'run{run}-group_{group}-batch{batch}'.replace('*', '-all-')
df, filepath = get_pair_analysis(data_dict_list, name)
df.drop(['annotations_with_contradiction'], axis = 1, inplace=True)
df

Discarded 0.0 annotations.

,pair,n_annotations,n_workers,n_contradictions,n_workers_contradicting,ratio_workers_contradicting,contradiction_annotation_ratio,average_time_pair,workers_contradicting,workers_not_contradicting,...,"(typical_of_property, unusual)","(afforded_usual, rare)","(impossible, typical_of_property)","(implied_category, impossible)","(afforded_unusual, impossible)","(afforded_usual, impossible)","(impossible, typical_of_concept)","(affording_activity, unusual)","(affording_activity, impossible)","(affording_activity, rare)"
0,roll-sprocket,101,10,23,4,0.4,0.227723,82.112645,5beca582fcb5fe0001259b1e 5cb883db4e440300010f6...,59edc6eceae741000111afb8 5e79e4e83d839d0009c76...,...,1.0,1.0,1.0,1.0,1.0,1.0,1.0,NaN,NaN,NaN
6,roll-windshield,100,10,20,8,0.8,0.200000,83.715110,5beca582fcb5fe0001259b1e 5cb883db4e440300010f6...,59edc6eceae741000111afb8 5e8423ef51b53b187eee0c69,...,NaN,1.0,1.0,1.0,4.0,1.0,NaN,NaN,NaN,NaN
5,roll-tray,100,10,16,9,0.9,0.160000,83.715110,59edc6eceae741000111afb8 5beca582fcb5fe0001259...,5e80ee7f1de315011aa4592d,...,1.0,NaN,1.0,NaN,3.0,NaN,NaN,NaN,NaN,NaN
4,red-vinegar,100,10,8,3,0.3,0.080000,83.715110,59edc6eceae741000111afb8 5beca582fcb5fe0001259...,5cb883db4e440300010f602c 5d87958fa509900001580...,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.0,NaN,2.0
3,round-bean,100,10,6,3,0.3,0.060000,83.715110,59edc6eceae741000111afb8 5cb883db4e440300010f6...,5beca582fcb5fe0001259b1e 5d494d958e0dc5001a99a...,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,NaN,1.0
2,round-samosa,101,10,6,1,0.1,0.059406,82.112645,5beca582fcb5fe0001259b1e,59edc6eceae741000111afb8 5cb883db4e440300010f6...,...,NaN,NaN,NaN,1.0,NaN,NaN,1.0,NaN,NaN,NaN
1,red-vegetable,100,10,4,3,0.3,0.040000,83.715110,59edc6eceae741000111afb8 5beca582fcb5fe0001259...,5cb883db4e440300010f602c 5d494d958e0dc5001a99a...,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,1.0,NaN
7,_check1-_check1,10,10,0,0,0.0,0.000000,837.151100,,59edc6eceae741000111afb8 5beca582fcb5fe0001259...,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8,_test4-_test,10,10,0,0,0.0,0.000000,837.151100,,59edc6eceae741000111afb8 5beca582fcb5fe0001259...,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

### Get rows with pairs annotated by specific workers:

* Check if a worker in the only one contradicting or if others also had issues with the pairs

In [10]:
worker = '5beca582fcb5fe0001259b1e'

show_pairs_of_worker(worker, df)

Worker 5beca582fcb5fe0001259b1e contradicted themselves in the following pairs:

roll-sprocket 	 total workers contradicting themselves: 4
roll-windshield 	 total workers contradicting themselves: 8
roll-tray 	 total workers contradicting themselves: 9
red-vinegar 	 total workers contradicting themselves: 3
round-samosa 	 total workers contradicting themselves: 1
red-vegetable 	 total workers contradicting themselves: 3

### Compare to entire annotation set

In [7]:
run = '*'
batch = '*'
n_q = '*'
group = 'experiment1'

data_dict_list = load_experiment_data(run, group, n_q, batch, remove_not_val = True)
name = f'run{run}-group_{group}-batch{batch}'.replace('*', '-all-')
df, filepath = get_pair_analysis(data_dict_list, name)
df.drop(['annotations_with_contradiction'], axis = 1, inplace=True)
df

Discarded 655.0 annotations.

,pair,n_annotations,n_workers,n_contradictions,n_workers_contradicting,ratio_workers_contradicting,contradiction_annotation_ratio,average_time_pair,workers_contradicting,workers_not_contradicting,...,"(impossible, typical_of_property)","(implied_category, rare)","(rare, typical_of_property)","(affording_activity, unusual)","(implied_category, impossible)","(rare, typical_of_concept)","(affording_activity, impossible)","(afforded_unusual, impossible)","(afforded_usual, impossible)","(affording_activity, rare)"
26,roll-spindle,50,5,22,4,0.8,0.44,57.711660,5dc0395f2a1dd64710661ccd 5ddc56fbf290e7bbfa964...,5de6be6912bcf6041b3276ba,...,2.0,NaN,NaN,NaN,2.0,NaN,NaN,2.0,2.0,NaN
231,roll-bolt,50,5,21,5,1.0,0.42,85.335380,5acb5910e1546900019c413a 5c5758e9efe1550001dc3...,,...,1.0,NaN,NaN,NaN,NaN,NaN,NaN,1.0,1.0,NaN
23,roll-mandrel,50,5,21,5,1.0,0.42,57.711660,5dc0395f2a1dd64710661ccd 5ddc56fbf290e7bbfa964...,,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25,roll-pipe,50,5,19,4,0.8,0.38,57.711660,5dc0395f2a1dd64710661ccd 5ddc56fbf290e7bbfa964...,5de6d199a23d79000bf9aef9,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,1.0,NaN
227,roll-lamp,50,5,17,4,0.8,0.34,85.335380,5acb5910e1546900019c413a 5d3f14f66a8a4e0018c17...,5c5758e9efe1550001dc31b6,...,2.0,NaN,NaN,NaN,1.0,NaN,NaN,2.0,1.0,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
324,round-breadcrumb,50,5,0,0,0.0,0.00,53.131520,,5aed0f3823e2ca0001976444 5c590c02e66e510001ef0...,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
323,red-cat,142,15,0,0,0.0,0.00,70.430573,,5aed0f3823e2ca0001976444 5c590c02e66e510001ef0...,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
176,round-cream,50,5,0,0,0.0,0.00,23.563020,,59d3764946447f00011f0407 5a828ebeeea3d300016e5...,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
320,red-guava,50,5,0,0,0.0,0.00,53.131520,,5aed0f3823e2ca0001976444 5c590c02e66e510001ef0...,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
245,red-beet,35,5,0,0,0.0,0.00,93.395600,,5c8abb61e1b6910001b30615 5d8b0fb691f3e600016e6...,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

### Compare contradictions between runs:

In [17]:
run = '1'
batch = '*'
n_q = '*'
group = 'experiment1'

data_dict_list = load_experiment_data(run, group, n_q, batch, remove_not_val = True)
name = f'run{run}-group_{group}-batch{batch}'.replace('*', '-all-')
df1, filepath = get_pair_analysis(data_dict_list, name)
print(f'analysis can be found at: {filepath}')

run = '3'
batch = '*'
n_q = '*'
group = 'experiment1'

data_dict_list = load_experiment_data(run, group, n_q, batch, remove_not_val = True)
name = f'run{run}-group_{group}-batch{batch}'.replace('*', '-all-')
df2, filepath = get_pair_analysis(data_dict_list, name)
print(f'analysis can be found at: {filepath}')

name1 = '1'
name2 = '3'
compare_runs(name1, name2, df1, df2, comp = 'all')
print()
compare_runs(name1, name2, df1, df2, comp = 'pairs')

Discarded 0.0 annotations.
analysis can be found at: ../analyses/pairs/run1-group_experiment1-batch-all-.csv
Discarded 655.0 annotations.
analysis can be found at: ../analyses/pairs/run3-group_experiment1-batch-all-.csv
Set 1 as a contradiction ratio of 0.26912294753704447
Set 3 as a contradiction ratio of 0.1533487297921478
The ratio is based on the number of workers annotating a pair.
A worker always annotates a full set.

Set 1 as a contradiction ratio of 0.19137931034482758
Set 3 as a contradiction ratio of 0.170997920997921
The ratio is based on the number of workers annotating a pair.
A worker always annotates a full set.
This analysis only includes pairs annotated in run 1 and run 3.

(0.19137931034482758, 0.170997920997921)

# Inter-annotator agreement

Compare both runs in original version and version without annotations in which annotators contradict themselves:

In [9]:
run = '3'
batch = '18'
n_q = '*'
group = 'experiment1'
data_dict_list = load_experiment_data(run, group, n_q, batch, remove_not_val = True)

get_agreement(data_dict_list)

run = '1'
batch = '*'
n_q = '*'
group = 'experiment1'
data_dict_list = load_experiment_data(run, group, n_q, batch, remove_not_val = True)

get_agreement(data_dict_list)

Discarded 20.0 annotations.
Krippendorff's alpha: 0.2933511483129806
Proportional agreement (pairwise): 0.684330484330484

Discarded 0.0 annotations.
Krippendorff's alpha: 0.2413329996998821
Proportional agreement (pairwise): 0.6204625909422005

In [10]:
run = '1'
batch = '*'
n_q = '*'
group = 'experiment1'
data_dict_list = load_experiment_data(run, group, n_q, batch, remove_not_val = True)

get_agreement(data_dict_list)

Discarded 0.0 annotations.
Krippendorff's alpha: 0.2413329996998821
Proportional agreement (pairwise): 0.6204625909422005

In [11]:
run = '3'
batch = '*'
n_q = '*'
group = 'experiment1'

category = 'pairs_contradictions'
print(f'analyze {category}')
annotations_clean, annotations_removed = clean_annotations(run, group, n_q, batch, category)
print('agreement clean')
get_agreement(annotations_clean)
print('agreement rest')
get_agreement(annotations_removed)


category = 'worker_contradictions'
print(f'analyze {category}')
annotations_clean, annotations_removed = clean_annotations(run, group, n_q, batch, category)
print('agreement clean')
get_agreement(annotations_clean)
print('agreement rest')
get_agreement(annotations_removed)


category = 'worker_checks'
print(f'analyze {category}')
annotations_clean, annotations_removed = clean_annotations(run, group, n_q, batch, category)
print('agreement clean')
get_agreement(annotations_clean)
print('agreement rest')
get_agreement(annotations_removed)

analyze pairs_contradictions
Discarded 655.0 annotations.
Found 13633 clean annotations.
Round 3283 to remove.

agreement clean
Krippendorff's alpha: 0.34099930456831007
Proportional agreement (pairwise): 0.7022918102658329

agreement rest
Krippendorff's alpha: 0.08464996553294202
Proportional agreement (pairwise): 0.40217438573602804

analyze worker_contradictions
Discarded 655.0 annotations.
Found 6774 clean annotations.
Round 10100 to remove.

agreement clean
Krippendorff's alpha: 0.34138322343219396
Proportional agreement (pairwise): 0.6879524284198786

agreement rest
Krippendorff's alpha: 0.22305174148170004
Proportional agreement (pairwise): 0.6155764495684004

analyze worker_checks
Discarded 655.0 annotations.
Found 14345 clean annotations.
Round 2529 to remove.

agreement clean
Krippendorff's alpha: 0.3004942691037146
Proportional agreement (pairwise): 0.6671261731478569

agreement rest
Krippendorff's alpha: 0.11758340511071363
Proportional agreement (pairwise): 0.47452206698530147