# Annotation analysis

This noteboook

* illustrates the steps of the analysis currently implemented
* is used to analyze and monitor workers batch by batch

In [1]:
from load_data import load_experiment_data
from analyze_workers import get_worker_analysis
from analyze_pairs import get_pair_analysis
from analyze_pairs import show_pairs_of_worker
from analyze_pairs import compare_runs
from calculate_iaa import get_agreement
from clean_annotations import clean_annotations
from analyze_relations_and_examples import agreement_relations_across_runs

# Analyze worker contradictions:

* Workers with highest contradiction to annotations ratio appear on top
* use the pandas dataframe sort method to sort on other values: 

`df.sort_values(by, axis=0, ascending=True, inplace=False, kind='quicksort', na_position='last')`

### Current batch

In [17]:
run = 3
batch = 41
n_q = 70
group = 'experiment1'

data_dict_list = load_experiment_data(run, group, n_q, batch, remove_not_val = True)
name = f'run{run}-group_{group}-batch{batch}'.replace('*', '-all-')
df, filepath = get_worker_analysis(data_dict_list, name)
df.drop(['annotations'], axis = 1, inplace=True)
df

creating file with uuid run3-group_experiment1/qu70-s_qu70-batch41.csv
added unique ids - file can be found at: ../data/prolific_output_uuid/run3-group_experiment1/qu70-s_qu70-batch41.csv
Discarded 0.0 annotations.

,workerid,n_annotations,n_contradictions,n_fails,contradiction_annotation_ratio,fail_annotation_ratio,average_time_question,"(afforded_unusual, unusual)","(afforded_unusual, rare)","(implied_category, unusual)",...,"(affording_activity, impossible)","(implied_category, impossible)","(afforded_usual, unusual)","(afforded_usual, rare)","(typical_of_property, unusual)","(typical_of_concept, unusual)","(rare, typical_of_property)","(rare, typical_of_concept)","(affording_activity, unusual)","(afforded_unusual, impossible)"
4,5c91bad5be78b00016c8329e,72,15,0,0.208333,0.0,6.447722,NaN,NaN,3.0,...,NaN,1.0,2.0,1.0,2.0,1.0,1.0,1.0,1.0,NaN
7,5d683e0f4a933f0001ebca29,72,10,0,0.138889,0.0,5.591986,2.0,2.0,3.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9,5e874ce2a6b352069eae0aa2,72,9,0,0.125000,0.0,14.709069,1.0,1.0,2.0,...,NaN,NaN,NaN,NaN,1.0,1.0,NaN,NaN,1.0,1.0
3,5baf689c51dfa8000130f19f,72,6,0,0.083333,0.0,9.884681,NaN,1.0,1.0,...,1.0,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8,5e8523df36bc6310a69ab92b,72,5,0,0.069444,0.0,18.917458,1.0,NaN,2.0,...,NaN,NaN,NaN,NaN,NaN,1.0,NaN,NaN,NaN,NaN
5,5cd2cfecf03d540016cbc0a9,72,3,0,0.041667,0.0,10.605208,1.0,1.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,5d0109dda3e75f001786296c,72,3,0,0.041667,0.0,7.492306,1.0,1.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0
2,5b222aff59f9620001c109cb,72,2,0,0.027778,0.0,15.668403,1.0,1.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
0,56b8dc21e1d0a2000c15d4b7,72,0,0,0.000000,0.0,9.077514,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,5a82ca84000dab00018c85cf,72,0,0,0.000000,0.0,10.702028,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

### All annotations

* Workers with highest contradiction to annotations ratio appear on top
* use the pandas dataframe sort method to sort on other values: 
* Check how the behavior of a specific worker with many contradictions compares to other workers

`df.sort_values(by, axis=0, ascending=True, inplace=False, kind='quicksort', na_position='last')`

In [32]:
run = '*'
batch = '*'
n_q = '*'
group = 'experiment1'

data_dict_list = load_experiment_data(run, group, n_q, batch, remove_not_val = True)
name = f'run{run}-group_{group}-batch{batch}'.replace('*', '-all-')
df, filepath = get_worker_analysis(data_dict_list, name)
df.drop(['annotations'], axis = 1, inplace=True)
df[:10]

Discarded 655.0 annotations.

,workerid,n_annotations,n_contradictions,n_fails,contradiction_annotation_ratio,fail_annotation_ratio,average_time_question,"(afforded_unusual, unusual)","(typical_of_property, unusual)","(implied_category, unusual)",...,"(implied_category, impossible)","(affording_activity, impossible)","(afforded_unusual, impossible)","(afforded_usual, impossible)","(implied_category, rare)","(rare, typical_of_concept)","(rare, typical_of_property)","(afforded_usual, rare)","(afforded_unusual, rare)","(affording_activity, rare)"
400,5c042ba4bb85e60001c05c83,72,47,0,0.652778,0.000000,7.812292,1.0,3.0,5.0,...,3.0,1.0,1.0,2.0,6.0,4.0,3.0,2.0,2.0,3.0
648,5d76a2dc2a476a0001ce6843,72,45,1,0.625000,0.013889,16.482319,NaN,3.0,5.0,...,3.0,2.0,NaN,NaN,5.0,5.0,3.0,NaN,NaN,5.0
315,5e4e86b070e1ed2d6e4e3f62,72,42,1,0.583333,0.013889,4.293264,NaN,5.0,5.0,...,2.0,1.0,NaN,NaN,5.0,4.0,5.0,NaN,NaN,4.0
320,5e7cbbbcf0a5a004b60b48f7,72,41,1,0.569444,0.013889,11.482222,NaN,2.0,1.0,...,4.0,4.0,NaN,NaN,5.0,4.0,6.0,NaN,NaN,6.0
419,5c1f3a7c10677f0001da2157,72,39,0,0.541667,0.000000,9.921528,3.0,5.0,5.0,...,1.0,1.0,1.0,1.0,3.0,1.0,4.0,1.0,2.0,1.0
241,5c91321c0375460001034cb8,71,38,0,0.535211,0.000000,12.942127,2.0,6.0,6.0,...,4.0,1.0,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
364,5ddd128c961cb3c6780ff181,72,36,0,0.500000,0.000000,8.403056,2.0,2.0,5.0,...,3.0,2.0,1.0,NaN,4.0,3.0,1.0,NaN,2.0,1.0
642,5e76ab49dec4562243b421f9,72,35,2,0.486111,0.027778,18.781028,NaN,3.0,2.0,...,2.0,3.0,NaN,NaN,2.0,4.0,3.0,NaN,NaN,4.0
297,5c8831d20d005a00131367d3,72,35,0,0.486111,0.000000,16.026153,1.0,3.0,4.0,...,2.0,2.0,NaN,NaN,4.0,2.0,2.0,1.0,1.0,3.0
341,5ba4f45c4286a00001ea457f,72,34,1,0.472222,0.013889,9.803042,NaN,4.0,4.0,...,2.0,2.0,NaN,NaN,3.0,2.0,3.0,NaN,NaN,3.0

In [33]:
# Good workers
df[-200:-150:]

,workerid,n_annotations,n_contradictions,n_fails,contradiction_annotation_ratio,fail_annotation_ratio,average_time_question,"(afforded_unusual, unusual)","(typical_of_property, unusual)","(implied_category, unusual)",...,"(implied_category, impossible)","(affording_activity, impossible)","(afforded_unusual, impossible)","(afforded_usual, impossible)","(implied_category, rare)","(rare, typical_of_concept)","(rare, typical_of_property)","(afforded_usual, rare)","(afforded_unusual, rare)","(affording_activity, rare)"
154,5ce4db1f65cce3000166882d,71,1,0,0.014085,0.000000,8.306775,1.0,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
259,5d8e45a7d89bf800136c78e1,71,1,0,0.014085,0.000000,13.005620,NaN,NaN,NaN,...,NaN,NaN,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
116,5b2e41eb1d2f710001fb32db,142,2,0,0.014085,0.000000,5.781275,1.0,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
299,5e15baff6887bcbb5425280d,72,1,1,0.013889,0.013889,13.756500,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,NaN
407,579fadcbc6144900014a41cc,72,1,0,0.013889,0.000000,7.079236,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0
513,5cd15bacde09c80016cf3fb4,72,1,0,0.013889,0.000000,9.389569,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,1.0,NaN,NaN,NaN,NaN,NaN
347,5d20e6639825ad00188bd75e,72,1,0,0.013889,0.000000,12.262417,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,1.0,NaN,NaN,NaN,NaN,NaN
505,5bc11bbbc11e1200018dfa3b,72,1,1,0.013889,0.013889,10.438681,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
346,5d15f6ad8078020001aa614a,72,1,0,0.013889,0.000000,8.900528,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,1.0,NaN,NaN,NaN,NaN
451,5d593e9e44609300192e33d1,72,1,0,0.013889,0.000000,13.106069,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
40,56a80ddfc89737000b22bd61,72,1,0,0.013889,0.000000,5.461458,NaN,1.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
652,Shummana.2010@hotmail.com,72,1,1,0.013889,0.013889,0.000000,NaN,NaN,1.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
634,5bb5c54dc9fbd80001037ca2,72,1,0,0.013889,0.000000,11.298139,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0
361,5bd056f9263e0a00016d20d3,72,1,0,0.013889,0.000000,10.924306,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,NaN
587,5d10ce3e4217c500197fff6a,72,1,0,0.013889,0.000000,9.606847,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
358,5e85fb2aea1691074a320cf7,72,1,0,0.013889,0.000000,17.294444,NaN,NaN,NaN,...,NaN,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
526,5d553d4e6416e9001aeaa8a9,72,1,0,0.013889,0.000000,5.317083,NaN,NaN,1.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
616,5cb72d295a63a200170af08f,74,1,0,0.013514,0.000000,6.653608,NaN,1.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
494,5e70bc96e121de000b95c20e,74,1,0,0.013514,0.000000,10.654581,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0
499,5d0155a1d3e32c00187b729d,74,1,0,0.013514,0.000000,7.978122,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,1.0,NaN,NaN,NaN,NaN,NaN
522,5c67338e7d17f800013f6176,150,2,0,0.013333,0.000000,3.085215,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,1.0,1.0,NaN,NaN,NaN
558,5e701697bb8f8a0b89b86434,76,1,0,0.013158,0.000000,11.247645,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
178,5ad90f90dec767000128a5f4,77,1,0,0.012987,0.000000,25.003052,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
179,5aeded8f0ccc2e0001858d79,77,1,0,0.012987,0.000000,5.016870,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
585,5e6b9983d4948e1491e34553,78,1,0,0.012821,0.000000,5.072487,NaN,NaN,1.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
434,5e518641c702b0000d6da0b5,78,1,0,0.012821,0.000000,10.618077,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0
433,5e10c28282052679c88dcb9f,78,1,0,0.012821,0.000000,7.754744,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
106,5c5b57d70be57e0001fa116d,78,1,0,0.012821,0.000000,10.994436,1.0,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
445,5e7b12b61699ef1025b5c871,78,1,0,0.012821,0.000000,12.598026,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
436,5e722d72a2b106155672f855,78,1,0,0.012821,0.000000,11.623615,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0
67,5de560e8cca54a4e59b74553,78,1,0,0.012821,0.000000,12.683205,1.0,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
537,5e73c7dbc26506000b938b4e,78,1,0,0.012821,0.000000,10.101603,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
97,5de62d28d82800000b7f2913,78,1,0,0.012821,0.000000,7.594167,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
580,5e2a160c77d2c70762f0e32c,78,1,1,0.012821,0.012821,10.692513,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
534,5df0c7b60a30c6102c0772ba,78,1,0,0.012821,0.000000,8.905397,NaN,NaN,NaN,...,NaN,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
487,5bb8b67cf1f9ba0001412b97,78,1,0,0.012821,0.000000,10.018641,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
583,5e6b7cde2691b2126162ee61,78,1,0,0.012821,0.000000,10.120769,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
262,5c573b734dabe6000176ac3d,149,1,0,0.006711,0.000000,8.730060,1.0,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
109,5bb202b18aba5700017f36f6,156,1,0,0.006410,0.000000,5.580731,NaN,NaN,1.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
617,5dd7b85d428d61741ca8cf19,74,0,1,0.000000,0.013514,14.852932,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
618,5e6803f09c599a0802cf5b2d,74,0,1,0.000000,0.013514,8.497500,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
662,5c1fcd13da51990001e15c37,68,0,0,0.000000,0.000000,5.414868,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
70,55887149fdf99b5a49c225e3,71,0,0,0.000000,0.000000,17.341169,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
564,5e38196845318801d994744c,78,0,0,0.000000,0.000000,12.998513,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,5d1e2045a37a4d001a1fc2cb,71,0,0,0.000000,0.000000,9.466085,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
242,5ad27a0793f87d00016ceb1c,71,0,0,0.000000,0.000000,6.242127,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,5a22e6aabf56cc00017701ef,71,0,0,0.000000,0.000000,5.570915,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
567,597fa2d8fc90e000011c586d,68,0,0,0.000000,0.000000,8.560044,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
568,5b2838e8b1cd750001498ba9,68,0,0,0.000000,0.000000,6.909279,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
619,5e6f7bdeb0939651c1cf1847,74,0,0,0.000000,0.000000,24.712176,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

### Get all contradictions and fails of a particular worker 

* Check if a specfic worker continuously contradicts themselves (and fails checks)

In [28]:
# copy from above - worker with many disagreements in target batch
worker = '5e61391b8f3f89033279a67a'

# df.loc[df['column_name'] == some_value]
df.loc[df['workerid'] == worker]

,workerid,n_annotations,n_contradictions,n_fails,contradiction_annotation_ratio,fail_annotation_ratio,average_time_question,"(afforded_unusual, unusual)","(typical_of_property, unusual)","(implied_category, unusual)",...,"(implied_category, impossible)","(affording_activity, impossible)","(afforded_unusual, impossible)","(afforded_usual, impossible)","(implied_category, rare)","(rare, typical_of_concept)","(rare, typical_of_property)","(afforded_usual, rare)","(afforded_unusual, rare)","(affording_activity, rare)"
301,5e61391b8f3f89033279a67a,72,32,0,0.444444,0.0,7.211972,2.0,NaN,4.0,...,2.0,NaN,2.0,1.0,5.0,3.0,1.0,1.0,2.0,4.0

# Analyze pairs

* compars number of annotator contradictions among pairs

### Current batch:

In [6]:
run = '3'
batch = '38'
n_q = '*'
group = 'experiment1'

data_dict_list = load_experiment_data(run, group, n_q, batch, remove_not_val = True)
name = f'run{run}-group_{group}-batch{batch}'.replace('*', '-all-')
df, filepath = get_pair_analysis(data_dict_list, name)
df.drop(['annotations_with_contradiction'], axis = 1, inplace=True)
df

Discarded 0.0 annotations.

,pair,n_annotations,n_workers,n_contradictions,n_workers_contradicting,ratio_workers_contradicting,contradiction_annotation_ratio,average_time_pair,workers_contradicting,workers_not_contradicting,...,"(afforded_usual, rare)","(implied_category, impossible)","(afforded_usual, impossible)","(implied_category, unusual)","(afforded_usual, unusual)","(afforded_unusual, unusual)","(affording_activity, rare)","(affording_activity, unusual)","(typical_of_property, unusual)","(rare, typical_of_property)"
5,roll-barrel,98,10,19,4,0.4,0.193878,94.054221,5b222aff59f9620001c109cb 5bd04def8f94190001a99...,599863d36c165e000113fadf 59bda1adab8d830001fe5...,...,NaN,NaN,NaN,3.0,1.0,4.0,NaN,NaN,2.0,1.0
1,roll-chamfer,100,10,15,4,0.4,0.150000,93.366130,5c73477642a5070001a2f940 5e418df8a3b8cc01e3363...,599863d36c165e000113fadf 59bda1adab8d830001fe5...,...,1.0,1.0,1.0,1.0,1.0,2.0,NaN,NaN,NaN,NaN
6,roll-chock,99,10,10,3,0.3,0.101010,93.169505,599863d36c165e000113fadf 5c73477642a5070001a2f...,59bda1adab8d830001fe5e4b 5b222aff59f9620001c10...,...,1.0,NaN,NaN,1.0,1.0,3.0,NaN,NaN,NaN,NaN
4,roll-axle,99,10,6,1,0.1,0.060606,93.169505,5c73477642a5070001a2f940,599863d36c165e000113fadf 59bda1adab8d830001fe5...,...,NaN,NaN,NaN,1.0,NaN,1.0,NaN,NaN,NaN,NaN
3,red-shallot,97,10,3,2,0.2,0.030928,95.115880,5a4fcc9fe0cf3d000125d7e4 5e418df8a3b8cc01e3363110,599863d36c165e000113fadf 59bda1adab8d830001fe5...,...,NaN,NaN,NaN,1.0,NaN,NaN,1.0,1.0,NaN,NaN
0,red-truffle,99,10,3,1,0.1,0.030303,93.169505,5e418df8a3b8cc01e3363110,599863d36c165e000113fadf 59bda1adab8d830001fe5...,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,round-watermelon,103,10,3,3,0.3,0.029126,90.483126,599863d36c165e000113fadf 5a4fcc9fe0cf3d000125d...,59bda1adab8d830001fe5e4b 5b222aff59f9620001c10...,...,NaN,NaN,NaN,2.0,NaN,NaN,NaN,NaN,NaN,NaN
7,_check2-_check2,11,10,0,0,0.0,0.000000,875.270050,,599863d36c165e000113fadf 59bda1adab8d830001fe5...,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8,_test2-_test2,10,10,0,0,0.0,0.000000,933.661300,,599863d36c165e000113fadf 59bda1adab8d830001fe5...,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

### Get rows with pairs annotated by specific workers:

* Check if a worker in the only one contradicting or if others also had issues with the pairs

In [7]:
worker = '5c73477642a5070001a2f940'

show_pairs_of_worker(worker, df)

Worker 5c73477642a5070001a2f940 contradicted themselves in the following pairs:

roll-barrel 	 total workers contradicting themselves: 4
roll-chamfer 	 total workers contradicting themselves: 4
roll-chock 	 total workers contradicting themselves: 3
roll-axle 	 total workers contradicting themselves: 1

### Compare to entire annotation set

In [8]:
run = '*'
batch = '*'
n_q = '*'
group = 'experiment1'

data_dict_list = load_experiment_data(run, group, n_q, batch, remove_not_val = True)
name = f'run{run}-group_{group}-batch{batch}'.replace('*', '-all-')
df, filepath = get_pair_analysis(data_dict_list, name)
df.drop(['annotations_with_contradiction'], axis = 1, inplace=True)
df

Discarded 655.0 annotations.

,pair,n_annotations,n_workers,n_contradictions,n_workers_contradicting,ratio_workers_contradicting,contradiction_annotation_ratio,average_time_pair,workers_contradicting,workers_not_contradicting,...,"(affording_activity, rare)","(implied_category, rare)","(rare, typical_of_property)","(implied_category, impossible)","(rare, typical_of_concept)","(affording_activity, impossible)","(afforded_unusual, impossible)","(afforded_usual, rare)","(afforded_unusual, rare)","(afforded_usual, impossible)"
26,roll-spindle,50,5,22,4,0.8,0.44,57.711660,5dc0395f2a1dd64710661ccd 5ddc56fbf290e7bbfa964...,5de6be6912bcf6041b3276ba,...,NaN,NaN,NaN,2.0,NaN,NaN,2.0,NaN,NaN,2.0
227,roll-lamp,50,5,17,4,0.8,0.34,85.335380,5acb5910e1546900019c413a 5d3f14f66a8a4e0018c17...,5c5758e9efe1550001dc31b6,...,NaN,NaN,NaN,1.0,NaN,NaN,2.0,NaN,NaN,1.0
96,red-mentzelia,50,5,16,4,0.8,0.32,72.657960,5b994a6d700b020001c572e2 5d134f52f1341200164f9...,5bce0e9e48473300014cafca,...,NaN,NaN,NaN,1.0,NaN,1.0,NaN,NaN,NaN,NaN
275,roll-hammer,50,5,16,5,1.0,0.32,52.465380,57e131b80cb6700001dd7e5c 5d14abad4d38750001435...,,...,NaN,NaN,NaN,1.0,NaN,NaN,2.0,NaN,NaN,1.0
39,roll-nut,50,5,16,5,1.0,0.32,53.847560,5a4bf85dac413f0001e6076a 5bfa79fdb8a4c50001b8a...,,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
371,red-tomato,95,15,0,0,0.0,0.00,122.189322,,591d7a33e4b20e00016c2798 5a473bda7aebf70001153...,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
370,round-biscuit,90,15,0,0,0.0,0.00,128.782233,,591d7a33e4b20e00016c2798 5a473bda7aebf70001153...,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
245,red-beet,95,15,0,0,0.0,0.00,116.628067,,5c8abb61e1b6910001b30615 5d8b0fb691f3e600016e6...,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
246,red-fear,15,5,0,0,0.0,0.00,217.923067,,5c8abb61e1b6910001b30615 5d8b0fb691f3e600016e6...,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
60,round-apple,95,15,0,0,0.0,0.00,119.094798,,56a80ddfc89737000b22bd61 5b7ebb54ff1109000172a...,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

### Compare contradictions between runs:

In [9]:
run = '1'
batch = '*'
n_q = '*'
group = 'experiment1'

data_dict_list = load_experiment_data(run, group, n_q, batch, remove_not_val = True)
name = f'run{run}-group_{group}-batch{batch}'.replace('*', '-all-')
df1, filepath = get_pair_analysis(data_dict_list, name)
print(f'analysis can be found at: {filepath}')

run = '3'
batch = '*'
n_q = '*'
group = 'experiment1'

data_dict_list = load_experiment_data(run, group, n_q, batch, remove_not_val = True)
name = f'run{run}-group_{group}-batch{batch}'.replace('*', '-all-')
df2, filepath = get_pair_analysis(data_dict_list, name)
print(f'analysis can be found at: {filepath}')

name1 = '1'
name2 = '3'
compare_runs(name1, name2, df1, df2, comp = 'all')
print()
compare_runs(name1, name2, df1, df2, comp = 'pairs')

Discarded 0.0 annotations.
analysis can be found at: ../analyses/pairs/run1-group_experiment1-batch-all-.csv
Discarded 655.0 annotations.
analysis can be found at: ../analyses/pairs/run3-group_experiment1-batch-all-.csv
Set 1 as a contradiction ratio of 0.26912294753704447
Set 3 as a contradiction ratio of 0.2091286307053942
The ratio is based on the number of workers annotating a pair.
A worker always annotates a full set.

Set 1 as a contradiction ratio of 0.23765786452353616
Set 3 as a contradiction ratio of 0.23180256169946892
The ratio is based on the number of workers annotating a pair.
A worker always annotates a full set.
This analysis only includes pairs annotated in run 1 and run 3.

(0.23765786452353616, 0.23180256169946892)

# Inter-annotator agreement

* Total agreement
* Agreement by relations
* agreement after removing annotators with many contradictions/annotators who fail checks/contradictory annotations

## Total iaa:

In [10]:
run = '3'
batch = '*'
n_q = '*'
group = 'experiment1'
print(f"Run {run}:")
data_dict_list = load_experiment_data(run, group, n_q, batch, remove_not_val = True)
get_agreement(data_dict_list)

run = '1'
batch = '*'
n_q = '*'
group = 'experiment1'
print(f"Run {run}:")
data_dict_list = load_experiment_data(run, group, n_q, batch, remove_not_val = True)

get_agreement(data_dict_list)

Run 3:
Discarded 655.0 annotations.
Krippendorff's alpha: 0.2463725697540442
Proportional agreement (pairwise): 0.6385114873424212

Run 1:
Discarded 0.0 annotations.
Krippendorff's alpha: 0.2413329996998821
Proportional agreement (pairwise): 0.6204625909422005

{'Krippendorff': 0.2413329996998821, 'Proportional': 0.6204625909422005}

## IAA by relation

In [11]:
runs = ['3', '1']
experiment_name = 'experiment1'
path, df = agreement_relations_across_runs(runs, experiment_name)
print(f'Results written to: {path}')
df

Discarded 655.0 annotations.
Discarded 0.0 annotations.
Results written to: ../analyses/iaa/relations_runs3-1.csv

,relation,3_Krippendorff,3_Proportional,1_Krippendorff,1_Proportional
0,rare,0.162885,0.596243,NaN,NaN
1,_check,0.643894,0.894828,0.904637,0.964443
2,impossible,0.143642,0.675566,0.183925,0.679565
3,afforded_unusual,0.035775,0.525967,0.108460,0.557623
4,afforded_usual,0.181940,0.660557,0.336767,0.698580
5,test_true,0.080396,0.813115,NaN,NaN
6,test_false,0.106607,0.767095,NaN,NaN
7,creative,0.065253,0.557281,0.040020,0.524894
8,variability_subcategories,NaN,NaN,0.157270,0.579637
9,unusual,0.171452,0.584685,0.120147,0.561644
10,typical_of_property,0.252850,0.770219,0.326482,0.682547
11,variability_open,0.216772,0.607166,0.143751,0.580081
12,implied_category,0.273568,0.659212,0.260459,0.629956
13,variability_limited,0.120893,0.562074,0.197795,0.599990
14,affording_activity,0.194360,0.653146,0.149149,0.672259
15,typical_of_concept,0.332461,0.716034,0.367910,0.689440

## Agreement after removing workers or annotations:

In [12]:
run = '3'
batch = '*'
n_q = '*'
group = 'experiment1'

print('Total Agreement')
data_dict_list = load_experiment_data(run, group, n_q, batch, remove_not_val = True)
get_agreement(data_dict_list)
print('-------')
print()

print('Removing pairs with many contradictions:')
category = 'pairs_contradictions'
print(f'analyze {category}')
annotations_clean, annotations_removed = clean_annotations(run, group, n_q, batch, category)
print('agreement clean')
get_agreement(annotations_clean)
#print('agreement rest')
#get_agreement(annotations_removed)


category = 'worker_contradictions'
print(f'analyze {category}')
annotations_clean, annotations_removed = clean_annotations(run, group, n_q, batch, category)
print('agreement clean')
get_agreement(annotations_clean)
#print('agreement rest')
#get_agreement(annotations_removed)
print()

category = 'worker_checks'
print(f'analyze {category}')
annotations_clean, annotations_removed = clean_annotations(run, group, n_q, batch, category)
print('agreement clean')
get_agreement(annotations_clean)
#print('agreement rest')
#get_agreement(annotations_removed)

Total Agreement
Discarded 655.0 annotations.
Krippendorff's alpha: 0.2463725697540442
Proportional agreement (pairwise): 0.6385114873424212

-------

Removing pairs with many contradictions:
analyze pairs_contradictions
Discarded 655.0 annotations.
Found 21467 clean annotations.
Round 7670 to remove.

agreement clean
Krippendorff's alpha: 0.34022524272587773
Proportional agreement (pairwise): 0.6873914995739058

analyze worker_contradictions
Discarded 655.0 annotations.
Found 18983 clean annotations.
Round 10100 to remove.

agreement clean
Krippendorff's alpha: 0.2736523689712784
Proportional agreement (pairwise): 0.6619245304424161


analyze worker_checks
Discarded 655.0 annotations.
Found 26554 clean annotations.
Round 2529 to remove.

agreement clean
Krippendorff's alpha: 0.26865514911812405
Proportional agreement (pairwise): 0.6499509093252589

{'Krippendorff': 0.26865514911812405, 'Proportional': 0.6499509093252589}