# Annotation analysis

This noteboook

* illustrates the steps of the analysis currently implemented
* is used to analyze and monitor workers batch by batch

In [1]:
from load_data import load_experiment_data
from analyze_workers import get_worker_analysis
from analyze_pairs import get_pair_analysis
from analyze_pairs import show_pairs_of_worker
from analyze_pairs import compare_runs
from calculate_iaa import get_agreement
from clean_annotations import clean_annotations
from analyze_relations_and_examples import agreement_relations_across_runs

# Analyze worker contradictions:

* Workers with highest contradiction to annotations ratio appear on top
* use the pandas dataframe sort method to sort on other values: 

`df.sort_values(by, axis=0, ascending=True, inplace=False, kind='quicksort', na_position='last')`

### Current batch

In [25]:
run = 3
batch = 47
n_q = 70
group = 'experiment1'

data_dict_list = load_experiment_data(run, group, n_q, batch, remove_not_val = True)
name = f'run{run}-group_{group}-batch{batch}'.replace('*', '-all-')
df, filepath = get_worker_analysis(data_dict_list, name)
df.drop(['annotations'], axis = 1, inplace=True)
df

Discarded 0.0 annotations.

,workerid,n_annotations,n_contradictions,n_fails,contradiction_annotation_ratio,fail_annotation_ratio,average_time_question,"(afforded_usual, unusual)","(afforded_unusual, unusual)","(afforded_usual, rare)",...,"(afforded_unusual, rare)","(implied_category, rare)","(afforded_unusual, impossible)","(implied_category, impossible)","(implied_category, unusual)","(rare, typical_of_concept)","(rare, typical_of_property)","(typical_of_concept, unusual)","(typical_of_property, unusual)","(impossible, typical_of_property)"
6,5e790f7147422a4bfcd6e560,72,28,0,0.388889,0.000000,10.776639,2.0,2.0,2.0,...,2.0,4.0,NaN,1.0,5.0,3.0,2.0,3.0,2.0,NaN
5,5dead1e57ecb2a1f9829bb69,72,17,0,0.236111,0.000000,10.588944,1.0,4.0,1.0,...,3.0,1.0,2.0,2.0,2.0,NaN,NaN,NaN,NaN,NaN
7,5e870a2014e29700082b9ba8,72,17,0,0.236111,0.000000,12.799778,1.0,3.0,1.0,...,3.0,1.0,3.0,1.0,1.0,1.0,NaN,1.0,NaN,NaN
2,5ce02b5124b7ee0015fc2799,72,13,0,0.180556,0.000000,7.611694,NaN,1.0,1.0,...,4.0,3.0,2.0,NaN,NaN,1.0,1.0,NaN,NaN,NaN
0,5b116068160a2e0001acb494,72,12,1,0.166667,0.013889,17.928819,1.0,3.0,1.0,...,3.0,1.0,1.0,1.0,NaN,NaN,NaN,NaN,NaN,NaN
1,5bdb25a0cf36dd0001e18da5,72,10,0,0.138889,0.000000,17.913542,NaN,2.0,NaN,...,1.0,2.0,1.0,1.0,3.0,NaN,NaN,NaN,NaN,NaN
9,5e67ec7516f67809dfd6f8c9,72,10,0,0.138889,0.000000,11.224139,NaN,4.0,NaN,...,4.0,NaN,2.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8,5e8783b0fde5153fbd9dca43,72,5,0,0.069444,0.000000,31.395750,NaN,1.0,NaN,...,2.0,NaN,1.0,NaN,NaN,NaN,NaN,NaN,NaN,1.0
3,5d0fbad182a931000182bbfb,72,4,0,0.055556,0.000000,22.868833,NaN,2.0,NaN,...,NaN,NaN,1.0,NaN,1.0,NaN,NaN,NaN,NaN,NaN
4,5daf6f5d5f543b00151fb4fc,72,0,0,0.000000,0.000000,7.444306,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

### All annotations

* Workers with highest contradiction to annotations ratio appear on top
* use the pandas dataframe sort method to sort on other values: 
* Check how the behavior of a specific worker with many contradictions compares to other workers

`df.sort_values(by, axis=0, ascending=True, inplace=False, kind='quicksort', na_position='last')`

In [22]:
run = '*'
batch = '*'
n_q = '*'
group = 'experiment1'

data_dict_list = load_experiment_data(run, group, n_q, batch, remove_not_val = True)
name = f'run{run}-group_{group}-batch{batch}'.replace('*', '-all-')
df, filepath = get_worker_analysis(data_dict_list, name)
df.drop(['annotations'], axis = 1, inplace=True)
df[:10]

Discarded 655.0 annotations.

,workerid,n_annotations,n_contradictions,n_fails,contradiction_annotation_ratio,fail_annotation_ratio,average_time_question,"(afforded_unusual, unusual)","(typical_of_property, unusual)","(implied_category, unusual)",...,"(implied_category, impossible)","(affording_activity, impossible)","(afforded_unusual, impossible)","(afforded_usual, impossible)","(implied_category, rare)","(rare, typical_of_concept)","(rare, typical_of_property)","(afforded_usual, rare)","(afforded_unusual, rare)","(affording_activity, rare)"
298,5bfed16ca1f050000102693c,74,62,1,0.837838,0.013514,14.382986,3.0,4.0,4.0,...,4.0,NaN,4.0,5.0,3.0,4.0,4.0,4.0,3.0,NaN
458,5c042ba4bb85e60001c05c83,72,47,0,0.652778,0.000000,7.812292,1.0,3.0,5.0,...,3.0,1.0,1.0,2.0,6.0,4.0,3.0,2.0,2.0,3.0
706,5d76a2dc2a476a0001ce6843,72,45,1,0.625000,0.013889,16.482319,NaN,3.0,5.0,...,3.0,2.0,NaN,NaN,5.0,5.0,3.0,NaN,NaN,5.0
358,IT Manager,72,44,2,0.611111,0.027778,0.000000,4.0,3.0,3.0,...,3.0,1.0,3.0,2.0,2.0,1.0,3.0,3.0,4.0,2.0
373,5e4e86b070e1ed2d6e4e3f62,72,42,1,0.583333,0.013889,4.293264,NaN,5.0,5.0,...,2.0,1.0,NaN,NaN,5.0,4.0,5.0,NaN,NaN,4.0
378,5e7cbbbcf0a5a004b60b48f7,72,41,1,0.569444,0.013889,11.482222,NaN,2.0,1.0,...,4.0,4.0,NaN,NaN,5.0,4.0,6.0,NaN,NaN,6.0
290,5d323affa754dc00018b15cc,150,82,3,0.546667,0.020000,17.685089,6.0,6.0,5.0,...,5.0,1.0,5.0,5.0,4.0,5.0,5.0,5.0,5.0,NaN
477,5c1f3a7c10677f0001da2157,72,39,0,0.541667,0.000000,9.921528,3.0,5.0,5.0,...,1.0,1.0,1.0,1.0,3.0,1.0,4.0,1.0,2.0,1.0
241,5c91321c0375460001034cb8,71,38,0,0.535211,0.000000,12.942127,2.0,6.0,6.0,...,4.0,1.0,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
422,5ddd128c961cb3c6780ff181,72,36,0,0.500000,0.000000,8.403056,2.0,2.0,5.0,...,3.0,2.0,1.0,NaN,4.0,3.0,1.0,NaN,2.0,1.0

In [4]:
# Good workers
#df[-20:]

### Get all contradictions and fails of a particular worker 

* Check if a specfic worker continuously contradicts themselves (and fails checks)

In [23]:
# copy from above - worker with many disagreements in target batch
worker = '5e790f7147422a4bfcd6e560'


# df.loc[df['column_name'] == some_value]
df.loc[df['workerid'] == worker]

,workerid,n_annotations,n_contradictions,n_fails,contradiction_annotation_ratio,fail_annotation_ratio,average_time_question,"(afforded_unusual, unusual)","(typical_of_property, unusual)","(implied_category, unusual)",...,"(implied_category, impossible)","(affording_activity, impossible)","(afforded_unusual, impossible)","(afforded_usual, impossible)","(implied_category, rare)","(rare, typical_of_concept)","(rare, typical_of_property)","(afforded_usual, rare)","(afforded_unusual, rare)","(affording_activity, rare)"
347,5e790f7147422a4bfcd6e560,72,28,0,0.388889,0.0,10.776639,2.0,2.0,5.0,...,1.0,NaN,NaN,NaN,4.0,3.0,2.0,2.0,2.0,NaN

# Analyze pairs

* compars number of annotator contradictions among pairs

### Current batch:

In [13]:
run = '3'
batch = '46'
n_q = '*'
group = 'experiment1'

data_dict_list = load_experiment_data(run, group, n_q, batch, remove_not_val = True)
name = f'run{run}-group_{group}-batch{batch}'.replace('*', '-all-')
df, filepath = get_pair_analysis(data_dict_list, name)
df.drop(['annotations_with_contradiction'], axis = 1, inplace=True)
df

Discarded 0.0 annotations.

,pair,n_annotations,n_workers,n_contradictions,n_workers_contradicting,ratio_workers_contradicting,contradiction_annotation_ratio,average_time_pair,workers_contradicting,workers_not_contradicting,...,"(typical_of_property, unusual)","(afforded_usual, impossible)","(afforded_usual, rare)","(impossible, typical_of_property)","(affording_activity, unusual)","(affording_activity, rare)","(typical_of_concept, unusual)","(implied_category, impossible)","(impossible, typical_of_concept)","(affording_activity, impossible)"
4,roll-plunger,109,10,39,9,0.9,0.357798,59.474925,5baca6927d22360001541382 5e85cdeab6f70303224b6...,5c43e536d780340001c6a3e1,...,NaN,2.0,2.0,1.0,NaN,NaN,2.0,3.0,3.0,NaN
0,roll-headboard,108,10,26,7,0.7,0.240741,60.118063,5baca6927d22360001541382 5e85cdeab6f70303224b6...,5c43e536d780340001c6a3e1 5e8b338ed124690353004...,...,1.0,2.0,2.0,1.0,NaN,NaN,NaN,NaN,NaN,NaN
3,roll-wagon,107,10,20,4,0.4,0.186916,60.836865,5e85cdeab6f70303224b6105 5e8b36411f49d70640e09...,5baca6927d22360001541382 5c43e536d780340001c6a...,...,NaN,2.0,2.0,NaN,NaN,NaN,NaN,3.0,NaN,NaN
6,roll-rail,108,10,20,7,0.7,0.185185,59.939303,5baca6927d22360001541382 5e85cdeab6f70303224b6...,5c43e536d780340001c6a3e1 5e8a44c7524dca6ef7215...,...,NaN,4.0,1.0,1.0,NaN,NaN,NaN,2.0,1.0,NaN
1,red-frog,106,10,14,5,0.5,0.132075,61.301243,5c43e536d780340001c6a3e1 5e8a44c7524dca6ef7215...,5baca6927d22360001541382 5e85cdeab6f70303224b6...,...,3.0,NaN,NaN,1.0,3.0,2.0,1.0,NaN,NaN,NaN
2,round-world,105,10,9,2,0.2,0.085714,62.561990,5e8b36411f49d70640e09943 IT Manager,5baca6927d22360001541382 5c43e536d780340001c6a...,...,1.0,NaN,NaN,NaN,1.0,2.0,1.0,NaN,NaN,NaN
5,red-blackboard,107,10,8,2,0.2,0.074766,60.836865,5e8a44c7524dca6ef721565c IT Manager,5baca6927d22360001541382 5c43e536d780340001c6a...,...,NaN,NaN,NaN,NaN,2.0,1.0,1.0,1.0,1.0,1.0
7,_check3-_check3,11,10,0,0,0.0,0.000000,588.961000,,5baca6927d22360001541382 5c43e536d780340001c6a...,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8,_test2-_test2,10,10,0,0,0.0,0.000000,698.937700,,5baca6927d22360001541382 5c43e536d780340001c6a...,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

### Get rows with pairs annotated by specific workers:

* Check if a worker in the only one contradicting or if others also had issues with the pairs

In [14]:
worker = 'IT Manager'

show_pairs_of_worker(worker, df)

Worker IT Manager contradicted themselves in the following pairs:

### Compare to entire annotation set

In [15]:
run = '*'
batch = '*'
n_q = '*'
group = 'experiment1'

data_dict_list = load_experiment_data(run, group, n_q, batch, remove_not_val = True)
name = f'run{run}-group_{group}-batch{batch}'.replace('*', '-all-')
df, filepath = get_pair_analysis(data_dict_list, name)
df.drop(['annotations_with_contradiction'], axis = 1, inplace=True)
df

Discarded 655.0 annotations.

,pair,n_annotations,n_workers,n_contradictions,n_workers_contradicting,ratio_workers_contradicting,contradiction_annotation_ratio,average_time_pair,workers_contradicting,workers_not_contradicting,...,"(affording_activity, unusual)","(rare, typical_of_concept)","(rare, typical_of_property)","(implied_category, rare)","(implied_category, impossible)","(affording_activity, impossible)","(afforded_unusual, impossible)","(afforded_usual, rare)","(afforded_unusual, rare)","(afforded_usual, impossible)"
227,roll-lamp,50,5,17,4,0.800000,0.340000,85.335380,5acb5910e1546900019c413a 5d3f14f66a8a4e0018c17...,5c5758e9efe1550001dc31b6,...,NaN,NaN,NaN,NaN,1.0,NaN,2.0,NaN,NaN,1.0
39,roll-nut,50,5,16,5,1.000000,0.320000,53.847560,5a4bf85dac413f0001e6076a 5bfa79fdb8a4c50001b8a...,,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
275,roll-hammer,50,5,16,5,1.000000,0.320000,52.465380,57e131b80cb6700001dd7e5c 5d14abad4d38750001435...,,...,NaN,NaN,NaN,NaN,1.0,NaN,2.0,NaN,NaN,1.0
26,roll-spindle,150,15,48,10,0.666667,0.320000,75.754453,5dc0395f2a1dd64710661ccd 5ddc56fbf290e7bbfa964...,5de6be6912bcf6041b3276ba 589cc7bd8bf22a00015b7...,...,NaN,1.0,3.0,2.0,4.0,NaN,3.0,2.0,2.0,3.0
87,roll-dowel,149,15,45,11,0.733333,0.302013,56.773827,5b281303007d870001c7f24a 5c097af754deae0001ac6...,5cfa90ccd128950001311ed0 5d598dff48766d0001949...,...,NaN,3.0,2.0,5.0,2.0,NaN,NaN,4.0,3.0,3.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
354,round-chicken,50,5,0,0,0.000000,0.000000,69.145900,,59e5177f16ecc200016fefc1 5c07b16bfd9c080001708...,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
316,red-cabbage,98,15,0,0,0.000000,0.000000,195.999652,,5d362118bd3f570016067a6b 5d40128e2b6eaf00155f2...,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
352,round-beet,93,15,0,0,0.000000,0.000000,142.238313,,59e5177f16ecc200016fefc1 5c07b16bfd9c080001708...,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
265,round-football,50,5,0,0,0.000000,0.000000,85.898220,,5ad90f90dec767000128a5f4 5aeded8f0ccc2e0001858...,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
56,round-syrup,148,15,0,0,0.000000,0.000000,72.702280,,5a7622caf49c9a0001f2f7a8 5db954a2af32f6000a8fe...,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

### Compare contradictions between runs:

In [26]:
run = '1'
batch = '*'
n_q = '*'
group = 'experiment1'

data_dict_list = load_experiment_data(run, group, n_q, batch, remove_not_val = True)
name = f'run{run}-group_{group}-batch{batch}'.replace('*', '-all-')
df1, filepath = get_pair_analysis(data_dict_list, name)
print(f'analysis can be found at: {filepath}')

run = '3'
batch = '*'
n_q = '*'
group = 'experiment1'

data_dict_list = load_experiment_data(run, group, n_q, batch, remove_not_val = True)
name = f'run{run}-group_{group}-batch{batch}'.replace('*', '-all-')
df2, filepath = get_pair_analysis(data_dict_list, name)
print(f'analysis can be found at: {filepath}')

name1 = '1'
name2 = '3'
compare_runs(name1, name2, df1, df2, comp = 'all')
print()
compare_runs(name1, name2, df1, df2, comp = 'pairs')

Discarded 0.0 annotations.
analysis can be found at: ../analyses/pairs/run1-group_experiment1-batch-all-.csv
Discarded 655.0 annotations.
analysis can be found at: ../analyses/pairs/run3-group_experiment1-batch-all-.csv
Set 1 as a contradiction ratio of 0.26912294753704447
Set 3 as a contradiction ratio of 0.23076923076923078
The ratio is based on the number of workers annotating a pair.
A worker always annotates a full set.

Set 1 as a contradiction ratio of 0.2510948905109489
Set 3 as a contradiction ratio of 0.25537982888255123
The ratio is based on the number of workers annotating a pair.
A worker always annotates a full set.
This analysis only includes pairs annotated in run 1 and run 3.

(0.2510948905109489, 0.25537982888255123)

# Inter-annotator agreement

* Total agreement
* Agreement by relations
* agreement after removing annotators with many contradictions/annotators who fail checks/contradictory annotations

## Total iaa:

In [27]:
run = '3'
batch = '*'
n_q = '*'
group = 'experiment1'
print(f"Run {run}:")
data_dict_list = load_experiment_data(run, group, n_q, batch, remove_not_val = True)
get_agreement(data_dict_list)

run = '1'
batch = '*'
n_q = '*'
group = 'experiment1'
print(f"Run {run}:")
data_dict_list = load_experiment_data(run, group, n_q, batch, remove_not_val = True)

get_agreement(data_dict_list)

Run 3:
Discarded 655.0 annotations.
Krippendorff's alpha: 0.23336207839907597
Proportional agreement (pairwise): 0.6304754199128316

Run 1:
Discarded 0.0 annotations.
Krippendorff's alpha: 0.2413329996998821
Proportional agreement (pairwise): 0.6204625909422005

{'Krippendorff': 0.2413329996998821, 'Proportional': 0.6204625909422005}

## IAA of collapsed relations

In [28]:
run = '3'
batch = '*'
n_q = '*'
group = 'experiment1'
print(f"Run {run}:")
data_dict_list = load_experiment_data(run, group, n_q, batch, remove_not_val = True)
get_agreement(data_dict_list)

collapse_relations = 'pos_neg'
print(f'collapsing {collapse_relations}')
get_agreement(data_dict_list, collapse_relations = collapse_relations)

collapse_relations = 'levels'
print(f'collapsing {collapse_relations}')
get_agreement(data_dict_list, collapse_relations = collapse_relations)

collapse_relations = 'similar_relations'
print(f'collapsing {collapse_relations}')
get_agreement(data_dict_list, collapse_relations = collapse_relations)


run = '1'
batch = '*'
n_q = '*'
group = 'experiment1'
print(f"Run {run}:")
data_dict_list = load_experiment_data(run, group, n_q, batch, remove_not_val = True)
collapse_relations = 'pos_neg'
print(f'collapsing {collapse_relations}')
get_agreement(data_dict_list, collapse_relations = collapse_relations)

collapse_relations = 'levels'
print(f'collapsing {collapse_relations}')
get_agreement(data_dict_list, collapse_relations = collapse_relations)

collapse_relations = 'similar_relations'
print(f'collapsing {collapse_relations}')
get_agreement(data_dict_list, collapse_relations = collapse_relations)

Run 3:
Discarded 655.0 annotations.
Krippendorff's alpha: 0.23336207839907597
Proportional agreement (pairwise): 0.6304754199128316

collapsing pos_neg
pos_neg
Krippendorff's alpha: 0.1290459652595516
Proportional agreement (pairwise): 0.5818103504182993

collapsing levels
levels
Krippendorff's alpha: 0.1809414319009356
Proportional agreement (pairwise): 0.5856217398765973

collapsing similar_relations
similar_relations
Krippendorff's alpha: 0.2228834198795826
Proportional agreement (pairwise): 0.637612435001261

Run 1:
Discarded 0.0 annotations.
collapsing pos_neg
pos_neg
Krippendorff's alpha: 0.16756939242308677
Proportional agreement (pairwise): 0.5759980191358617

collapsing levels
levels
Krippendorff's alpha: 0.20455848112125752
Proportional agreement (pairwise): 0.582823814823261

collapsing similar_relations
similar_relations
Krippendorff's alpha: 0.24340570835907704
Proportional agreement (pairwise): 0.6233640269121777

{'Krippendorff': 0.24340570835907704, 'Proportional': 0.6233640269121777}

## IAA by relation

In [29]:
runs = ['3', '1']
experiment_name = 'experiment1'
path, df = agreement_relations_across_runs(runs, experiment_name)
print(f'Results written to: {path}')
df

Discarded 655.0 annotations.
Discarded 0.0 annotations.
Results written to: ../analyses/iaa/relations_runs3-1.csv

,relation,3_Krippendorff,3_Proportional,1_Krippendorff,1_Proportional
0,unusual,0.163739,0.580171,0.120147,0.561644
1,typical_of_property,0.232499,0.761854,0.326482,0.682547
2,creative,0.062932,0.549106,0.040020,0.524894
3,afforded_unusual,0.041609,0.532267,0.108460,0.557623
4,impossible,0.130651,0.666326,0.183925,0.679565
5,afforded_usual,0.148028,0.633726,0.336767,0.698580
6,typical_of_concept,0.308479,0.709056,0.367910,0.689440
7,test_false,0.168062,0.725298,NaN,NaN
8,implied_category,0.263127,0.647922,0.260459,0.629956
9,test_true,0.061648,0.789103,NaN,NaN
10,variability_open,0.205872,0.601707,0.143751,0.580081
11,_check,0.599204,0.883060,0.904637,0.964443
12,rare,0.144133,0.585215,NaN,NaN
13,variability_subcategories,NaN,NaN,0.157270,0.579637
14,affording_activity,0.205192,0.654540,0.149149,0.672259
15,variability_limited,0.106971,0.554742,0.197795,0.599990

## Agreement after removing workers or annotations:

In [32]:
run = '3'
batch = '*'
n_q = '*'
group = 'experiment1'

print('Total Agreement')
data_dict_list = load_experiment_data(run, group, n_q, batch, remove_not_val = True)
get_agreement(data_dict_list)
print('-------')
print()

print('Removing pair annotations with many contradictions:')
category = 'pairs_contradictions'
print(f'analyze {category}')
annotations_clean, annotations_removed = clean_annotations(run, group, n_q, batch, category)
print('agreement clean')
get_agreement(annotations_clean)
#print('agreement rest')
#get_agreement(annotations_removed)


category = 'worker_contradictions'
print(f'analyze {category}')
annotations_clean, annotations_removed = clean_annotations(run, group, n_q, batch, category)
print('agreement clean')
get_agreement(annotations_clean)
#print('agreement rest')
#get_agreement(annotations_removed)
print()

category = 'worker_checks'
print(f'analyze {category}')
annotations_clean, annotations_removed = clean_annotations(run, group, n_q, batch, category)
print('agreement clean')
get_agreement(annotations_clean)
#print('agreement rest')
#get_agreement(annotations_removed)

Total Agreement
Discarded 655.0 annotations.
Krippendorff's alpha: 0.23336207839907597
Proportional agreement (pairwise): 0.6304754199128316

-------

Removing pair annotations with many contradictions:
analyze pairs_contradictions
Discarded 655.0 annotations.
Found 24827 clean annotations.
Round 10212 to remove.

agreement clean
Krippendorff's alpha: 0.33405102479157067
Proportional agreement (pairwise): 0.68651450192071

analyze worker_contradictions
Discarded 655.0 annotations.
Found 24877 clean annotations.
Round 10100 to remove.

agreement clean
Krippendorff's alpha: 0.24953378047207264
Proportional agreement (pairwise): 0.6498735089301452


analyze worker_checks
Discarded 655.0 annotations.
Found 32448 clean annotations.
Round 2529 to remove.

agreement clean
Krippendorff's alpha: 0.25028983009201133
Proportional agreement (pairwise): 0.639896601266422

{'Krippendorff': 0.25028983009201133, 'Proportional': 0.639896601266422}